### PR TITLE
Improve error message if clang is not installed

### PR DESCRIPTION
**Pull request by KucicM**
Current error message is `FileNotFoundError: [Errno 2] No such file or directory: 'clang'`

### CODE REVIEW

**Comment by geohot** [comment]
This is slow, I'd rather catch the error and provide a way to fix it

**Comment by KucicM** [comment]
Added try/except around compile, but I'm not sure what do you mean by `provide a way to fix it.` 
Should message be something like `clang not installed. run: sudo apt install clang to fix it`?

**Comment by geohot** [comment]
Looking at it, I'm not sure we need this complexity. File not found 'clang' is a pretty clear error

**Comment by wmuron** [comment]
>  File not found 'clang' is a pretty clear error

I wanted to try out the library, since I am following this project for some time now, and still didn't have a chance to give it a try.

The first experience when trying to run a simplest hello world in tinygrad is getting a wall of exceptions, and vague message `FileNotFoundError [Errno 2] No such file or directory: 'clang'`. I can understand that it's self-explanatory, but from a user perspective it's a bit harsh starting point, IMO.

**Pull request closed without merging**
