### PR TITLE
Fix calculation of vmin and vmax in multiplication

### PR DESCRIPTION
**Pull request by S-Lykles**
Fix calculation of vmin and vmax in multiplication when one src is negative and the other src has negative min and positive max.

Using render from `test_uop_symbolic`
```python
print(render(-2 * Variable("a", -2, 4)))
```
Outputs:
```
('(a*-2)', -2147483648, 2147483647)
```

Added a test as well

### CODE REVIEW

**Comment by chenyuxyz** [comment]
cool, this used to have an issue but maybe it's due to unrelated bugs. let me test with resnet and will merge if it looks good

**Comment by S-Lykles** [comment]
Wait this is kind of the same as #7278 ?

**Comment by S-Lykles** [comment]
I was working on improving div_folding and I use the min/max of the sub-expression for that.

**Comment by S-Lykles** [comment]
So like `a[-2, inf]*b[0, 4]` should be `[-8, inf]` and not `[nan, nan]`?

**Comment by chenyuxyz** [comment]
yea bounds should not have nan as comparison with nan is weird

i am testing with #7336 to limit these to non-float, i think float bounds are not properly handled anyway and this approach is cleaner

**Pull request merged**
