### PR TITLE
Import whole math module in tensor.py

### PR DESCRIPTION
**Pull request by c143**

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                        24              24
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by wozeparrot** [comment]
I don't follow, is this faster than the individual imports? what was wrong with them before?

**Comment by c143** [comment]
@wozeparrot request from geroge: https://youtu.be/yyHU5SJ-BPA?t=5779

**Comment by wozeparrot** [comment]
got it, didn't catch that stream, my bad

**Pull request merged**
