### PR TITLE
[WIP] Do math in same type as buffer dtype

### PR DESCRIPTION
**Pull request by kunwar31**
changes to do math in same dtype as buffer dtype, and upcast to highest priority dtype when operands are of different dtypes. 
on 7900XTX this gives 

```
GPU=1 HALF=0 BIG=1 python -W ignore test/test_speed_v_torch.py
add                             8192x 8192   70.45 ms (    0.95 GFLOPS    11.43 GB/s) in torch,    1.31 ms (   51.39 GFLOPS   616.67 GB/s) in tinygrad,    0.02x faster      67.11 MOPS   805.31 MB
exp                             8192x 8192  110.82 ms (    1.21 GFLOPS     4.84 GB/s) in torch,    0.82 ms (  163.48 GFLOPS   653.93 GB/s) in tinygrad,    0.01x faster     134.22 MOPS   536.87 MB
gemm                            2048x 2048  162.96 ms (  105.42 GFLOPS     0.31 GB/s) in torch,    2.28 ms ( 7528.15 GFLOPS    22.06 GB/s) in tinygrad,    0.01x faster   17179.87 MOPS    50.33 MB
gemm                            4096x 4096 1289.31 ms (  106.60 GFLOPS     0.16 GB/s) in torch,   17.32 ms ( 7936.21 GFLOPS    11.63 GB/s) in tinygrad,    0.01x faster  137438.95 MOPS   201.33 MB
conv bs: 32 chans:128 -> 128 k:1            367.02 ms (   46.81 GFLOPS     1.46 GB/s) in torch,    1.27 ms (13489.88 GFLOPS   421.61 GB/s) in tinygrad,    0.00x faster   17179.87 MOPS   536.94 MB
conv bs:  4 chans:128 -> 128 k:3            179.92 ms (  107.42 GFLOPS     0.38 GB/s) in torch,    1.21 ms (15982.02 GFLOPS    56.85 GB/s) in tinygrad,    0.01x faster   19327.35 MOPS    68.76 MB
conv bs:  4 chans:128 -> 128 k:5            452.53 ms (  114.96 GFLOPS     0.15 GB/s) in torch,    6.97 ms ( 7468.98 GFLOPS     9.87 GB/s) in tinygrad,    0.02x faster   52022.48 MOPS    68.76 MB
```

```
GPU=1 HALF=1 BIG=1 python -W ignore test/test_speed_v_torch.py
add                             8192x 8192   70.00 ms (    0.96 GFLOPS     5.75 GB/s) in torch,    0.78 ms (   85.71 GFLOPS   514.23 GB/s) in tinygrad,    0.01x faster      67.11 MOPS   402.65 MB
exp                             8192x 8192  110.55 ms (    1.21 GFLOPS     2.43 GB/s) in torch,    0.45 ms (  297.45 GFLOPS   594.90 GB/s) in tinygrad,    0.00x faster     134.22 MOPS   268.44 MB
gemm                            2048x 2048  163.04 ms (  105.37 GFLOPS     0.15 GB/s) in torch,    1.45 ms (11816.01 GFLOPS    17.31 GB/s) in tinygrad,    0.01x faster   17179.87 MOPS    25.17 MB
gemm                            4096x 4096 1293.58 ms (  106.25 GFLOPS     0.08 GB/s) in torch,    8.54 ms (16085.20 GFLOPS    11.78 GB/s) in tinygrad,    0.01x faster  137438.95 MOPS   100.66 MB
conv bs: 32 chans:128 -> 128 k:1            366.71 ms (   46.85 GFLOPS     0.73 GB/s) in torch,    1.51 ms (11412.33 GFLOPS   178.34 GB/s) in tinygrad,    0.00x faster   17179.87 MOPS   268.47 MB
conv bs:  4 chans:128 -> 128 k:3            193.16 ms (  100.06 GFLOPS     0.18 GB/s) in torch,    1.35 ms (14273.78 GFLOPS    25.39 GB/s) in tinygrad,    0.01x faster   19327.35 MOPS    34.38 MB
conv bs:  4 chans:128 -> 128 k:5            457.79 ms (  113.64 GFLOPS     0.08 GB/s) in torch,    4.34 ms (11997.22 GFLOPS     7.93 GB/s) in tinygrad,    0.01x faster   52022.48 MOPS    34.38 MB
```

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/linearizer.py            83              36
tinygrad/codegen/optimizer.py              2               2
tinygrad/helpers.py                       18               9
tinygrad/renderer/cstyle.py                3               5
tinygrad/runtime/ops_clang.py              3               2
tinygrad/runtime/ops_cuda.py               4               2
tinygrad/runtime/ops_gpu.py                5               3
tinygrad/runtime/ops_hip.py                4               2
tinygrad/runtime/ops_llvm.py               3               2
tinygrad/runtime/ops_metal.py              3               2
tinygrad/runtime/ops_webgpu.py             3               1
------------------------------------------------------------
total                                    131              66
------------------------------------------------------------
lines added in the tinygrad folder: 65
```

**Comment by geohot** [comment]
So I think we should get UOps tests for other math types added first, confirming that the backends are correctly doing the math in that type. #1522

**Comment by kunwar31** [comment]
> So I think we should get UOps tests for other math types added first, confirming that the backends are correctly doing the math in that type. #1522

Added half uops tests. it works with GPU=1 and POCL (CI doesn't support half math)
also works on AMD OpenCL
```
test_add_half (__main__.TestHalfUOps.test_add_half) ... ok
test_cmplt_half (__main__.TestHalfUOps.test_cmplt_half) ... ok
test_div_half (__main__.TestHalfUOps.test_div_half) ... ok
test_exp2_half (__main__.TestHalfUOps.test_exp2_half) ... ok
test_log2_half (__main__.TestHalfUOps.test_log2_half) ... ok
test_max_half (__main__.TestHalfUOps.test_max_half) ... ok
test_mul_half (__main__.TestHalfUOps.test_mul_half) ... ok
test_mulacc_half (__main__.TestHalfUOps.test_mulacc_half) ... ok
test_sin_half (__main__.TestHalfUOps.test_sin_half) ... ok
test_sqrt_half (__main__.TestHalfUOps.test_sqrt_half) ... ok
test_sub_half (__main__.TestHalfUOps.test_sub_half) ... ok
test_where_half (__main__.TestHalfUOps.test_where_half) ... ok
```

**Comment by kunwar31** [comment]
will split the CI to use POCL for anything HALF related

**Comment by kunwar31** [comment]
Closing - same functinality as https://github.com/tinygrad/tinygrad/pull/2046

**Pull request closed without merging**
