### PR TITLE
diverse test value in test_dtype DATA based on dtype

### PR DESCRIPTION
**Pull request by chenyuxyz**
added negative int for int case

TODO: test this on real GPU. test passed on tinybox

### CODE REVIEW

**Comment by Qazalin** [comment]
I think there might be some edgecases i didnt cover in the instruction implementations, thanks for catching these I'll fix them

**Comment by chenyuxyz** [comment]
some of these might be undefined behavior (there are some skipped tests, i tested before https://github.com/chenyuxyz/tinygrad/pull/159). Feel free to skip the ones that you are sure it's undefined

**Comment by Qazalin** [comment]
@chenyuxyz fyi shipped int16 sign extension fixes for remu - should be good now. thanks again for helping catch this.

**Comment by chenyuxyz** [comment]
added annotation for PTX. it looks like PTX does not support int8, uint8 buffer and we are using int16 and uint16 to represent it now, which failed in cast.

**Pull request merged**
