### PR TITLE
increase jit batch size progressively

### PR DESCRIPTION
**Pull request by nimlgen**
Saves some enqueue time for big jit caches

llama 7b gpu6
```
enqueue in  39.35 ms
total  60.86 ms, 16.43 tok/sec
```
vs
```
enqueue in  52.92 ms
total  65.90 ms, 15.17 tok/sec
```

resnet beam=4
```
30  339.68 ms run,   36.58 ms python,  26.77 ms fetch data,  276.33 ms HSA * 6,  7.03 loss, 0.00 acc, 0.007821 LR, 94.53 GB used,  45560.44 GFLOPS
```
vs
```
30  369.88 ms run,   57.52 ms python,  24.03 ms fetch data,  288.33 ms HSA * 6,  7.03 loss, 0.00 acc, 0.007821 LR, 94.53 GB used,  41840.78 GFLOPS
```

### CODE REVIEW

**Comment by chenyuxyz** [comment]
This is great! Is there a upper limit how big a single batch can be?

**Comment by chenyuxyz** [comment]
llama 70B 4.66 tok/s!

**Comment by nimlgen** [comment]
I decided not to set an upper limit. I tested it (4096), and it really doesn't change anything. We could add one if something goes wrong

**Comment by chenyuxyz** [comment]
FYI this one might cause resnet training to hang on the second epoch. It might not be this one and I need to do more test, but 3 runs I included this hung, and the one that is on previous commit has trained more than 5 epochs as of now

**Pull request merged**
