### PR TITLE
reduce scheduler process replay overhead [pr]

### PR DESCRIPTION
**Pull request by Qazalin**
[baseline](https://github.com/tinygrad/tinygrad/actions/runs/11277079847/job/31362393426#step:11): 860 ms
[master](https://github.com/tinygrad/tinygrad/actions/runs/11277278851/job/31363062866#step:11): 2280 ms
[this branch](https://github.com/tinygrad/tinygrad/actions/runs/11277622878/job/31364205640#step:11): ~860 ms

blocker: [flaky with multiprocessing](https://github.com/tinygrad/tinygrad/actions/runs/11277622878/job/31364205640#step:12:24)

### CODE REVIEW

**Comment by geohot** [comment]
Why is this needed now? I think it's a bad idea

**Comment by geohot** [comment]
How can this be fixed, not hacked around?

**Comment by Qazalin** [comment]
same wins possible with the atexit commit in process replay
https://github.com/tinygrad/tinygrad/actions/runs/11278469163/job/31366984852#step:11:22
I think this is better, it's isolated.

Once we have big graph we can rip it out, it only happens to unjitted.
image

**Comment by geohot** [comment]
Meh, okay, rip it out with big graph

**Pull request merged**
