### PR TITLE
Negative variables in Symbolic

### PR DESCRIPTION
**Pull request by ronak69**
Read Issue #1316

* Implement floor div and mod which "rounds towards -infinity."
* Pass the negative tests which were failing.
* Negative min/max are now allowed.
* Add more tests.
* Factor out a function for performing common assertions/optimizations.

Welcome back negatives!

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/shape/symbolic.py                43              29
------------------------------------------------------------
lines added in the tinygrad folder: 14
```

**Comment by geohot** [comment]
I support this direction, but tests are failing.

**Comment by ronak69** [comment]
As i said in the Issue #1316, i think the reason is mismatched floor division implementations.

Tests for Clang *ubuntu* fails but for *windows* it doesn't, so it must be some architecture related bug right?

llvm's [sdiv](https://llvm.org/docs/LangRef.html#sdiv-instruction) instruction rounds towards zero. So the llvm codegen needs to replace all div operations with a custom routine that rounds towards -infinity.

But i don't understand codegen yet... but i will try.

**Comment by geohot** [comment]
I don't understand what this gains. There's now backend specific code too? I'm fine with generally improving symbolic to support negatives, but this is a lot of code and I don't see the benefit.

**Comment by ronak69** [comment]
The issue is that currently symbolic has a "hybrid" implementation of div/mod that either rounds towards zero or -infinity.

The solution is to select one or the other. This PR selected -infinity. But now i believe that it was a wrong choice as all of the hardware in the world rounds towards zero. This is why the tests failed: backends were rounding towards zero but symbolic was expecting them to round towards -infinity. Thus, for the tests to pass i had to make backends round towards -infinity. This turned out to be more complex and costly than i expected.

I am now working on making symbolic confirm to rounding toward zero instead. So no more backend specific code there.

This PR is a solution but not a merge-able one.

**Comment by ronak69** [comment]
I was wrong. Symbolic doesn't need to select one kind of div/mod because there is a way to make lhs be always positive (getting rid of differences in two kinds of div/mod) which is already implemented.

**Pull request closed without merging**
