### PR TITLE
remove uopgraph dedup + slight speedup

### PR DESCRIPTION
**Pull request by DKormann**

### CODE REVIEW

**Comment by DKormann** [comment]
the new graph_rewrite looks a lot like my recursive PR #5093 and at the same time only minimal changes to the current graph_rewrite

**Comment by roelofvandijk** [comment]
```
def __inner_rewrite(n: UOp) -> UOp:
  if n not in replace:
    key = (n.op, n.dtype, tuple(__inner_rewrite(s) for s in n.src), n.arg)
    new_n = UOp(*key)
    replace[n] = nodes.setdefault(key, pm.rewrite(new_n) or new_n)
  return replace[n]
```

**Comment by DKormann** [comment]
dont think it works here

**Comment by geohot** [comment]
Nice!

**Pull request merged**
