### PR TITLE
ELF loader improvements and tests

### PR DESCRIPTION
**Pull request by uuuvn**

### CODE REVIEW

**Comment by wozeparrot** [comment]
don't feel like `extra/datasets` is a good place to put the test files, somewhere under `test/` would be better

**Comment by uuuvn** [comment]
> don't feel like `extra/datasets` is a good place to put the test files, somewhere under `test/` would be better

Yeah, every other place seems worse though. Created test/blobs and moved it there

**Comment by uuuvn** [comment]
Maybe move extra/datasets/sops.gz there too?

**Comment by geohot** [comment]
Is this the highest quality you can make this code? Before I point anything out, please try to preempt any feedback and fix things. This is how you become a better software engineer.

**Comment by geohot** [comment]
How about this, the current `_elf_parse_names` contains a bug that `_strtab` fixes.

Can you submit a minimal PR that fixes that bug and contains a regression test for it? (aka it would currently fail)

**Comment by geohot** [comment]
Closing for #6011

**Pull request closed without merging**
