### PR TITLE
reduce "same but neq" cases [pr]

### PR DESCRIPTION
**Pull request by thelonejordan**
earlier, when projecting vm2's mask onto vm1, we were completely ignoring strides where len(term) > 1. This PR changes that and slightly more views are able to get merged.

towards #7237

some examples:

381356973-7862bb1f-6712-48c9-bfa0-464cc98a287d
381356918-94cb73ea-2162-41c4-9291-dcde4c7b8607

fuzzer improvements:

```PYTHONPATH=. CNT=1000 SEED=42 CHECK_NEQ=1 python3 test/external/fuzz_shapetracker_math.py```
same but neq
master - good (60/1000 = 6.00%)
branch - good (55/1000 = 5.50%)

```PYTHONPATH=. CNT=5000 SEED=42 CHECK_NEQ=1 python3 test/external/fuzz_shapetracker_math.py```
same but neq
master - good (305/5000 = 6.10%)
branch - good (298/5000 = 5.96%)

```PYTHONPATH=. CNT=10000 SEED=42 CHECK_NEQ=1 python3 test/external/fuzz_shapetracker_math.py```
same but neq
master - good (578/10000 = 5.78%)
branch - good (559/10000 = 5.59%)

### CODE REVIEW

**Comment by thelonejordan** [comment]
PYTHONPATH=. CNT=1000 SEED=1 CHECK_NEQ=1 DEBUG=0 python3 test/external/fuzz_shapetracker_math.py
same but neq
master - good (55/1000 = 5.50%)
branch - good (52/1000 = 5.20%)

PYTHONPATH=. CNT=5000 SEED=1 CHECK_NEQ=1 DEBUG=0 python3 test/external/fuzz_shapetracker_math.py
same but neq
master - good (279/5000 = 5.58%)
branch - good (264/5000 = 5.28%)


PYTHONPATH=. CNT=10000 SEED=1 CHECK_NEQ=1 DEBUG=0 python3 test/external/fuzz_shapetracker_math.py
same but neq
master - good (571/10000 = 5.71%)
branch - good (539/10000 = 5.39%)

**Comment by thelonejordan** [comment]
Why does this indexing test fail?

**Comment by thelonejordan** [comment]
@chenyuxyz this is ready for review.

**Comment by chenyuxyz** [comment]
Maybe there some good ideas here, but the pull request is hard to review. It looks like adding bunch if else conditions to reduce the diff. Is this complete, and if not, does this completely fix a sub category of cases?

For pr itself, minimize the diff and document properly with unit tests before asking for review.

**Comment by thelonejordan** [comment]
earlier, when projecting vm2's mask onto vm1, we were completely ignoring strides where len(term) > 1. This PR changes that and slightly more views are able to get merged.

**Comment by thelonejordan** [comment]
Example (same but unequal) shapetracker with more than 1 canonical form. Is there a way to identify these?

```
ShapeTracker(views=(View(shape=(7, 8), strides=(7, 1), offset=-7, mask=((1, 5), (0, 7)), contiguous=False), View(shape=(58,), strides=(1,), offset=0, mask=((0, 56),), contiguous=False)))
ShapeTracker(views=(View(shape=(8, 8), strides=(7, 1), offset=-7, mask=((1, 5), (0, 7)), contiguous=False), View(shape=(58,), strides=(1,), offset=0, mask=((0, 56),), contiguous=False)))
```

**Comment by chenyuxyz** [comment]
i added some tests in `https://github.com/tinygrad/tinygrad/blob/801e199196c19f1f1adee43cff616adce45d0580/test/unit/test_view.py#L77`

if you want i can merge the tests in this pr with `unittest.expectedFailure` for TODOs

**Comment by thelonejordan** [comment]
> i added some tests in `https://github.com/tinygrad/tinygrad/blob/801e199196c19f1f1adee43cff616adce45d0580/test/unit/test_view.py#L77`
> 
> if you want i can merge the tests in this pr with `unittest.expectedFailure` for TODOs

sure, I will create the PR with the failing tests.

**Comment by chenyuxyz** [comment]
thanks for adding the tests. for the actual implementation i think https://github.com/tinygrad/tinygrad/issues/8305 is the way, so closing this one

**Pull request closed without merging**
