### PR TITLE
speed up graph rewrite by flattening out loops [run_process_replay]

### PR DESCRIPTION
**Pull request by DKormann**
this is faster because rewrite cache only gets created once per rewrite. speedup no added complexity

### CODE REVIEW

**Comment by geohot** [comment]
Can you run this with process replay?

**Comment by DKormann** [comment]
process replay is part of the standart unit tests right?

**Comment by roelofvandijk** [comment]
> process replay passed since its part of standart CI right?
No, you need to use `[run_process_replay]` in the last commit message.

See https://github.com/tinygrad/tinygrad/actions/runs/9688184037/job/26734247958, the `Run process replay tests` step is skipped.

**Comment by roelofvandijk** [comment]
You could get rid of the nonlocal:
```
  def graph_rewrite(self, sink, pm):
    @functools.lru_cache(None)
    def recursive_rewrite(pm: PatternMatcher, up:UOp) -> UOp:
      recurse_cnt = 0
      while (rewritten:=pm.rewrite(up)) is not None:
        assert recurse_cnt < 100, f"recursive_rewrite looped {up} <--> {rewritten}"
        up = rewritten
        recurse_cnt += 1
      up = UOp(up.op, up.dtype, tuple(recursive_rewrite(pm, x) for x in up.src), up.arg)
      return self.nodes.setdefault(up.tuple(), up)
    changed = getenv("UOPS_REWRITE", True)
    run_cnt = 0
    while changed:
      changed = sink != (rewritten := recursive_rewrite(pm, sink))
      sink = rewritten
      run_cnt += 1
      assert run_cnt < 100, "exceeded 100 rewrite loops!"
    return sink

```

**Comment by DKormann** [comment]
huh it passes process replay on every device apart from clang and llvm and i cant reproduce the llvm or clang error locally

**Comment by roelofvandijkO** [comment]
Try this:
```
  def graph_rewrite(self, sink, pm):
    @functools.lru_cache(None)
    def rewrite(pm: PatternMatcher, up:UOp) -> UOp:
      recurse_cnt = 0
      while (rewritten:=pm.rewrite(up)) is not None:
        assert recurse_cnt < 100, f"recursive_rewrite looped {up} <--> {rewritten}"
        up = rewritten
        recurse_cnt += 1
      up = UOp(up.op, up.dtype, tuple(rewrite(pm, x) for x in up.src), up.arg)
      return self.nodes.setdefault(up.tuple(), up)
    changed = getenv("UOPS_REWRITE", True)
    run_cnt = 0
    while changed:
      changed = sink != (rewritten:=rewrite(pm, sink))
      sink = rewritten
      run_cnt += 1
      assert run_cnt < 100, "exceeded 100 rewrite loops!"
    return sink
```

**Comment by roelofvandijk** [comment]
Try this:

```
 def graph_rewrite(self, sink, pm):
    @functools.lru_cache(None)
    def rewrite(pm: PatternMatcher, up:UOp) -> UOp:
      recurse_cnt = 0
      while (rewritten:=pm.rewrite(up)) is not None:
        assert recurse_cnt < 100, f"recursive_rewrite looped {up} <--> {rewritten}"
        up = rewritten
        recurse_cnt += 1
      up = UOp(up.op, up.dtype, tuple(rewrite(pm, x) for x in up.src), up.arg)
      return self.nodes.setdefault(up.tuple(), up)
    changed = getenv("UOPS_REWRITE", True)
    run_cnt = 0
    while changed:
      changed = sink != (rewritten:=rewrite(pm, sink))
      sink = rewritten
      run_cnt += 1
      assert run_cnt < 100, "exceeded 100 rewrite loops!"
    return sink
```

**Comment by roelofvandijk** [comment]
I'm not 100% sure but I think your failure was related to that ugly `nonlocal changed` which is gone now.

**Comment by DKormann** [comment]
nice! thanks

**Comment by DKormann** [comment]
closed becuase not needed any more

**Pull request closed without merging**
