### PR TITLE
remove MULACC

### PR DESCRIPTION
**Pull request by geohotstan**
from #3335 bug where `contiguous` changed the result
essentially when the original AST is 
`MUL -> CAST -> MUL -> SUM`
the MUL -> SUM gets fused to MULACC so it becomes 
`MUL -> CAST -> MULACC`
but this gets triggered again despite MUL -> SUM being already fused into MULACC
this is not intended I don't think.....
which results in 
`CAST -> MULACC`
which is wrong.

fix is just elif instead of if

previously:
```
# original ast
  0 ━┳ SUM (1,)                                                                                                                                                                      
  1  ┗━┳ MUL                                                                                                                                                                         
  2    ┣━┳ CAST (dtypes.float, False)                                                                                                                                                
  3    ┃ ┗━┳ MUL                                                                                                                                                                     
  4    ┃   ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.bool, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))                             
  5    ┃   ┗━━ LOAD MemBuffer(idx=2, dtype=dtypes.bool, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))                             
  6    ┗━━ LOAD MemBuffer(idx=3, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))        

# mulacc fusion ast                        
  0 ━┳ MULACC (1,)                                                                                                                                                                   
  1  ┣━┳ CAST (dtypes.float, False)                                                                                                                                                  
  2  ┃ ┗━━ LOAD MemBuffer(idx=1, dtype=dtypes.bool, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))                                 
  3  ┗━┳ CAST (dtypes.float, False)                                                                                                                                                  
  4    ┗━━ LOAD MemBuffer(idx=2, dtype=dtypes.bool, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))         
```

now:
```
# original ast
  0 ━┳ SUM (1,)                                                                                                                                                                      
  1  ┗━┳ MUL                                                                                                                                                                         
  2    ┣━┳ CAST (dtypes.float, False)                                                                                                                                                
  3    ┃ ┗━┳ MUL                                                                                                                                                                     
  4    ┃   ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.bool, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))                             
  5    ┃   ┗━━ LOAD MemBuffer(idx=2, dtype=dtypes.bool, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))                             
  6    ┗━━ LOAD MemBuffer(idx=3, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))    

# mulacc fusion ast                            
  0 ━┳ MULACC (1,)                                                                                                                                                                   
  1  ┣━┳ CAST (dtypes.float, False)                                                                                                                                                  
  2  ┃ ┗━┳ MUL                                                                                                                                                                       
  3  ┃   ┣━━ LOAD MemBuffer(idx=1, dtype=dtypes.bool, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))                               
  4  ┃   ┗━━ LOAD MemBuffer(idx=2, dtype=dtypes.bool, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))                               
  5  ┗━━ LOAD MemBuffer(idx=3, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(10,), strides=(1,), offset=0, mask=None, contiguous=True),)))      
```

----------------------------------
update:
darn this TC=2 stuff is a little difficult to figure out. Need some more time.

### CODE REVIEW

**Comment by geohot** [comment]
Want to just remove MULACC entirely?

**Comment by geohot** [comment]
Is this good?

**Comment by chenyuxyz** [comment]
I have seen similar errors in https://github.com/tinygrad/tinygrad/actions/runs/8053110155/job/22057773495?pr=3505.

**Comment by geohotstan** [comment]
> I have seen similar errors in https://github.com/tinygrad/tinygrad/actions/runs/8053110155/job/22057773495?pr=3505.

hmmmmm yeah very odd 🤔 

some comments about this error from my investigation:
1. when I reverted the codepath back to MULACC's, the tests magically pass despite the rendered code from `MetalRenderer` being exactly the same, this made me think it was not metal related and was some artifacts from cached MULACC
2. I disabled some cache and the problem didn't go away (maybe not the right cache?)
3. if we enable only 1 of the 4 `test_linearizer_failures` additions that is suppose to trigger metal compilation error, the rest of the test pass. It's only when we have 2 or more of the 4 additions, that's when every gets corrupted. So this actually suggests it actually might be metal?

but if it's metal, and if the rendered kernel is the same when passed into metal....
Yeah I'm kinda out of ideas.

**Comment by chenyuxyz** [comment]
Thanks!

**Pull request merged**
