### PR TITLE
Refactor amd kernel prefix

### PR DESCRIPTION
**Pull request by ignaciosica**
Changes in kernel prefix rendering
- unify `extern "C"` usage
- combine attributes into one `__attribute__(({atrs}))`

### process_replay run diff
```diff
-extern "C" __attribute__((device)) __attribute__((const)) size_t __ockl_get_local_id(unsigned int);
-extern "C" __attribute__((device)) __attribute__((const)) size_t __ockl_get_group_id(unsigned int);
-extern "C" __attribute__((device)) __attribute__((const)) size_t __ockl_get_local_size(unsigned int);
-extern "C" {
-  __attribute__((device)) __attribute__((const)) float __ocml_fmax_f32(float, float);
-  __attribute__((device)) __attribute__((pure)) float __ocml_exp2_f32(float);
-  __attribute__((device)) __attribute__((pure)) float __ocml_log2_f32(float);
-  __attribute__((device)) __attribute__((const)) float __ocml_sqrt_f32(float);
-  __attribute__((device)) float __ocml_sin_f32(float);
-  __attribute__((device)) __attribute__((const)) double __ocml_fmax_f64(double, double);
-  __attribute__((device)) __attribute__((pure)) double __ocml_exp2_f64(double);
-  __attribute__((device)) __attribute__((pure)) double __ocml_log2_f64(double);
-  __attribute__((device)) __attribute__((const)) double __ocml_sqrt_f64(double);
-  __attribute__((device)) double __ocml_sin_f64(double);
-  __attribute__((device)) __attribute__((const)) _Float16 __ocml_fmax_f16(_Float16, _Float16);
-  __attribute__((device)) __attribute__((pure)) _Float16 __ocml_exp2_f16(_Float16);
-  __attribute__((device)) __attribute__((pure)) _Float16 __ocml_log2_f16(_Float16);
-  __attribute__((device)) __attribute__((const)) _Float16 __ocml_sqrt_f16(_Float16);
-  __attribute__((device)) _Float16 __ocml_sin_f16(_Float16);
-}
+extern "C" __attribute__((device, const)) size_t __ockl_get_local_id(unsigned int);
+extern "C" __attribute__((device, const)) size_t __ockl_get_group_id(unsigned int);
+extern "C" __attribute__((device, const)) size_t __ockl_get_local_size(unsigned int);
+extern "C" __attribute__((device, const)) float __ocml_fmax_f32(float, float);
+extern "C" __attribute__((device, pure)) float __ocml_exp2_f32(float);
+extern "C" __attribute__((device, pure)) float __ocml_log2_f32(float);
+extern "C" __attribute__((device, const)) float __ocml_sqrt_f32(float);
+extern "C" __attribute__((device)) float __ocml_sin_f32(float);
+extern "C" __attribute__((device, const)) double __ocml_fmax_f64(double, double);
+extern "C" __attribute__((device, pure)) double __ocml_exp2_f64(double);
+extern "C" __attribute__((device, pure)) double __ocml_log2_f64(double);
+extern "C" __attribute__((device, const)) double __ocml_sqrt_f64(double);
+extern "C" __attribute__((device)) double __ocml_sin_f64(double);
+extern "C" __attribute__((device, const)) _Float16 __ocml_fmax_f16(_Float16, _Float16);
+extern "C" __attribute__((device, pure)) _Float16 __ocml_exp2_f16(_Float16);
+extern "C" __attribute__((device, pure)) _Float16 __ocml_log2_f16(_Float16);
+extern "C" __attribute__((device, const)) _Float16 __ocml_sqrt_f16(_Float16);
+extern "C" __attribute__((device)) _Float16 __ocml_sin_f16(_Float16);
```

### CODE REVIEW

**Comment by geohot** [comment]
Curious why "sin" isn't pure

**Comment by ignaciosica** [comment]
yes, don't really sure why max and sqrt are const either. 
Don't have local amd setup to test though

**Comment by ignaciosica** [comment]
It passes CI with all set to pure but I'm not confident enough that suffices

**Comment by ignaciosica** [comment]
https://clang.llvm.org/doxygen/____clang__hip__libdevice__declares_8h_source.html

there the attributes are set in that way
- __ocml_fmax_f32 -> const
- __ocml_exp2_f32 -> pure
- __ocml_log2_f32 -> pure
- __ocml_sqrt_f32 -> const
- __ocml_sin_f32 -> none

**Pull request merged**
