### PR TITLE
[Bounty] SOTA 7B chatbot + proper chatbot format + better sampling + tests

### PR DESCRIPTION
**Pull request by francislata**
## Overview

This is PR for using the [Intel-7B](https://huggingface.co/Intel/neural-chat-7b-v3-1) model as the SOTA 7B model as mentioned [here](https://discord.com/channels/1068976834382925865/1068976834928193609/1177733163263475843).

Here's a screenshot of loading the **Intel-7B** model in the existing `examples/llama.py`:
Screenshot 2023-11-24 at 18 44 45

The command I ran is the following:
```sh
METAL_XCODE=1 DEBUG=1 python3 examples/llama.py --gen intel --size 7B --model path/to/pytorch_model.bin.index.json
```

For now, you'll have to download the [Intel-7B weights](https://huggingface.co/Intel/neural-chat-7b-v3-1/tree/main) + `tokeniser.model` + `pytorch_model.bin.index.json` files and place them in a single folder. Once #2415 is merged later on, I'll add support for downloading the needed models.

**Note:** This is a work in progress and will address the rest of the tasks as I go.

## Tasks
- [x] Load Intel-7B model
- [ ] Add proper chatbot prompting
- [ ] Add better sampling
- [ ] Add tests
- [ ] Add model downloading depending on #2415

### CODE REVIEW

**Comment by geohot** [comment]
This is not enough for a lock. For a lock I need to see it running + proper chatbot prompting. Then for bounty show the tests confirm it's SOTA 7B

**Comment by francislata** [comment]
@geohot - added the following template for the intel-7b model. There was a recommended template from their [Huggingface page](https://huggingface.co/Intel/neural-chat-7b-v3-1#prompt-template):

```
### System:
{system}
### User:
{usr}
### Assistant:
```

Here's a very quick demo:

**Comment by francislata** [comment]
Screenshot 2023-11-25 at 00 41 58

I updated the system prompt locally and had some decent conversation with the chatbot. One thing I noticed is that at the very end, the chatbot pretty much produced a different language after I said "bye" to it.

**Comment by francislata** [comment]
@geohot - saw you taking on this bounty. Feel free to close this if that’s the case.

**Comment by geohot** [comment]
Yea ### User: isn't the right delimiter. See what I did on stream, you have to use the extended hidden tokens.

**Pull request closed without merging**
