### PR TITLE
enable whisper batch for long sequences

### PR DESCRIPTION
**Pull request by DKormann**
long batch inference works now

### CODE REVIEW

**Comment by chenyuxyz** [comment]
"whisper refactor 2" is a pr title with very little information and that makes it less likely for someone to review and merge

it's a big diff with very little test changes (not even run in CI). is this pr the minimal to make test work? mixing refactor and behavior change is hard to review and time consuming

**Comment by DKormann** [comment]
I understand what you mean. I do also think this pr is a clear win since it reduces lines while providing better functionality

**Comment by DKormann** [comment]
i rolled back some small refactors to reduce diff

**Comment by chenyuxyz** [comment]
tested locally and test passed and will merge this one. i think it would be nice to make the tests work in CI too

**Pull request merged**
