### PR TITLE
(WIP) ptx in ci

### PR DESCRIPTION
**Pull request by cloud11665**
All testing was done on a 4070, cpu tests will come after all pass on device. 

test_ops:
- 3 failed, 161 passed, 11 skipped, 1 warning in 32.7
fails on ceil, floor, broadcast_partial.

TODO:
- [x] upcasting (alignment fails)
- [X] downcasting (i2f, f2f)
- [ ] cast propagation

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/assembly.py               7               1
tinygrad/codegen/assembly_ptx.py          10               6
tinygrad/codegen/linearizer.py             8               1
tinygrad/runtime/ops_cuda.py               2               2
------------------------------------------------------------
total                                     27              10
------------------------------------------------------------
lines added in the tinygrad folder: 17
```

**Comment by cloud11665** [comment]
```
===================================================================== short test summary info =====================================================================
FAILED test/test_dtype.py::TestHalfDtype::test_half_matmul - pycuda._driver.LogicError: cuModuleLoadDataEx failed: a PTX JIT compilation failed - ptxas application ptx input, line 27; error   : Unexpected instruction ty...
FAILED test/test_dtype.py::TestHalfDtype::test_int8_matmul_upcast_half - pycuda._driver.LogicError: cuModuleLoadDataEx failed: a PTX JIT compilation failed - ptxas application ptx input, line 28; error   : Unexpected instruction ty...
FAILED test/test_dtype.py::TestFloat64Dtype::test_float64_matmul - AssertionError: 
FAILED test/test_dtype.py::TestFloat64Dtype::test_float_matmul_upcast_float64 - AssertionError: 
FAILED test/test_dtype.py::TestInt8Dtype::test_int64_matmul - pycuda._driver.LogicError: cuModuleLoadDataEx failed: a PTX JIT compilation failed - ptxas application ptx input, line 17; error   : Arguments mismatch for in...
FAILED test/test_dtype.py::TestInt8Dtype::test_int8_matmul - pycuda._driver.LogicError: cuModuleLoadDataEx failed: a PTX JIT compilation failed - ptxas application ptx input, line 17; error   : Unexpected instruction ty...
FAILED test/test_dtype.py::TestInt8Dtype::test_int8_matmul_upcast_int64 - pycuda._driver.LogicError: cuModuleLoadDataEx failed: a PTX JIT compilation failed - ptxas application ptx input, line 18; error   : Arguments mismatch for in...
FAILED test/test_gc.py::TestGC::test_gc - assert 6 == 0
FAILED test/test_gc.py::TestGC::test_gc_complex - assert 8 == 2
FAILED test/test_ops.py::TestOps::test_broadcast_partial - Exception: backward pass tensor 1 failed shape (1, 32, 1, 1)
FAILED test/test_ops.py::TestOps::test_ceil - pycuda._driver.LogicError: cuModuleLoadDataEx failed: a PTX JIT compilation failed - ptxas application ptx input, line 45; error   : Illegal rounding modifier...
FAILED test/test_ops.py::TestOps::test_depthwise_conv2d - Exception: backward pass tensor 1 failed shape (32, 1, 1, 1)
FAILED test/test_ops.py::TestOps::test_floor - pycuda._driver.LogicError: cuModuleLoadDataEx failed: a PTX JIT compilation failed - ptxas application ptx input, line 45; error   : Illegal rounding modifier...
FAILED test/test_optim.py::TestOptim::test_adam_high_lr - AssertionError: 
FAILED test/test_optim.py::TestOptim::test_adamw_high_lr - AssertionError: 
FAILED test/test_optim.py::TestOptim::test_multistep_adam_high_lr - AssertionError: 
FAILED test/test_optim.py::TestOptim::test_multistep_adamw_high_lr - AssertionError: 
FAILED test/models/test_efficientnet.py::TestEfficientNet::test_car - ValueError: ndarray is not contiguous
FAILED test/models/test_efficientnet.py::TestEfficientNet::test_chicken - ValueError: ndarray is not contiguous
FAILED test/models/test_efficientnet.py::TestViT::test_car - ValueError: ndarray is not contiguous
FAILED test/models/test_efficientnet.py::TestViT::test_chicken - ValueError: ndarray is not contiguous
FAILED test/models/test_efficientnet.py::TestResNet::test_car - ValueError: ndarray is not contiguous
FAILED test/models/test_efficientnet.py::TestResNet::test_chicken - ValueError: ndarray is not contiguous
FAILED test/models/test_onnx.py::TestOnnxModel::test_openpilot_model - AssertionError: 
FAILED test/models/test_onnx.py::TestOnnxModel::test_shufflenet - ValueError: ndarray is not contiguous
=============================================== 25 failed, 511 passed, 34 skipped, 3 warnings in 132.13s (0:02:12) ================================================
```

**Comment by geohot** [comment]
How is this coming? I removed ptx from the tinygrad/ directory, but feel free to add back when it has tests.

**Comment by pasxn** [comment]
@wozeparrot since PTX is stale now, I assume this is not required anymore!

**Pull request closed without merging**
