### PR TITLE
Simple abstractions3.py fix

### LINKED ISSUE #5342: Running `python docs/abstractions3.py` results in error
I'm just going through the onboarding docs and seemed to find that running `python docs/abstractions3.py` results in the following error:

```
The schedule contains 28 items.
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=47040000),), bufs=(<buf re
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=LoadOps.CUSTOM, src=(), arg=<function custom_random 
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=60000),), bufs=(<buf real:
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=4),), bufs=(<buf real:Fals
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.MUL, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.SUB, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=UnaryOps.CAST, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=UnaryOps.NEG, src=(L
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.MAX, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.MAX, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.DIV, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.MUL, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.SUB, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.SUB, src=(
100%|█████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:00<00:00, 190.96it/s]
  0%|                                                                                               | 0/28 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "$PATH_TO_CODE/tinygrad/docs/abstractions3.py", line 56, in <module>
    for ei in tqdm(lowered): ei.run()
                             ^^^^^^^^
  File "$PATH_TO_CODE/code/tinygrad/tinygrad/engine/realize.py", line 149, in run
    et = self.prg(bufs, var_vals if var_vals is not None else {}, wait=wait or DEBUG >= 2)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'ExecItem' object is not callable
```

### PR DESCRIPTION
**Pull request by ianpaul10**
closes #5342

Apologies if I broke any of the contribution guidelines. This is my first PR to this repo.

Was going through the onboarding docs and noticed this small bug when trying to run `python docs/abstractions3.py`.

Error output in the linked issue above. New (error free) output below.

```
The schedule contains 28 items.
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=47040000),), bufs=(<buf re
ScheduleItem(ast=(LazyOp(op=LoadOps.CUSTOM, src=(), arg=<function custom_random 
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=60000),), bufs=(<buf real:
ScheduleItem(ast=(LazyOp(op=LoadOps.COPY, src=(), arg=4),), bufs=(<buf real:Fals
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.MUL, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=UnaryOps.CAST, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=UnaryOps.NEG, src=(L
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.MAX, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.MAX, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.MUL, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.MUL, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=ReduceOps.SUM, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
ScheduleItem(ast=(LazyOp(op=BufferOps.STORE, src=(LazyOp(op=BinaryOps.ADD, src=(
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:00<00:00, 217.55it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:00<00:00, 1344.22it/s]
first weight change
 [[-0.00094206 -0.00094206 -0.00094206 ... -0.00094206 -0.00094206
  -0.00094206]
 [-0.00039936 -0.00039936 -0.00039936 ... -0.00039936 -0.00039936
  -0.00039936]
 [ 0.00046347  0.00046347  0.00046347 ...  0.00046347  0.00046347
   0.00046347]
 ...
 [ 0.00145262  0.00145262  0.00145262 ...  0.00145262  0.00145262
   0.00145262]
 [ 0.00344959  0.00344959  0.00344959 ...  0.00344959  0.00344959
   0.00344959]
 [ 0.00249569  0.00249569  0.00249569 ...  0.00249569  0.00249569
   0.00249569]]
second weight change
 [[ 1.5030019e-03  0.0000000e+00  7.3841065e-03 ...  6.9242269e-03
   9.9812150e-03  1.0891259e-02]
 [ 4.2351931e-03  3.9860420e-04  3.1151613e-03 ...  3.3482760e-03
   1.1355365e-02  1.4978208e-02]
 [ 4.0464997e-03  1.0833405e-03  2.2312403e-03 ...  1.7572641e-03
   1.0248706e-02  1.1132598e-02]
 ...
 [-4.3201149e-03 -2.3348927e-03  7.3403120e-05 ...  2.1919012e-03
   4.0287077e-03 -1.7832965e-05]
 [-4.5595020e-03  6.4106146e-04 -1.3993951e-03 ... -1.0329038e-03
  -7.5615942e-04  7.2875023e-03]
 [-1.7886743e-02 -7.6207221e-03 -1.6377151e-02 ... -2.8304070e-02
  -6.7972377e-02 -7.5396322e-02]]
```

### CODE REVIEW

**Comment by Qazalin** [comment]
cool, thanks. Can you also add abstractions3 to CI? https://github.com/tinygrad/tinygrad/blob/master/.github/workflows/test.yml#L135

**Comment by ianpaul10** [comment]
Looking into why it's failing on CI now :eyes:

**Comment by Qazalin** [comment]
huh, my guess is python version

**Comment by ianpaul10** [comment]
So it seems like in python3.8 (when the walrus operator was introduced and the version of python on the CI machine), you would need to wrap assignment expressions in parentheses (https://peps.python.org/pep-0572/).

Although it is mentioned in the PEP as not recommended. However, adding that to the abstractions3.py script seemed to fix things.

If you think that makes it a bit less readable, I see a couple options:
1. Pop the assignment out into it's own row directly above `samples:=Tensor.randint(128, high=X_train.shape[0])`
2. Revert the parentheses addition change and bump the version of python in CI (it works on my machine on python3.12)

**Comment by Qazalin** [comment]
fine with the extra (, we'll eventually bump the python version but for now wanna keep 3.8.

**Pull request merged**
