### PR TITLE
Multireduce Lowerer

### PR DESCRIPTION
**Pull request by 0xtimmy**
Codegen changes to handle a basic multireduce kernel

### CODE REVIEW

**Comment by Qazalin** [comment]
I'd merge a diff that has ASTs in test_linearizer passing verify_lazyop. That'd help make progress on Lowerer changes independently.

**Comment by geohot** [comment]
Nice! Bounty is of course yours when we get this merged. Hopefully the lowerer was helpful

**Comment by 0xtimmy** [comment]
> Nice! Bounty is of course yours when we get this merged. Hopefully the lowerer was helpful

The lowerer was super helpful, great refactor

**Comment by Qazalin** [comment]
How's this going?

**Comment by 0xtimmy** [comment]
working on grouping + adding the other multireduce tests is, I can push a checkpoint

**Comment by Qazalin** [comment]
sg, I think we can independently make some progress on the UOpGraph toposort.

**Comment by 0xtimmy** [comment]
diff should now support grouping; working on incorporating more of the linearizer tests

**Comment by Qazalin** [comment]
cool, you know we can't merge big diffs; But it's worth exploring the full scope and incrementally ship in clean, small diffs.

**Pull request closed without merging**
