### PR TITLE
run more in amd ci

### PR DESCRIPTION
**Pull request by nimlgen**
to test how slow and what we can add to ci

### CODE REVIEW

**Comment by Qazalin** [comment]
remu needs new instructions - I think I pretty much implemented all formats so should be easy to add them.

**Comment by nimlgen** [comment]
8m is also pretty slow, gpuocelot is ~3m on the same tests. I will profile remu, but maybe you @Qazalin know what might be slow in remu?

**Comment by Qazalin** [comment]
I've seen line 48: https://github.com/Qazalin/remu/blob/master/src/lib.rs be very slow for large global sizes. Tried multithreading but the overhead cost was greater.

**Comment by nimlgen** [comment]
hmm, you think mt really matters running ci? it runs a worker on each thread, so I think we should try just to optimize single threaded?

**Comment by Qazalin** [comment]
so I'd first root cause where the bottleneck is. The global dims is a guess.

**Comment by nimlgen** [comment]
I have seen `index` to be slow, I think cuz of hashmap. Can we just switch this to array of registers of fixed size?
```
pub struct VGPR {
    values: HashMap<usize, [u32; 256]>,
    pub default_lane: Option<usize>,
}
impl Index<usize> for VGPR {
    type Output = u32;
    fn index(&self, index: usize) -> &Self::Output {
        &self.values.get(&self.default_lane.unwrap()).unwrap()[index]
    }
}
```

**Comment by Qazalin** [comment]
I released this FYI - didn't see a huge perf change though

**Comment by geohot** [comment]
We still want this?

**Comment by geohot** [comment]
Closing for now

**Pull request closed without merging**
