### PR TITLE
Implement q4_0 loader for gguf llama

### PR DESCRIPTION
**Pull request by Qazalin**
Adds a gguf loader to plug into Tinygrad. The gguf file format [(spec here)](https://github.com/philpax/ggml/blob/gguf-spec/docs/gguf.md) stores everything about the LLM in a single file. I've spot checked the output with the original [llama.cpp](https://github.com/ggerganov/ggml/blob/8ca2c19a3bb8622954d858fbf6383522684eaf34/include/ggml/ggml.h#L1844) implementation and the [Rust implementation](https://github.com/huggingface/candle).

- [x] Custom loader for binary -> spec values (since gguf isn't picklable)
- [x] Loading tensors via Disktensors
- [x] Dequantization fused in GPU

Dequantizations implemented: (gguf has many more dtypes, these are used in llama)
- [x] q4_0
- [x] q6K

Perf:
- [x] load and realize weights fast (~10 seconds)
- [ ] make llama run at 10 tok/s

### CODE REVIEW

**Comment by wozeparrot** [comment]
See #1807, but basically the loader should be implemented with disktensors like the torch loader and the safetensors loader.

**Comment by Qazalin** [comment]
@wozeparrot added an initial [implementation of DiskTensors](https://github.com/tinygrad/tinygrad/pull/1892/files#diff-ce5d4e7e02fbe5f8a87efb10f9dd65903a097cbf18db6f30b720806e6e5d657cR105). Can load the buffers correctly and cast. reshapes working for all layers is WIP.

 I also added a custom loader extending `pickle.Unpickler` - Though the serialization gguf uses isn't compatible with pickle's default `load` so we need to override it for this one

**Comment by geohot** [comment]
disk tensor bug should be fixed I think

**Comment by Qazalin** [comment]
I'm pausing this to work on #2011 - Right now without bitcasting the loading is very memory intensive. We need to copy the disk tensors hundreds of times in chunks.
i did a prototype version of loading `t` once and then dequanitzing everything in the GPU and it was way more manageable _(though inaccurate)_.

**Comment by Qazalin** [comment]
been stale too long, will come back to working on it

**Pull request closed without merging**
