### PR TITLE
[run_process_replay] faster and simpler match function

### PR DESCRIPTION
**Pull request by geohot**
Similar to #4867 but improves speed.

### CODE REVIEW

**Comment by geohot** [comment]
@Qazalin Hmm, I got the checkmark, but it looks like process replay failed.

**Comment by Qazalin** [comment]
yeah because of this https://github.com/tinygrad/tinygrad/pull/4873

**Comment by roelofvandijk** [comment]
Move the `dtype` check to the back, it's statistically uncommon/

**Comment by geohot** [comment]
Didn't see a speedup moving dtype

**Pull request merged**
