### PR TITLE
Train resnet

### PR DESCRIPTION
**Pull request by mekashef**
Going to be picking up where @ojaffe left off.

[Linky to previous](https://github.com/tinygrad/tinygrad/pull/1404#issuecomment-1701744099)

#1638

### CODE REVIEW

**Comment by mekashef** [comment]
I've brought it up to the latest on master.

Current problem is that the training is very slow. My previous timing was wrong (timing is often wrong with CUDA=1), so a typical run looked something like this on a 3070. The GPU time is 8x slower than my pytorch benchmark.
441.57 ms step, 37.10 ms fetch data, 398.86 ms GPU, 4.26 GB used, 995.41 GFLOPS

Possible solutions:

Wait for winograd
Do multiGPU stuff. This shouldn't be necessary, on the bottom of [this page](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Classification/ConvNets/resnet50v1.5) the authors did 90 epochs in 14 hours with mixed precision
Improve fp16 training. The training works despite failing some tests, has a much lower memory footprint, but is very slightly slower* than full precision
Pad images to nicer shapes (e.g. 256x256)

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/helpers.py                        2               2
tinygrad/nn/__init__.py                    5               2
tinygrad/runtime/ops_disk.py               2               0
------------------------------------------------------------
total                                      9               4
------------------------------------------------------------
lines added in the tinygrad folder: 5
```

**Comment by wozeparrot** [comment]
I have worked on this a bit as well, @ojaffe tested on imagenette, but to load actual imagenet is a bit different. Now that wino is merged it should also be possible to use that.

**Comment by chaosagent** [comment]
You can use wino with WINO=1. It just compiles slower for now, the kernel performance on nvidia is quite good.

**Comment by mehdi10beauty** [comment]
> 

@wozeparrot @chaosagent I'll take a look and start on that path.

**Comment by zaristei3** [comment]
Is this still being worked on? Can I pick it up where it was left off?

**Comment by mekashef** [comment]
Yes definitely!

**Pull request closed without merging**
