### PR TITLE
[experimenting] use contiguous instead of realize in optim

### PR DESCRIPTION
**Pull request by chaosagent**
Just opening a PR to run CI lol

### CODE REVIEW

**Comment by wozeparrot** [comment]
interesting

**Comment by geohot** [comment]
Oh I'd merge this.

**Comment by chaosagent** [comment]
OK, but I wanted to write tests. But I don't know a good test API.

**Comment by geohot** [comment]
Adding tests here would be welcome. Does it fail without the contiguous?

**Comment by chaosagent** [comment]
> Does it fail without the contiguous?

I was thinking about tests to prevent kernel count, memory, etc regression

**Comment by chaosagent** [comment]
hm, causes weird numbers!

**Comment by geohot** [comment]
It's not numerics. It might be assign.

**Pull request merged**
