### PR TITLE
merge reduces in conv2d

### PR DESCRIPTION
**Pull request by learossi**
This is a fix for issue #3572. The two sequential reduces come from sequential expand operations within conv2d. When backwards is called on these tensors and the gradient is produced, these two expand operations become reduces. Specifically, the expand within repeat on line 697 of _pool is only separated from the expand in the WINO = 0 branch of conv2d by movement ops. Therefore, the two reduceops show up next to one another in the final graph. 

My solution is to add the ability to forward an expand into _pool. Specifically, _pool takes the integer argument 'new_dim' which is passed into the repeat call with the other _pool arguments. This creates the new dimension the 2nd expand inside conv2d would have created separately with only the one call to repeat.

The problem right now is that the current implementation triggers the idx.max assert in log_lazybuffer -> real_strides -> expr_idxs on my laptop. I'm unsure to what extent this is system specific. As I can tell, the current code for beautiful_mnist  and conv2d generates a shapetracker for the relevant lazybuffer which is about 10x smaller than idx.max. This means adding a new dimension of 32 to the shapetracker early increases idx.max by more than 10x. I don't think this is a bug given that I also trigger the assert on my system by simply increasing one of the image dimensions or the filter number in master by more than 10x or so; conversely, it doesn't feel like intended behavior. I think this could be fixed by adding a new tensor in the middle which inherits only the last view in the problematic shapetracker but I don't understand kernel generation well enough to know whether this breaks some sort of optimization down the line and would like some advice.

### CODE REVIEW

**Comment by geohot** [comment]
I don't understand this. Can you post the before and after graph of a conv?

**Comment by learossi** [comment]
Yeah sure. Here's the model I'm running which is small enough not to trigger the idx.max assert: 
Screenshot 2024-04-21 124711
Here's an example of the double reduces from the graph that is produced by the main branch:
original_conv_graph_single_node
An here is that same node in the branch: 
revised_conv_graph_single_node
The svgs are way too big to nicely put in here, so here a drive link where you can grab both of the full graphs: 
https://drive.google.com/drive/folders/1Lu2oTNODpXLtIZQ7moG7EE6LaMhPFvlc?usp=sharing. 

You'll notice there still are double reduces even after the fix. There are at least a few double expands in the code in different places that generate this stuff when you call backwards. This just fixes the one specific to conv2d. I tracked down a few of them at one point, but then forgot to save the file where I wrote it down, but I could probably come up with where all the other ones come from in like an hour if you wanted to know.

**Comment by xXWarMachineRoXx** [comment]
> The svgs are way too big to nicely put in here, so here a drive link where you can grab both of the full graphs:

yep, that's not an understatement. Congrats on the progress tho, It has been stale in a while. 
( _I was trying this problem out and couldn't get a hold on where to start_)

**Comment by geohot** [comment]
It should probably be done at the scheduler level like #4441, but if there's other benefits to this I'm open to exploring more.

**Pull request closed without merging**
