### PR TITLE
Support and tests for nearest mode in interpolate

### PR DESCRIPTION
**Pull request by Sir-Goose**

### CODE REVIEW

**Comment by geohot** [comment]
Does it support uint8 and match torch?

**Comment by Sir-Goose** [comment]
Matches torch but checked now and uint8 is off by a max absolute difference of 1. Will look into that.

**Comment by Sir-Goose** [comment]
> I think your code looks good, how are you getting a max absolute difference of 1?
> 
> I just added a uint8 test and it passes.
> 
> ```
> class TestOpsUint8(unittest.TestCase):
>   def test_interpolate_nearest(self):
>     out_sz = (10, 10)
>     helper_test_op([(2,3,64,64)],
>       lambda x: torch.nn.functional.interpolate((10*x).relu().type(torch.uint8), size=out_sz, mode="nearest-exact"),
>       lambda x: Tensor.interpolate((10*x).relu().cast('uint8'), size=out_sz, mode="nearest"), forward_only=True)
> ```

Was just a bug with my test. @braxtonowens Thank you for yours I've added it to the PR. At least now we have confirmed uint8 works. 

@geohot looks good to merge if you are happy.

**Comment by geohot** [comment]
uint8 linear. see discussion on #6088 and #6087

**Comment by chenyuxyz** [comment]
#6308

**Pull request closed without merging**
