### PR TITLE
some docstrings

### PR DESCRIPTION
**Pull request by wozeparrot**
all of creation and data access.

if style is good, I'll go through the rest of the functions in tensor as well.

working on a way to ignore docstrings in line count.

### CODE REVIEW

**Comment by geohot** [comment]
Line too long

**Comment by geohot** [comment]
Hmm, I should probably make the doc builder run always, and just only push on mkdocs or master

**Comment by geohot** [comment]
I think we need the line count fix before we can merge, it's +274 now.

**Comment by wozeparrot** [comment]
sound good, working on line count fix

**Comment by geohot** [comment]
I put something in for line count fix, it's not exactly perfect, but it should be fine.

**Comment by wozeparrot** [comment]
Then this should be fine to merge. Can just fix later `sz.py` when we run into weird edge cases if it does break.

**Pull request merged**
