### PR TITLE
whisper: clean up code, support all sizes, test with eval set

### PR DESCRIPTION
**Pull request by jla524**
Changes made:
- support all sizes
- test against librispeech dataset
- clean up code
  - no more torch

Results on librispeech:
```
jacky@ephphatha tinygrad % TEST=1 python3 examples/whisper.py
ram used:  0.11 GB, decoder.ln.bias                                   : 100%|█████| 167/167 [00:00<00:00, 2636.35it/s]
loaded weights in 70.28 ms, 0.11 GB loaded at 1.54 GB/s
--------------------------------------------------------------------------------------------------------------------------------
2277-149896-0000

  he was in a fevered state of mind owing to the blight his wifes action threatened to cast upon his entire future

word error rate: 0.0000
--------------------------------------------------------------------------------------------------------------------------------
2277-149896-0001

  he would have to pay her the money which she would now regularly demand or there would be trouble it did not matter what he did

word error rate: 0.0000
--------------------------------------------------------------------------------------------------------------------------------
...
```

### CODE REVIEW

**Comment by jla524** [comment]
Looks like we have a bug where the sentence keeps repeating.
```
2277-149896-0004 
<|startoftranscript|><|notimestamps|> How would the papers talk about it? How would the papers talk about it? How would the papers talk about
```

**Comment by rouseabout** [comment]
> Looks like we have a bug where the sentence keeps repeating.
> 
> ```
> 2277-149896-0004 
> <|startoftranscript|><|notimestamps|> How would the papers talk about it? How would the papers talk about it? How would the papers talk about
> ```

this happens often when you don't use the full positional encoding sequence.

the paper describes other hacks for reducing hallucinations like upping the temperature and gzipping the output tokens.

**Comment by jla524** [comment]
Added a comparison and similarity score.
```
--------------------------------------------------------------------------------------------------------------------------------
2277-149896-0000

  he was in a fevered state of mind owing to the blight his wifes action threatened to cast upon his entire future

similarity score: 1.00
--------------------------------------------------------------------------------------------------------------------------------
2277-149896-0001

- he would have to pay her the money which she would now regularly demand or there would be trouble
+ he would have to pay her the money which she would now regularly demand or there would be trouble it did not matter what he did
?                                                                                                  ++++++++++++++++++++++++++++++

similarity score: 0.87
--------------------------------------------------------------------------------------------------------------------------------
2277-149896-0002

- hurst would walk to the floor mentally arranging the chief points of his situation
?      -  ^^      ^^^
+ hurstwood walked the floor mentally arranging the chief points of his situation
?        ^      ^^

similarity score: 0.94
--------------------------------------------------------------------------------------------------------------------------------
2277-149896-0003

  he also thought of his managerial position

similarity score: 1.00
--------------------------------------------------------------------------------------------------------------------------------
2277-149896-0004

  how would the papers talk about it

similarity score: 1.00
--------------------------------------------------------------------------------------------------------------------------------
2277-149896-0005

- many little wrinkles gathered between his eyes as he contemplated this and his brown moistened
?                                                                                    -
+ many little wrinkles gathered between his eyes as he contemplated this and his brow moistened

similarity score: 0.99
```

**Comment by rouseabout** [comment]
> Added a comparison and similarity score.

I guess it works. The standard metric is [WER](https://en.wikipedia.org/wiki/Word_error_rate), or CER for character-based languages.

**Comment by geohot** [comment]
"support all sizes"?

**Comment by geohot** [comment]
Is this close? I see it's still draft.

**Comment by jla524** [comment]
> Is this close? I see it's still draft.

It's close. Just need to support fallback and increment seek properly. I'm on a business trip so I haven't had a chance to work on it.

**Comment by jla524** [comment]
Update: looks like we don't really need fallback. I need to figure out where our implementation is different.

**Comment by jla524** [comment]
Our implementation works now! We have some clean up to do, but our implementation seems to perform better on larger audio files. OpenAI's implementation is missing sentences when I transcribe 5am in Silicon Valley.

**Comment by geohot** [comment]
No progress in 5 days, closing.

**Pull request closed without merging**
