### PR TITLE
add support for padding='same' in nn.conv

### PR DESCRIPTION
**Pull request by bhavyagada**
#6901 
Implemented by referencing the [PyTorch conv source](https://pytorch.org/docs/stable/_modules/torch/nn/modules/conv.html)

### CODE REVIEW

**Comment by geohot** [comment]
Tons of lines! How can you express concisely?

**Comment by bhavyagada** [comment]
@geohot I reduced the line count by half. 

Is this fine, or do you want me to simplify the loop using list comprehension, which may reduce readability but would bring the line count down to 5?

**Comment by geohot** [comment]
Looking much better!

**Comment by bhavyagada** [comment]
Do I need to do anything else?

**Comment by geohot** [comment]
Nope, merged!

**Pull request merged**
