### PR TITLE
take merge views from corsix branch

### PR DESCRIPTION
**Pull request by geohot**
This makes Winograd twice as fast (to compile) on M3

### CODE REVIEW

**Comment by geohot** [comment]
@corsix I remember you mentioned having a better merge views, I found it

This is the fix I need for Winograd, but it seems like it breaks something else.

**Comment by geohot** [comment]
This should also be able to share a lot of code with reshape I think. The reshape thing is just a specialized version of this where the second view has to be contiguous.

**Comment by corsix** [comment]
FWIW, taking out the `tinygrad/shape/view.py` change seems to put it in a better place (said change was only there because `merge_views` was very occasionally too good in synthetic tests, and that `View.create` change was an easy way to make the competitor equally good).

**Comment by geohot** [comment]
Too good? I didn't really understand that change, is there a bug with/without it?

**Comment by corsix** [comment]
> I didn't really understand that change

There's long-standing code in `View.create` to canonicalise strides: if any dimension has size 1, then its stride can be canonicalised to 0. The change added another case of canonicalisation: if any dimension has size >1, but is masked such that only one index in the dimension is unmasked (e.g. a dimension with range from 0 through 10, but with <4 and >4 all masked off, leaving 4 as the only unmasked index), then its stride can also be set to 0, albeit with a corresponding adjustment required to the offset (e.g. continuing the example, if said dimension had stride X, we'd need to add 4*X to the offset).

> Too good?

The context was a unit test that compared the following:
* A: Start with some shape X, applied a sequence of elementary transforms to it to create Y, then applied another sequence of elementary transforms to create Z.
* B: Start with shapeof(Y), apply the 2<sup>nd</sup> sequence of elementary transforms to that, then do `merge_views` between Y and that.

The expectation was that (B) would create something complicated, then the `merge_views` would simplify it back down, ideally getting as simple as (A). In practice, it sometimes created something _simpler_ than (A), because (B) naturally canonicalised away masked-to-single-element dimensions as a consequence of removing masked elements then canonicalising then re-applying padding. In those cases, to get the results of (A) and (B) to be identical, (A) also needed to canonicalise away masked-to-single-element dimensions, which is the `view.py` change.

> is there a bug with/without it?

It slightly increased the number of cases where (A) gave identical result to (B). At least in the tests I was looking at, in all cases (A) and (B) gave _equivalent_ results, just not _identical_ results. That said, there is clearly some bug with it based on the earlier test failures in this PR.

> Is this merge_views complete?

It isn't sufficient to make the aforementioned unit test always give identical results for (A) and (B); testing showed various cases where either (A) was slightly simpler, or (B) was slightly simpler, or (A) and (B) were equally complex but decided to express the complexity in slightly different ways. Is there some weaker sense in which it is complete? Perhaps.

**Comment by geohot** [comment]
Huh, so the `test_shrink_const_then_cast` is fixed it seems by the canonicalization.

**Comment by geohot** [comment]
I have a different fix for this in #3277

**Comment by corsix** [comment]
Ah, I see you identified the bug as the handling of symbolics, as comparison operators on symbolics end up false-y if the comparison is always false, but end up true-y if the comparison is _potentially_ true. Both new calls to `any` in `view.py` are affected; one fix as you've done is `instanceof` checks (though the 2<sup>nd</sup> `any` also needs them), the other (more subtle) approach is to invert the direction of the condition and wrap it in a not (e.g. `b+1 >= e` -> `not (b+1 < e)`).

**Comment by geohot** [comment]
Ahh yea, the second any probably caused the issue with llama on master.

@chenyuxyz perhaps symbolic should assert on those comparisons?

**Comment by corsix** [comment]
FWIW, this behaviour of symbolics is why the revised `merge_views` has things like `if not (merged_term >= merged_size) and not (merged_term < 0):`, rather than the more obvious way of writing that without `not`s.

**Comment by ronak69** [comment]
@corsix @geohot

> comparison operators on symbolics end up false-y if the comparison is always false, but end up true-y if the comparison is potentially true.

Comparison operation on symbolics will return `True` only if the condition is true for all values of the symbolic between `min` and `max`. Analogously, return `False` if false for all.

The problem occurs when for some values between `min` and `max`, the condition is true and for others it is false. In this case, the comparison operation will return `LtNode` instead of a `bool`; but since you have put the condition in an if-statement, python will try to convert the `LtNode` into a `bool` by calling `LtNode.__bool__()`. But guess what, a `LtNode` will *always* get converted to `True`.

I have a more **readable** solution for this problem: explicitly checking if the comparison returned `True` or it was `LtNode` or `False`. So, you can replace pattern `if x < y` with `if (x < y) is True` and pattern `if not x < y` with `if (x < y) is False`.

see also: https://github.com/tinygrad/tinygrad/issues/2469#issuecomment-1867856487 and https://github.com/tinygrad/tinygrad/issues/1924#issuecomment-1742153891 for original.

To catch these kind of bugs, why not just put an always failing assert in `LtNode.__bool__()`?

The assertions in this patch does not fail when running `test/test_symbolic_ops.py` and `test/test_symbolic_jit.py`.

```diff
diff --git a/tinygrad/shape/view.py b/tinygrad/shape/view.py
index acdd4b9b..3bb0a2f7 100644
--- a/tinygrad/shape/view.py
+++ b/tinygrad/shape/view.py
@@ -85,6 +85,16 @@ class View:
     contiguous = offset == 0 and mask is None and strides == strides_for_shape(shape)
     # if any dimension has size >1, but is masked such that only one index in the dimension is unmasked
     # then its stride can also be set to 0, albeit with a corresponding adjustment required to the offset
+
+    if mask:
+      explicit = [(b+1 >= e) is True for b,e in mask]
+      flip = [not (b+1 < e) for b,e in mask]
+      assert explicit == flip
+
+      explicit = [(b >= e) is True for b,e in mask]
+      flip = [not (b < e) for b,e in mask]
+      assert explicit == flip
+
     if mask and any(elim := [not (b+1 < e) for b,e in mask]):
       if any(not (b < e) for b,e in mask):
         strides, offset, mask = (0,) * len(shape), 0, ((0,0),) * len(shape)
```

**Pull request merged**
