### PR TITLE
Constant Folding

### PR DESCRIPTION
**Pull request by chaosagent**
Depends on #1483 . Diff against that.

When valid.max == 0, the variable is const 0, and we can write 0 + a = a etc. Useful especially for upcasted Tensor.stack, which produces many masked out variables.

Before:
```
*** exec  0.00 GB    0.01 ms op: BinaryOps.ADD        out(float): (2, 1)                         in(2): [(2, 1)] 
UOps.DEFINE_GLOBAL  :                           []                               ('data0', dtypes.float)
UOps.DEFINE_GLOBAL  :                           []                               ('data1', dtypes.float)
UOps.DEFINE_GLOBAL  :                           []                               ('data2', dtypes.float)
   0 buffer<2, dtypes.float>                         [View(shape=(2,), strides=(1,), offset=0, mask=None, contiguous=True, shape_strides=((2, 1),))]
   1 buffer<1, dtypes.float>                         [View(shape=(2,), strides=(0,), offset=0, mask=((0, 1),), contiguous=False, shape_strides=((2, 0),))]
   2 buffer<1, dtypes.float>                         [View(shape=(2,), strides=(0,), offset=0, mask=((1, 2),), contiguous=False, shape_strides=((2, 0),))]
   2
UOps.LOOP           :                           []                               ([], 'global')
UOps.LOOP           :                           []                               ([], 'local')
UOps.LOAD           : <val1_0>                  []                               MemOp(name='data1', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<1>, invalid_value=0.0)
UOps.LOAD           : <val1_1>                  []                               MemOp(name='data1', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<0>, invalid_value=0.0)
UOps.LOAD           : <val2_0>                  []                               MemOp(name='data2', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<0>, invalid_value=0.0)
UOps.LOAD           : <val2_1>                  []                               MemOp(name='data2', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<1>, invalid_value=0.0)
UOps.ALU            : <alu0>                    [<val1_0>, <val2_0>]             BinaryOps.ADD
UOps.ALU            : <alu1>                    [<val1_1>, <val2_1>]             BinaryOps.ADD
UOps.CAST           : <alu2:float2:None>        [<alu0>, <alu1>]                 None
UOps.STORE          :                           [<alu2:float2:None>]             MemOp(name='data0', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<1>, invalid_value=0.0)
UOps.ENDLOOP        :                           []                               ([], 'global+local')

```

After:

```
*** exec  0.00 GB    0.01 ms op: BinaryOps.ADD        out(float): (2, 1)                         in(2): [(2, 1)] 
UOps.DEFINE_GLOBAL  :                           []                               ('data0', dtypes.float)
UOps.DEFINE_GLOBAL  :                           []                               ('data1', dtypes.float)
UOps.DEFINE_GLOBAL  :                           []                               ('data2', dtypes.float)
   0 buffer<2, dtypes.float>                         [View(shape=(2,), strides=(1,), offset=0, mask=None, contiguous=True, shape_strides=((2, 1),))]
   1 buffer<1, dtypes.float>                         [View(shape=(2,), strides=(0,), offset=0, mask=((0, 1),), contiguous=False, shape_strides=((2, 0),))]
   2 buffer<1, dtypes.float>                         [View(shape=(2,), strides=(0,), offset=0, mask=((1, 2),), contiguous=False, shape_strides=((2, 0),))]
   2
UOps.LOOP           :                           []                               ([], 'global')
UOps.LOOP           :                           []                               ([], 'local')
UOps.LOAD           : <val1_0>                  []                               MemOp(name='data1', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<1>, invalid_value=0.0)
UOps.LOAD           : <val1_1>                  []                               MemOp(name='data1', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<0>, invalid_value=0.0)
UOps.LOAD           : <val2_0>                  []                               MemOp(name='data2', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<0>, invalid_value=0.0)
UOps.LOAD           : <val2_1>                  []                               MemOp(name='data2', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<1>, invalid_value=0.0)
    zero fold alu op: <val1_0> <- [<val1_0>, <val2_0>] BinaryOps.ADD
    zero fold alu op: <val2_1> <- [<val1_1>, <val2_1>] BinaryOps.ADD
UOps.CAST           : <alu2:float2:None>        [<val1_0>, <val2_1>]             None
UOps.STORE          :                           [<alu2:float2:None>]             MemOp(name='data0', idx=<0>, local=False, memory_dtype=dtypes.float, valid=<1>, invalid_value=0.0)
UOps.ENDLOOP        :                           []                               ([], 'global+local')
```

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/linearizer.py            44              24
------------------------------------------------------------
lines added in the tinygrad folder: 20
```

**Comment by chaosagent** [comment]
I need some way to suppress unused variable warnings, since we can't tell if a masked out variable will be used later when we define it.

**Comment by wozeparrot** [comment]
Can we just set a compiler flag to ignore them?

**Comment by chaosagent** [comment]
Yes. We will have to do this for every other backend too, now that I think about it: 0 * x will make x an unused variable.

We could add a tree shaker at the end, but I think we should try to minimize boring compiler work in tinygrad... (also at some level this is a hack because the AST can't do all of this for us)

**Comment by geohot** [comment]
So before this, valid=0 should be replaced in the linearizer with a Const uop. Can we merge that first?

**Comment by chaosagent** [comment]
superseded by #1748

**Pull request closed without merging**
