### PR TITLE
voice changer model added

### PR DESCRIPTION
**Pull request by jbalthis**
WIP

so-vits-svc added for use in voice changing functionality

referencing: bounty a22 - voice changer model (so-vits-svc, rvc). make me sound like drake

### CODE REVIEW

**Comment by prusnak** [comment]
`.DS_Store` does not belong to git - you added it to `.gitignore`, but you still kept the file

**Comment by jbalthis** [comment]
My apologies I thought it was left out. I will correct the commit and resubmitJason BalthisSoftware Engineer / Fullstack Developerweb       https://portfolio.barelyjason.onlinegithub    https://github.com/jbalthislinkedin  https://linkedin.com/in/jasonbalthiscell       ***@***.******@***.*** Jul 25, 2023, at 4:33 AM, Pavol Rusnak ***@***.***> wrote:﻿
.DS_Store does not belong to git - you added it to .gitignore, but you still kept the file

**Comment by jbalthis** [comment]
Yes I thought it was left out. Thanks for letting me know. I will remove this pull request and resubmit with just the correct file

**Comment by jbalthis** [comment]
I definitely will make use of vits as much as possible and thanks for the advice from you all. On Jul 25, 2023, at 12:19 PM, wozeparrot ***@***.***> wrote:﻿
Can try to reuse as much as possible from the existing vits model, because so-vits is based on vits there should be a bit of an overlap

**Pull request closed without merging**
