### PR TITLE
Nicer UPat [run_process_replay]

### PR DESCRIPTION
**Pull request by uuuvn**

### CODE REVIEW

**Comment by uuuvn** [comment]
not ready to review yet, created pr to easily run process replay and also my local versions of ruff and mypy are different for some reason

**Comment by geohot** [comment]
Seems like a lot of lines, and it looks copy paste from UOp. Is it worth it?

**Comment by uuuvn** [comment]
> Seems like a lot of lines, and it looks copy paste from UOp. Is it worth it?

image

**Comment by uuuvn** [comment]
I think i'll make it under 15-20
Also it's not really UOps copy paste
In my opinion it's 120% worth it, check out that arange example

**Comment by uuuvn** [comment]
down to +17 lines, this is still WIP, a lot of code is quick and hacky still, will make it <10 before ready to review

**Comment by uuuvn** [comment]
closed in flavor of #4991

**Pull request closed without merging**
