### PR TITLE
amd in benchmarks

### PR DESCRIPTION
**Pull request by nimlgen**

### CODE REVIEW

**Comment by nimlgen** [comment]
bench results:


  | AMD | HSA
-- | -- | --
hlb_cifar10 (bs=1536, 6gpus) | 349   53.12 ms run,   20.61 ms python,   32.51 ms AMD * 6,  486.84 loss, 0.000086 LR, 8.85 GB used,  37878.00 GFLOPS,   2012.20 GOPS | 349   60.75 ms run,   23.48 ms python,   37.28 ms HSA * 6,  486.84 loss, 0.000086 LR, 8.84 GB used,  33120.89 GFLOPS,   2012.20 GOPS
Resnet (mlperf) | 23  329.38 ms run,   21.91 ms python,  65.96 ms fetch data,  241.51 ms AMD * 6,  6.93 loss, 0.00 acc, 0.146587 LR, 91.89 GB used, 115379.28 GFLOPS | 23  349.80 ms run,   26.36 ms python,  72.97 ms fetch data,  250.47 ms HSA * 6,  6.97 loss, 0.00 acc, 0.103473 LR, 91.89 GB used, 108642.18 GFLOPS
Bert | x | x
stable_diffusion | step in 416.83 ms, using 6.57 GB | step in 419.05 ms, using 6.57 GB
gpt2 | 5.15 ms | 4.94 ms
Llama 7b - 1 gpu | total  42.94 ms, 23.29 tok/s, | total  42.77 ms, 23.38 tok/s,
Llama 7b beam | total  18.09 ms, 55.27 tok/s, | total  17.75 ms, 56.35 tok/s,
Llama 7b - 4gpus | total  31.87 ms, 31.37 tok/s, | total  36.98 ms, 27.04 tok/s
Llama 7b - 6gpus | total  66.36 ms, 15.07 tok/s | total  77.85 ms, 12.85 tok/s
Llama-2 70b - 6gpus | total 202.09 ms, 4.95 tok/s | total 224.17 ms, 4.46 tok/s,
cifar, 1gpu | 62.09 ms run,    2.76 ms python,   59.33 ms AMD | 63.35 ms run,    3.57 ms python,   59.78 ms HSA
cifar, half, 1gpu | 120.23 ms run,    1.36 ms python,  118.87 ms AMD | 121.80 ms run,    1.61 ms python,  120.19 ms HSA
cifar bf16, 1gpu | x | x
cifar half, 6gpus | 349   73.45 ms run,    9.57 ms python,   63.89 ms AMD * 6,  487.75 loss, 0.000086 LR, 4.79 GB used,  27394.38 GFLOPS,   2012.20 GOPS | 349   80.33 ms run,   11.15 ms python,   69.18 ms HSA * 6,  487.75 loss, 0.000086 LR, 4.78 GB used,  25049.38 GFLOPS,   2012.20 GOPS

**Comment by chenyuxyz** [comment]
(not a blocker), the mlperf resnet is slower than my last run (314ms step https://wandb.ai/chenyuxyz/tinygrad-examples_mlperf/runs/hgfjo9s3/logs?nw=nwuserchenyuxyz)

**Comment by nimlgen** [comment]
I have a HSA slower for some reason on tiny11 running dev_beam then dev_run than yours 314ms.

**Comment by chenyuxyz** [comment]
Oh did you run with the setup script in the same folder? IIRC it's slightly faster 

-- 
  Chen-Yu Yang
  ***@***.***

**Pull request merged**
