### PR TITLE
Perf example: low impact speedups for 20-30% gain

### PR DESCRIPTION
**Pull request by roelofvandijk**
Still in draft. Not intended to be merged, one MR per change might be wise.

Should be >20% faster. Plus another potential 10% from https://github.com/tinygrad/tinygrad/pull/1357
See timings below.

Work towards https://github.com/tinygrad/tinygrad/issues/1209.

It would be great if someone with an M1 Max could run and report the times here.

```
python3.11 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing
``` 

I hope the commits are self-explanatory, in theory all of them are independent.

I tried to focus on:
* statistical optimizations (e.g. most functions are called with 1 argument, order of if statements)
* syntax changes (e.g. avoid `math.isinf`, use `isinf`)
* caching

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/cstyle.py                22              21
tinygrad/codegen/linearizer.py            29              27
tinygrad/codegen/llvmir.py                12              12
tinygrad/codegen/optimizer.py             13              12
tinygrad/codegen/wgsl.py                   5               5
tinygrad/graph.py                          9               6
tinygrad/helpers.py                        3              40
tinygrad/jit.py                            4               3
tinygrad/lazy.py                          62              57
tinygrad/mlops.py                          5               5
tinygrad/nn/__init__.py                    7               7
tinygrad/ops.py                           22              25
tinygrad/runtime/lib.py                    4               3
tinygrad/runtime/ops_cpu.py                4               4
tinygrad/runtime/ops_gpu.py                1               1
tinygrad/runtime/ops_metal.py              3               2
tinygrad/runtime/ops_torch.py              1               1
tinygrad/shape/shapetracker.py            41              33
tinygrad/shape/symbolic.py                 9              10
tinygrad/state.py                          1               1
tinygrad/tensor.py                        52              57
------------------------------------------------------------
total                                    309             332
------------------------------------------------------------
lines added in the tinygrad folder: -23
```

**Comment by geohot** [comment]
Baseline:
```
ran model in 113.61 ms
sync in 4.01 ms
m   
ran model in 114.56 ms
sync in 3.64 ms
 a                               
ran model in 123.03 ms
sync in 3.67 ms
  
ran model in 114.79 ms
sync in 3.74 ms
2
ran model in 114.34 ms
sync in 3.87 ms
0
ran model in 115.53 ms
sync in 3.63 ms
 year
ran model in 123.73 ms
sync in 3.75 ms
 old
ran model in 117.00 ms
sync in 3.69 ms
```

This PR:
```
ran model in 113.83 ms
sync in 3.91 ms
m
ran model in 113.21 ms
sync in 3.80 ms
 a
ran model in 120.58 ms
sync in 3.90 ms
 
ran model in 113.11 ms
sync in 3.81 ms
2
ran model in 112.75 ms
sync in 3.76 ms
0
ran model in 113.73 ms
sync in 3.78 ms
 year
ran model in 122.34 ms
sync in 3.89 ms
 old
ran model in 113.78 ms
sync in 3.81 ms
```

Though I like the removal of the custom weakset and weakdict if we can do that w/o a perf hit.

**Comment by roelofvandijk** [comment]
> Baseline:
> 
> ```
> ran model in 113.61 ms
> sync in 4.01 ms
> m   
> ran model in 114.56 ms
> sync in 3.64 ms
>  a                               
> ran model in 123.03 ms
> sync in 3.67 ms
>   
> ran model in 114.79 ms
> sync in 3.74 ms
> 2
> ran model in 114.34 ms
> sync in 3.87 ms
> 0
> ran model in 115.53 ms
> sync in 3.63 ms
>  year
> ran model in 123.73 ms
> sync in 3.75 ms
>  old
> ran model in 117.00 ms
> sync in 3.69 ms
> ```
> 
> This PR:
> 
> ```
> ran model in 113.83 ms
> sync in 3.91 ms
> m
> ran model in 113.21 ms
> sync in 3.80 ms
>  a
> ran model in 120.58 ms
> sync in 3.90 ms
>  
> ran model in 113.11 ms
> sync in 3.81 ms
> 2
> ran model in 112.75 ms
> sync in 3.76 ms
> 0
> ran model in 113.73 ms
> sync in 3.78 ms
>  year
> ran model in 122.34 ms
> sync in 3.89 ms
>  old
> ran model in 113.78 ms
> sync in 3.81 ms
> ```
> 
> Though I like the removal of the custom weakset and weakdict if we can do that w/o a perf hit.

That's odd. I am seeing way larger speedups both on `examples/llama.py` and on `external_test_speed_llama.py`, May the latter is not representative any more...

**Comment by roelofvandijk** [comment]
Here are the timings on my machine, different story alltogether. `GPU`  backend.
I still think I have something here, very strange that it does not reproduce for you.


master: fastest is 493.99ms
```
using GPU backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:00<00:00, 2556.16it/s]
loaded weights in 144.96 ms, 13.48 GB loaded at 92.98 GB/s
Hello.
/home/rvd/.local/lib/python3.11/site-packages/pyopencl/cache.py:495: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  _create_built_program_from_source_cached(
ran model in 27559.44 ms
sync in 5449.00 ms
 I
ran model in 1135.00 ms
sync in 207.85 ms
'
ran model in 617.60 ms
sync in 430.01 ms
m
ran model in 536.66 ms
sync in 443.17 ms
 a
ran model in 493.99 ms
sync in 446.27 ms
 
ran model in 682.47 ms
sync in 382.19 ms
2
ran model in 538.65 ms
sync in 489.59 ms
0
ran model in 535.72 ms
sync in 424.86 ms
 year
ran model in 610.71 ms
sync in 451.99 ms
 old
ran model in 627.94 ms
sync in 516.53 ms
 male
```

branch: fastest is 372.74ms
```
using GPU backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:00<00:00, 1752.95it/s]
loaded weights in 206.56 ms, 13.48 GB loaded at 65.25 GB/s
Hello.
/home/rvd/.local/lib/python3.11/site-packages/pyopencl/cache.py:495: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  _create_built_program_from_source_cached(
ran model in 30074.61 ms
sync in 5755.84 ms
 I
ran model in 947.69 ms
sync in 201.71 ms
'
ran model in 398.10 ms
sync in 371.54 ms
m
ran model in 402.13 ms
sync in 362.37 ms
 a
ran model in 372.74 ms
sync in 381.49 ms
 
ran model in 424.87 ms
sync in 349.03 ms
2
ran model in 408.73 ms
sync in 378.08 ms
0
ran model in 404.31 ms
sync in 371.56 ms
 year
ran model in 406.98 ms
sync in 370.72 ms
 old
ran model in 407.72 ms
sync in 372.41 ms

```

**Comment by roelofvandijk** [comment]
I also still think https://github.com/tinygrad/tinygrad/pull/1357 is a good idea: it makes ShapeTrackers hashable, is an in-place refactor and yields 10% speedup.

**Comment by wozeparrot** [comment]
`external_test_speed_llama.py`:
master:
```
codegen         mean runtime:  244.02ms, runs:   516.84,  257.60,  205.48,  205.94,  207.06,  209.20,  208.11,  209.83,  210.31,  209.80
methodcache     mean runtime:  202.01ms, runs:   186.75,  250.13,  195.89,  196.23,  197.12,  198.39,  199.43,  199.30,  198.42,  198.46
profile         mean runtime:  839.32ms, runs:   925.52,  820.97,  825.25,  876.07,  812.69,  819.08,  820.60,  830.07,  832.67,  830.31
```
this pr:
```
codegen         mean runtime:  227.16ms, runs:   487.94,  237.88,  185.03,  184.12,  184.78,  186.08,  185.48,  186.84,  188.00,  245.41
methodcache     mean runtime:  174.88ms, runs:   166.63,  176.66,  175.70,  175.65,  175.70,  175.62,  175.35,  175.58,  176.02,  175.84
profile         mean runtime:  631.88ms, runs:   721.01,  614.58,  617.36,  621.40,  621.08,  623.69,  624.09,  626.12,  624.71,  624.74
```

`llama.py`:
master:
```
ran model in 673.27 ms
sync in 2.03 ms
'
ran model in 284.36 ms
sync in 4.15 ms
m
ran model in 257.47 ms
sync in 4.32 ms
 a
ran model in 256.74 ms
sync in 4.18 ms
 
ran model in 270.62 ms
sync in 4.47 ms
2
ran model in 259.05 ms
sync in 4.52 ms
0
ran model in 257.74 ms
sync in 4.49 ms
 year
ran model in 271.73 ms
sync in 4.31 ms
 old
ran model in 263.68 ms
sync in 4.25 ms
```
this pr:
```
ran model in 356.73 ms
sync in 2.17 ms
'
ran model in 235.44 ms
sync in 4.58 ms
m
ran model in 248.21 ms
sync in 4.63 ms
 a
ran model in 236.52 ms
sync in 4.70 ms
 
ran model in 237.04 ms
sync in 4.61 ms
2
ran model in 237.26 ms
sync in 4.65 ms
0
ran model in 252.51 ms
sync in 4.56 ms
 year
ran model in 238.48 ms
sync in 4.81 ms
 old
ran model in 239.86 ms
sync in 4.64 ms
```

**Comment by roelofvandijk** [comment]
Thanks. Not great, not terrible.

**Comment by geohot** [comment]
So I ripped out the LightWeak stuff. Are there speedups that also reduce line count / increase readability?

**Comment by roelofvandijk** [comment]
I'll make some MRs.

**Comment by roelofvandijk** [comment]
Added some MRs with very limited scope, should be easy to merge/reject. In general, there is some simplification and speedup possible by using (frozen) dataclasses or namedtuples. E.g. the `RawBuffer` is another prime candidate for a `dataclass`.

You have already seen the `ShapeTracker` as tuple of views, that's another simplification that is also faster.

**Pull request closed without merging**
