### PR TITLE
[WIP] amx support

### PR DESCRIPTION
**Pull request by ignaciosica**
This PR is my approach to bring AMX support to tinygrad in the least hackiest way I could. Keeping the mantra "don't trade complexity for speed" was my main priority as I knew hacking AMX support through is not a good tradeoff given tinygrad requirements. I approached the problem through two different paths. First, I tried supporting AMX as an extension of tensor cores but found too many disadvantages down the road preventing me from continuing. I would later present the main reasons why I abandoned this approach. Second I treated AMX as a hand coded op and found it much simpler and straightforward.

Sorry if you found this PR description boring or unnecessary, I was inspired to write it by a discord message by an orange who stated something like "show deep understanding of the problem". Eitherway, you can just skip to diff.

Hope it is not too hacky for tinygrads standards.

# AMX architecture

Although AMX instructions are not officially documented by Apple, there is an excellent documentation work by [corsix](https://github.com/corsix/amx/tree/main). The following is part of his work. Apple's AMX is a set of specialized instructions designed to accelerate matrix computations on Apple's Ms processors. These instructions are executed on a dedicated accelerator unit within the CPU, enabling high-performance matrix multiply-accumulate (MMA) operations. The architecture of AMX consists of a 32x32 grid of compute units, where each unit can perform 16-bit multiply-accumulate operations, or be grouped into subgrids to handle 32-bit or 64-bit operations. This flexible grid structure is fed by pools of X and Y registers, each containing up to 32 elements, allowing for efficient outer product computations. AMX supports various data types, including IEEE754 f16, f32, and f64 for floating-point operations, as well as integer operations with 8-bit or 16-bit multiplicands. The instructions also include capabilities for accumulating onto different bit-widths, enhancing their versatility for different computational tasks. Reference the following figure for better visualization.

image

# Two approaches

### AMX as an extension on tensor cores

<sub>I am not an expert on TC, I learned about them while working on this bounty, so I might understood some things wrong </sub>

My first approach was to try to support AMX as a variation of TC as in principle enables MMA in a similar manner. As mentioned above, AMX arch resembles in some way those of a tensor core. Nonetheless, it presents some radical differences that makes an adaptation really hard and tricky, if not incorrect. 

First, TC are meant for GPUs. This is not a trivial aspect. Much of how tensor cores achieve the performance they do rely on several aspects that CPU like arch can't provide, such as massive parallelism or high memory bandwidth. (tinygrad clang and llvm are single threaded)

Additionally, this approach requires a deep understanding of tinygrad’s tensor core implementation, which turned out to be a bounty in and of itself. I spent several hours on it and I can't confidently say I completely understood it. So trying to adapt it for AMX was in a way double hard.

I will continue this section pointing out the main reasons why I abandoned this path.

**LOCAL**

Tensor cores operate at a thread level. More specifically, on tinygrad they rely heavily on the use of LOCALs. As CLANG does not have locals, this necessarily meant hacking local support for CLANG by changing them with ranges for example. I didn't find this correct enough that justified the hack and probably meant lots of conditional in kernel and linearizer code. Also, it meant losing parallel speed as ranges in cpus run serially.

**Accumulating outside AMX Z register**

One of the main aspects that enables the performance on AMX is the accumulation into the Z registers. Instead of accumulating into some local memory, AMX does the accumulation directly on its registers and moving in and out the data for accumulation, however possible, is an overhead that kills speed. The fastest algorithm I came up with worked by accumulating the whole operations between the columns of M and N matrices, and once the tile was done and no further process was going to be required, copy the results back into the output matrix. (See figure 2 or the AMX kernel for better visualization)

**AMX requires contiguous buffers**

AMX enables contiguous loads into its registers via load instructions. These instructions can load up to 64 contiguous bytes in AMX v3 for M3 or 32 bytes for M1 and M2. If your sources are not contiguous, you would first need to copy your data into contiguous memory in order to load it into AMX registers. If you do this before every AMX load, the overhead makes it slower than a conventional optimized cpu matmul kernel such as the one generated by tinygrad.

**TC sample kernel**
``` c
#include <metal_stdlib>
using namespace metal;
float2 __WMMA_8_8_8_float_float(float2 m, float2 n, float2 o) {
  simdgroup_float8x8 a,b,c; a.thread_elements()[0] = m.x; a.thread_elements()[1] = m.y; b.thread_elements()[0] = n.x;
  b.thread_elements()[1] = n.y; c.thread_elements()[0] = o.x; c.thread_elements()[1] = o.y; simdgroup_multiply_accumulate(c, a, b, c);
  return float2(c.thread_elements()[0], c.thread_elements()[1]);
}
kernel void r_2_4_2_2_8_2(device float* data0, const device float* data1, const device float* data2, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
  int lidx0 = lid.x; /* 8 */
  int lidx1 = lid.y; /* 2 */
  int lidx2 = lid.z; /* 2 */
  int alu0 = (lidx1*4);
  int alu1 = (lidx2*32);
  int alu2 = ((lidx0/2)*8);
  int alu3 = ((lidx0%2)*2);
  int alu4 = (alu3+alu2+alu0+alu1);
  float2 val0 = (float2)(*((device float2*)(data1+alu2+alu1+alu3+alu0)));
  float2 val1 = (float2)(*((device float2*)(data2+alu4)));
  float2 wmma0 = __WMMA_8_8_8_float_float(float2(val0.x,val0.y), float2(val1.x,val1.y), float2(0.0,0.0));
  *((device float2*)(data0+alu4)) = wmma0;
}
```

This is a METAL kernel for a matmul between two square matrices of dimensions 8x8 floats. If you were to treat AMX as a TC, you would necessarily need to adapt the code to CPU-like execution taking into consideration the AMX restrictions mentioned earlier (accumulation in z reg, contiàuous buffers and NOLOCAL). This rendered the task hacky, complex and not worthy in my personal opinion.

### Handcoded AMX op

**New UOp MMA**

The new UOp MMA is introduced as the operations the AMX module enables did not fit under WMMA description. Warp Matrix Multiply-Accumulate (WMMA) is a specialized computational technique designed for high-efficiency matrix operations on NVIDIA GPUs, particularly utilizing Tensor Cores and as the name suggests, operates at a warp level. I don't believe it fits under MULACC either the operation the custom kernels performs falls under ATLAS level 3 C ← aAB +b C classification, in other words, gemm.

**Handling indexes**

Like in the case of TC, Kernels ops are used to handle indexes correctly for the AMX op. apply_amx function in kernel first checks amx applicability and then proceeds to apply an UNROLL optimization over both dimensions. In the future, this function will also apply padding to enable arbitrary sized matrices.

**Free transpose?**

There are many approaches to AMX free transpose. This property comes with how memory is placed and amx registers are loaded. However, there are many ways to overcome this issue. The first is to transpose the first matrix and force the buffers to be contiguous before applying the op. This would generate a separate kernel that runs before the r kernels and transposes the matrix so it becomes contiguous in memory. This kernel that is in charge of the transposition could be optimized with the amx module as well as it offers some instructions that accelerate this task (extrv). I want to validate my approach to amx support before solving this issue.

**Custom kernel**

``` c
#define AMX_SET(imm5) __asm("nop\nnop\nnop\n.word (0x201000+(%0<<5)+%1)" : : "i"(17), "i"(imm5) : "memory")
#define AMX(op, gpr, btf) __asm(".word (0x201000+(%0 << 5)+0%1-((0%1>>4)*6))" : : "i"(op), "r"((unsigned long long)(gpr)+(btf)) : "memory")
void __mma_1024_32_32_float(const float* restrict data1, const float* restrict data2, float* restrict data0) {
  AMX_SET(0); // set
  for(int ridx0=0; ridx0<1024; ridx0++){
    AMX(0, data2, 1ull<<62 | ridx0*4*1024); AMX(1, data1, 1ull<<62 | ridx0*4*1024); // ldx, ldy
    AMX(12, 0, 0ull); AMX(12, 0, 1ull<<20 | 64<<10); AMX(12, 0, 2ull<<20 | 64); AMX(12, 0, 3ull<<20 | 64<<10 | 64); // fma
  }
  for(int ridx1 = 0; ridx1<16; ridx1++){
    AMX(5, data0, 1ull<<62 | (ridx1*4ull)<<56   | ridx1*4*1024); // stz
    AMX(5, data0, 1ull<<62 | (ridx1*4ull+2)<<56 | ridx1*4*1024+16*4*1024); // stz
  }
  AMX_SET(1); // clr
}
```

This is the custom kernel designed to take advantage of the amx accelerator unit. It performs a whole dot product between two columns of the matrices whose width is amx size and height is the reduced dimension. The following image facilitates visualization of the operation taking place. All the accumulation is done in the z registers and it is only once all the computation has taken place that the data is moved to the output buffer. This differs from TC kernels where the values are computed in multiple steps, this results in the accumulation value being loaded and stored multiple times.

The load operations simultaneously load into 2 registers for both x and y and perform 4 fma32 operations, each accumulating into different z registers. The figure illustrates where the first fma operation accumulates its values. The last loop of the custom kernel is in charge of storing the values from the z registers into the output buffer.

image

### Kernels

**Before**

``` c
void r_8_8_8(float* restrict data0, const float* restrict data1, const float* restrict data2) {
  for (int ridx0 = 0; ridx0 < 8; ridx0++) {
    int alu0 = (ridx0*8);
    float val0 = data1[alu0+1];
    float val1 = data1[alu0+2];
    float val2 = data1[alu0+3];
    float val3 = data1[alu0+4];
    float val4 = data1[alu0+5];
    float val5 = data1[alu0+6];
    float val6 = data1[alu0+7];
    float val7 = data1[alu0];
    for (int ridx1 = 0; ridx1 < 8; ridx1++) {
      float val8 = data2[ridx1+8];
      float val9 = data2[ridx1+16];
      float val10 = data2[ridx1+24];
      float val11 = data2[ridx1+32];
      float val12 = data2[ridx1+40];
      float val13 = data2[ridx1+48];
      float val14 = data2[ridx1+56];
      float val15 = data2[ridx1];
      data0[alu0+ridx1] = ((val6*val14)+(val5*val13)+(val4*val12)+(val3*val11)+(val2*val10)+(val1*val9)+(val0*val8)+(val7*val15));
    }
  }
}
```

**AMX generated kernel**

``` c
#define AMX_SET(imm5) __asm("nop\nnop\nnop\n.word (0x201000+(%0<<5)+%1)" : : "i"(17), "i"(imm5) : "memory")
#define AMX(op, gpr, btf) __asm(".word (0x201000+(%0 << 5)+0%1-((0%1>>4)*6))" : : "i"(op), "r"((unsigned long long)(gpr)+(btf)) : "memory")
void __mma_1024_32_32_float(const float* restrict data1, const float* restrict data2, float* restrict data0) {
  AMX_SET(0); // set
  for(int ridx0=0; ridx0<1024; ridx0++){
    AMX(0, data2, 1ull<<62 | ridx0*4*1024); AMX(1, data1, 1ull<<62 | ridx0*4*1024); // ldx, ldy
    AMX(12, 0, 0ull); AMX(12, 0, 1ull<<20 | 64<<10); AMX(12, 0, 2ull<<20 | 64); AMX(12, 0, 3ull<<20 | 64<<10 | 64); // fma
  }
  for(int ridx1 = 0; ridx1<16; ridx1++){
    AMX(5, data0, 1ull<<62 | (ridx1*4ull)<<56   | ridx1*4*1024); // stz
    AMX(5, data0, 1ull<<62 | (ridx1*4ull+2)<<56 | ridx1*4*1024+16*4*1024); // stz
  }
  AMX_SET(1); // clr
}
void r_32_32_1024_32_32(float* restrict data0, const float* restrict data1, const float* restrict data2) {
  for (int ridx0 = 0; ridx0 < 32; ridx0++) {
    for (int ridx1 = 0; ridx1 < 32; ridx1++) {
      int alu0 = (ridx1*32);
      __mma_1024_32_32_float(&data1[(ridx0*32)], &data2[alu0], &data0[(ridx0*32768)+alu0]);
    }
  }
}
```

### Benchmarks

image

### Overview of changes
- Kernel apply_amx (checks applicability and UNROLLs)
- MMA UOp introduction
- GEP modification to support dynamic indexes. Is this okay? Was this a design choice for some specific reason?
- New AMXRenderer

### TODO
- [ ] Padding
- [ ] Arbitrary shape matrices
- [ ] Transpose with AMX (extrv)
- [ ] Specific AMX tests
- [ ] Winograd support?

### CODE REVIEW

**Comment by geohot** [comment]
Cool! There's certainly enough depth of thought here to lock the bounty. Will test and come back with more feedback.

**Comment by ignaciosica** [comment]
Thanks George for your feedback! 

Back to the drawing board

**Comment by ignaciosica** [comment]
### AMX support 2

New approach where, as suggested, accs are mapped to AMX's zreg. The fixed loops are no longer needed and indexing for buffers was greatly improved. The whole AMX support works similarly to how TensorCores are supported. AMX renderer was removed and GEP modification for dynamic indexing was reverted as no longer necessary.

DEFINE_ACC and PHI nodes no longer render if it is amx_acc as accumulation is done implicitly on AMX registers.

For achieving torch speed, a clean way of avoiding generating a struct when memory is contiguous is needed but is a minor change. 

It now works for double and float, half and other int types are pending support. Also, arbitrary shapes are supported as long as the dimensions are divisible by AMX dim size. 

### TODO

[ ] Padding 
[ ] Avoid unnecessary struct for contiguous loading (speed)
[ ] Half and other int types support
[ ] AMX tests

### New AMX Kernel

``` c
typedef struct { float x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31; } float32;
float32 make_float32(float x0, float x1, float x2, float x3, float x4, float x5, float x6, float x7, float x8, float x9, float x10, float x11, float x12, float x13, float x14, float x15, float x16, float x17, float x18, float x19, float x20, float x21, float x22, float x23, float x24, float x25, float x26, float x27, float x28, float x29, float x30, float x31) { return (float32) {x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31}; }
#define AMX_SET(imm5) __asm("nop\nnop\nnop\n.word (0x201000+(%0<<5)+%1)" : : "i"(17), "i"(imm5) : "memory")
#define AMX(op, gpr, btf) __asm(".word (0x201000+(%0 << 5)+0%1-((0%1>>4)*6))" : : "i"(op), "r"((unsigned long long)(gpr)+(btf)) : "memory")
void __ST_float32(float* restrict data0, int zreg){ AMX(5, data0, 1ull<<62 | (zreg*1ull)<<56); }
void __MMA_32_32_float32(float32 data1, float32 data2){
AMX(0, (int *) (&data2), 1ull<<62); AMX(1, (int *) (&data1), 1ull<<62);
AMX(12, 0, 0ull); AMX(12, 0, 1ull<<20 | 64<<10); AMX(12, 0, 2ull<<20 | 64); AMX(12, 0, 3ull<<20 | 64<<10 | 64);
}
void r_32_32_1024_32_32(float* restrict data0, const float* restrict data1, const float* restrict data2) {
  AMX_SET(0);
  for (int ridx0 = 0; ridx0 < 32; ridx0++) {
    int alu0 = (ridx0*32768);
    for (int ridx1 = 0; ridx1 < 32; ridx1++) {
      int alu1 = (ridx1*32);
      int alu2 = (alu0+alu1);
      AMX_SET(1); AMX_SET(0);
      for (int ridx2 = 0; ridx2 < 1024; ridx2++) {
        int alu3 = (alu0+ridx2);
        float val0 = data1[alu3+1024];
        float val1 = data1[alu3+2048];
        float val2 = data1[alu3+3072];
        float val3 = data1[alu3+4096];
        float val4 = data1[alu3+5120];
        float val5 = data1[alu3+6144];
        float val6 = data1[alu3+7168];
        float val7 = data1[alu3+8192];
        float val8 = data1[alu3+9216];
        float val9 = data1[alu3+10240];
        float val10 = data1[alu3+11264];
        float val11 = data1[alu3+12288];
        float val12 = data1[alu3+13312];
        float val13 = data1[alu3+14336];
        float val14 = data1[alu3+15360];
        float val15 = data1[alu3+16384];
        float val16 = data1[alu3+17408];
        float val17 = data1[alu3+18432];
        float val18 = data1[alu3+19456];
        float val19 = data1[alu3+20480];
        float val20 = data1[alu3+21504];
        float val21 = data1[alu3+22528];
        float val22 = data1[alu3+23552];
        float val23 = data1[alu3+24576];
        float val24 = data1[alu3+25600];
        float val25 = data1[alu3+26624];
        float val26 = data1[alu3+27648];
        float val27 = data1[alu3+28672];
        float val28 = data1[alu3+29696];
        float val29 = data1[alu3+30720];
        float val30 = data1[alu3+31744];
        float val31 = data1[alu3];
        float32 val32 = (float32)(*((float32*)(data2+alu1+(ridx2*1024))));
        __MMA_32_32_float32(make_float32(val31,val0,val1,val2,val3,val4,val5,val6,val7,val8,val9,val10,val11,val12,val13,val14,val15,val16,val17,val18,val19,val20,val21,val22,val23,val24,val25,val26,val27,val28,val29,val30), val32);
      }
      __ST_float32(&data0[alu2+1024], 4);
      __ST_float32(&data0[alu2+2048], 8);
      __ST_float32(&data0[alu2+3072], 12);
      __ST_float32(&data0[alu2+4096], 16);
      __ST_float32(&data0[alu2+5120], 20);
      __ST_float32(&data0[alu2+6144], 24);
      __ST_float32(&data0[alu2+7168], 28);
      __ST_float32(&data0[alu2+8192], 32);
      __ST_float32(&data0[alu2+9216], 36);
      __ST_float32(&data0[alu2+10240], 40);
      __ST_float32(&data0[alu2+11264], 44);
      __ST_float32(&data0[alu2+12288], 48);
      __ST_float32(&data0[alu2+13312], 52);
      __ST_float32(&data0[alu2+14336], 56);
      __ST_float32(&data0[alu2+15360], 60);
      __ST_float32(&data0[alu2+16384], 2);
      __ST_float32(&data0[alu2+17408], 6);
      __ST_float32(&data0[alu2+18432], 10);
      __ST_float32(&data0[alu2+19456], 14);
      __ST_float32(&data0[alu2+20480], 18);
      __ST_float32(&data0[alu2+21504], 22);
      __ST_float32(&data0[alu2+22528], 26);
      __ST_float32(&data0[alu2+23552], 30);
      __ST_float32(&data0[alu2+24576], 34);
      __ST_float32(&data0[alu2+25600], 38);
      __ST_float32(&data0[alu2+26624], 42);
      __ST_float32(&data0[alu2+27648], 46);
      __ST_float32(&data0[alu2+28672], 50);
      __ST_float32(&data0[alu2+29696], 54);
      __ST_float32(&data0[alu2+30720], 58);
      __ST_float32(&data0[alu2+31744], 62);
      __ST_float32(&data0[alu2], 0);
    }
  }
  AMX_SET(1);
}
```

**Comment by geohot** [comment]
AMX should be an OptOps like tensor cores. And I don't love the DEFINE_ACC hack, maybe there's still a better way?

But much closer than last time! Can you add some tests for this? Does this fuse with a relu okay?

**Comment by ignaciosica** [comment]
Sorry I couldn't do much this week, I've been busy with school and work. I got it working without acc hack, now, instead of storing z_reg directly into output buff it stores to accs. This also kind of fixes the problem with relu or any other op that was fused into the kernel as it was skipping accs with the hack and storing directly to output buf (Thanks for pointing that out! I somehow overlooked it). I also make it an OptOps.

It kind of fixes the problem because a there is still an issue with vectorization. Fusing an op in the kernel makes it skip the folding that vectorizes phi (this phi vectorization is essential as amx only has full register store). I think this could be resolved with a new pattern though.

Specific tests and ops_python support is still pending. 

Sorry if it is taking too long, I don't have much time to fully dedicate to finishing it but I would love to keep it locked if possible, I estimate that with 2 more weeks I can cleanly round it up. 

**new kernel**

```c
typedef struct { float x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31; } float32;
float32 make_float32(float x0, float x1, float x2, float x3, float x4, float x5, float x6, float x7, float x8, float x9, float x10, float x11, float x12, float x13, float x14, float x15, float x16, float x17, float x18, float x19, float x20, float x21, float x22, float x23, float x24, float x25, float x26, float x27, float x28, float x29, float x30, float x31) { return (float32) {x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31}; }
#define AMX_SET(imm5) __asm("nop\nnop\nnop\n.word (0x201000+(%0<<5)+%1)" : : "i"(17), "i"(imm5) : "memory")
#define AMX(op, gpr, btf) __asm(".word (0x201000+(%0 << 5)+0%1-((0%1>>4)*6))" : : "i"(op), "r"((unsigned long long)(gpr)+(btf)) : "memory")
void __ST_float32(float32* acc, int zreg){ AMX(5, acc, 1ull<<62 | (zreg*1ull)<<56); }
void __MMA_32_32_float32(float32 data1, float32 data2){
  AMX(0, (int *) (&data2), 1ull<<62); AMX(1, (int *) (&data1), 1ull<<62);
  AMX(12, 0, 0ull); AMX(12, 0, 1ull<<20 | 64<<10); AMX(12, 0, 2ull<<20 | 64); AMX(12, 0, 3ull<<20 | 64<<10 | 64);
}

void r_32_32_1024_32_32(float* restrict data0, const float* restrict data1, const float* restrict data2) {
  AMX_SET(0);
  for (int ridx0 = 0; ridx0 < 32; ridx0++) {
    int alu0 = (ridx0*32768);
    for (int ridx1 = 0; ridx1 < 32; ridx1++) {
      int alu1 = (ridx1*32);
      int alu2 = (alu0+alu1);
      AMX_SET(1); AMX_SET(0);
      float32 amx_acc0 = make_float32(0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f);
      float32 amx_acc1 = make_float32(0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f);
      [...]
      float32 amx_acc31 = make_float32(0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f,0.0f);
      for (int ridx2 = 0; ridx2 < 1024; ridx2++) {
        int alu3 = (alu0+ridx2);
        float val0 = data1[alu3+1024];
        float val1 = data1[alu3+2048];
        [...] 
        float val30 = data1[alu3+31744];
        float val31 = data1[alu3];
        float32 val32 = *((float32*)(data2+alu1+(ridx2*1024)));
        __MMA_32_32_float32(make_float32(val31,val0,val1,val2,val3,val4,val5,val6,val7,val8,val9,val10,val11,val12,val13,val14,val15,val16,val17,val18,val19,val20,val21,val22,val23,val24,val25,val26,val27,val28,val29,val30), val32); // mma0
        __ST_float32(&amx_acc0, 0);
        __ST_float32(&amx_acc1, 4);
        [...]
        __ST_float32(&amx_acc31, 62);
      }
      *((float32*)(data0+alu2+1024)) = amx_acc1;
      [...] 
      *((float32*)(data0+alu2+31744)) = amx_acc31;
      *((float32*)(data0+alu2)) = amx_acc0;
    }
  }
  AMX_SET(1);
}
```

**Comment by geohot** [comment]
Check it out with the lowerer. It should be a lot simpler :)

**Comment by ignaciosica** [comment]
Closed in favor of #5693

**Pull request closed without merging**
