### PR TITLE
Improve Symbolic fuzz tests

### PR DESCRIPTION
**Pull request by ronak69**
* remove hard-coded rng seed
* start expressions with a variable instead of zero
* generate "real" expressions for better debugging in failures
* huge performance improvement in random sample generation

### CODE REVIEW

**Comment by chenyuxyz** [comment]
the random seed was hand coded for CI consistency, and sampling was done that way so for smaller space it's guaranteed to test all combinations. The original fuzz #1278 tests all combinations with small ranges and I am not sure sacrificing that is good

**Comment by ronak69** [comment]
Fixed. Now all combinations will be tested for smaller spaces. And for bigger spaces it randomly generates value of each variable individually (faster).

Seed is now set conditionally. But don't you think "consistent" tests should be handled by `unit/test_symbolic.py` and fuzz tests should be allowed to test "random" inputs?

**Comment by ronak69** [comment]
Note: used a prime number (closest to 100 is 101) of space/sample size because this guarantees cases where space size is exactly 100 not being considered as a bigger space.

**Comment by chenyuxyz** [comment]
will let @geohot decide if this overall is an improvement. I don't see it and I think it makes tests harder to understand. Why `render_real_expr`?

the pr also changed the testing subjects, now it only tests expressions that start with "v1" and not testing expressions that start with a number

**Comment by ronak69** [comment]
`render_real_expr` because if a test fails you get to see the difference between the rendered expression by symbolic and the "real" expression. For example, `"x*1 + 0"` is a real expression and `"x"` is symbolic's render of it.

And starting with a zero is essentially one wasted op. `0+1`, `0%3`, `0+v2` etc.

**Comment by ronak69** [comment]
On CI consistency:

* use random seed everywhere
* on failure print the seed that was used
* go back in history testing with the "failure-causing" seed to find the commit that introduced the bug

Will this work?

**Comment by geohot** [comment]
Closing, agree with @chenyuxyz

**Pull request closed without merging**
