### PR TITLE
perf: floordiv fast path first, only last SumNode can be NumNode

### PR DESCRIPTION
**Pull request by roelofvandijk**
* restore fast path for SumNode.__floordiv__
* Only last nodes in SumNodes can be NumNodes (this should be more explicit)

@chenyuxyz - feel free to incorporate this in a follow-up MR if so desired.

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/shape/symbolic.py                 5               6
------------------------------------------------------------
lines added in the tinygrad folder: -1
```

**Comment by chenyuxyz** [comment]
I see interesting. Is `flat_components` O(N^2) of length of flat components? It looks like each `+=` in `flat_components` call `__add__`, which calls `__sum__`. Probably can simplify by expanding all the components first then do the sum?

**Comment by geohot** [comment]
Needs tests that use to pass, now fail, and will pass again.

**Comment by roelofvandijk** [comment]
They don't exist, this is purely for perfomance, not correctness.

I can add timings later if you'd like, e.g. starting with the div fastpath (/1=self) hits 25% of the time for the llama test.

**Comment by roelofvandijk** [comment]
> I see interesting. Is `flat_components` O(N^2) of length of flat components? It looks like each `+=` in `flat_components` call `__add__`, which calls `__sum__`. Probably can simplify by expanding all the components first then do the sum?
> 
> oh never mind I misunderstood, it's `+=` for a list. Then why is it guaranteed only the last one will be a `NumNode`? Is it because we won't have a `SumNode` with a `SumNode` component?

Because the SumNode creation appends the NumNode last. It's a bit (too) implicit.

**Comment by geohot** [comment]
Actually read what this is, I don't trust relying on this behavior! SumNode today might put the NumNode in the last element, but what if it changes! A small amount of speed is never worth a potential bug.

**Pull request closed without merging**
