### PR TITLE
special tol when f16 and bf16 are tc input dtypes

### PR DESCRIPTION
**Pull request by ignaciosica**
fixes flaky 
image

### CODE REVIEW

**Comment by geohot** [comment]
Can you fix it so the test actually makes CI fail?

**Comment by ignaciosica** [comment]
Sure, I'll look into it, it don't know why it didn't failed in CI, I remember that specific test failing to me on GitHub CI, not in benchmark though.

**Comment by chenyuxyz** [comment]
still want this? is CI flaky (seems fine to me)? is it flaky locally?

**Comment by ignaciosica** [comment]
> is it flaky locally?

yes

image

**Comment by ignaciosica** [comment]
I believe the run failed on benchmark rather than on GitHub ci, I couldn't find George's run though

**Comment by chenyuxyz** [comment]
seems fine to me. after tensor refactor and cleanups are done i am interested to better understand these errors. like float16 and bfloat16 are larger, but how much. also important as we will have float8

**Pull request merged**
