### PR TITLE
Overwrite render_cast method to HIPLanguage for manual float to hip_b…

### PR DESCRIPTION
**Pull request by Zaffer**
Please confirm if I am on the right track with this approach?
Then will add the reversion test for this.

### CODE REVIEW

**Comment by geohot** [comment]
No test

**Comment by Zaffer** [comment]
Added test to benchmark.yml as per command in issue #3536

**Comment by geohot** [comment]
Not a benchmark test, a unit test that runs in CI. The problem with benchmark tests is they don't run on contributors

**Comment by Zaffer** [comment]
All working now. Fix is to use built in functions from the hip library.

Had to remove some of the custom functions to avoid reintroduction errors for new driver library here:
https://github.com/ROCm/clr/blob/rocm-6.0.x/hipamd/include/hip/amd_detail/amd_hip_bf16.h

I added a test to test.yml CI that reproduced the exact issue here, but commented it out because it runs on self-hosted tinybox.

**Comment by chenyuxyz** [comment]
can you make minimal change and include a minimal test that runs on CI?

**Comment by Zaffer** [comment]
> can you make minimal change and include a minimal test that runs on CI?

added a minimal test and added explicit test in CI
this is already the most minimal change possible in cstyle.py

summary:
- had to add a render_cast function override in the HIPLangauge class to handle float to bfloat16 type casting in HIP
- to use the built-in HIP conversion function called "__float2bfloat16", so I had to add this to the kernel prefix:
```c
#include <stdint.h>
#include <stddef.h>
#include <hip/amd_detail/amd_hip_bf16.h>
```
> more detail here: https://github.com/ROCm/clr/blob/rocm-6.0.x/hipamd/include/hip/amd_detail/amd_hip_bf16.h
- to add these libraries to the kernel and I had to remove the following custom `make_` functions:
```python
_make_hip_dtype(*x) for x in [("signed int", "int", 2), ("signed int", "int", 4), ("float", "float", 2), ("float", "float", 4)]
```

**Comment by Zaffer** [comment]
first test is the minimal test, simply do a type cast to bfloat16 causes the issue on AMD devices:
```python
def test_f16_to_bf16_minimal(self):
  original_tensor = Tensor([1.0, 2.0, 3.0], dtype=dtypes.float16)
  converted_tensor = original_tensor.cast(dtypes.bfloat16)
  self.assertEqual(converted_tensor.dtype, dtypes.bfloat16)
```

**Comment by chenyuxyz** [comment]
see #3630

**Pull request closed without merging**
