### PR TITLE
(re)start multireduce in codegen/*

### PR DESCRIPTION
**Pull request by Qazalin**
This is blocking progress on the scheduler.

milestones:

- [ ] reintroduce test_var_multireduce in the Lowerer, fixup_ast is transforming the ReduceOps incorrectly:

```
 14            ┣━┳ ReduceOps.SUM (3,)
 15            ┃ ┗━━ BufferOps.LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(3, 27, 32, 32), strides=(864, 32, 1, 0), offset=0, mask=None, contiguous=False),)))
 16            ┗━━ BufferOps.CONST ConstBuffer(val=0.03125, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(3, 27, 32, 1), strides=(0, 0, 0, 0), offset=0, mask=None, contiguous=False),)))
```
gets rewritten to: (NOOPT=1)
```
 14            ┣━┳ ReduceOps.SUM (1, 2)
 15            ┃ ┗━━ BufferOps.LOAD MemBuffer(idx=1, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(81, 32, 32), strides=(32, 1, 0), offset=0, mask=None, contiguous=False),)))
 16            ┗━━ BufferOps.CONST ConstBuffer(val=0.03125, dtype=dtypes.float, st=ShapeTracker(views=(View(shape=(81, 32, 1), strides=(0, 0, 0), offset=0, mask=None, contiguous=False),)))
```

- [ ] https://github.com/tinygrad/tinygrad/pull/5389. How should the arange+indexing AST look like?

### CODE REVIEW

**Comment by geohot** [comment]
Screenshot 2024-07-11 at 1 40 10 PM

This is the AST with a few scheduler tweaks (skip expands, don't chase). The two reduces need to be fused.

The full_shape of the AST should be (4, 16384, 16384, 256) with the first reduce on axis 2, and the second on axis 1.

**Comment by geohot** [comment]
I added a simpler `test_arange_2_reduce` test without the reshape issue.

**Comment by geohot** [comment]
I have a fix for test_var_multireduce

**Comment by Qazalin** [comment]
status: I'm picking up from test/test_arange.py expected failures. milestones:
- [ ] Verify AST correctness in test_linearizer.py for a fused `test_index`
- [ ] Generalize to the scheduler

**Pull request merged**
