### PR TITLE
refactor UOps Pattern Matcher

### PR DESCRIPTION
**Pull request by utkarshgill**
- [x]  add `UPat` + refactor `_match()` and `PatternMatcher`
- [x]  refactor `constant_folder` and `assembly.py`
- [x]  regression tests

### CODE REVIEW

**Comment by ignaciosica** [comment]
CI is broken. I would suggest making this a draft pr if it is not ready yet.  

Also, it seems to be a lot of changes related to formatting, I would recommend reverting those and leaving only the ones required for refactoring UOps

**Comment by utkarshgill** [comment]
> CI is broken. I would suggest making this a draft pr if it is not ready yet.

Yeah I messed up upstream merge conflicts. I think its fixed now. But some tests (ptx, nv) are failing:

```
File "/home/runner/work/tinygrad/tinygrad/tinygrad/renderer/assembly.py", line 383, in <module>
    UPat(
TypeError: UPat.__init__() got an unexpected keyword argument '__allow_len__'
```

Should I change `UPat` ?

**Comment by geohot** [comment]
Is this a functional change or a whitespace change? If no functional changes are expected, how have you verified that.

**Comment by geohot** [comment]
Still contains whitespace changes. Closed in favor of #4791

**Pull request closed without merging**
