### PR TITLE
Use local memory in kernels ($1000 bounty)

### PR DESCRIPTION
**Pull request by geohot**
Claim the bounty by implementing this and having tinygrad generate GEMM kernels for NVIDIA that are faster than torch/cuBLAS.

Clean code only, must be merged to claim bounty.

### CODE REVIEW

**Comment by sayantan3** [comment]
Forgive me if I ask rudimentary question.
During execution of -> tinygrad/accel/triton/ops_triton.py 
Error -> ImportError: cannot import name 'ExplicitExecAST' from 'tinygrad.ops'
What I am missing?

**Comment by geohot** [comment]
triton isn't supported anymore, you'd have to fix it.

**Comment by arandog** [comment]
@geohot  Can you clarify if the goal is to call cuBLAS from tinygrad (e.g. with cupy) or custom GEMM kernel generation that is faster than cuBLAS? The former seems too straightforward, while the latter seems too complex

**Comment by sayantan3** [comment]
I think he meant custom faster than cuBLAS/ pytorch.

**Pull request closed without merging**
