### PR TITLE
update openpilot supercombo.onnx to 0.9.4

### PR DESCRIPTION
**Pull request by chenyuxyz**
Should fix CI.

I am not very familiar with openpilot and onnx. Attempted to fix by checking errors and source https://github.com/commaai/openpilot/blob/57ad4f02f8e693639262aa3a982be8ed6c433ee0/selfdrive/modeld/modeld.py#L65.

### CODE REVIEW

**Comment by g1y5x3** [comment]
Oh, did they change models on their end which resulted in slight changes in model architecture and kernel counts?

**Comment by chenyuxyz** [comment]
yeah I think there are some model updates, the old model reference commit was about an year ago and v0.9.0 only has 198 kernels.

**Comment by geohotstan** [comment]
https://github.com/commaai/commavq/raw/master/models/gpt2m.onnx is also down I think.  :s
`external_model_benchmark` doesn't run on master.

**Comment by chenyuxyz** [comment]
eh you are right, thanks for the info. `commavq` does not have a release tag that we can pull the large files though. Not sure how to proceed.

Also the v0.9.4 `supercombo` had `RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'` when I tried to run `external_model_benchmark.py` locally, and after skipping that there's some numerical errors.

```
PYTHONPATH=. MODEL=openpilot python3 test/external/external_model_benchmark.py
https://github.com/commaai/openpilot/raw/v0.9.4/selfdrive/modeld/models/supercombo.onnx: 100%|███████████████████████████████████████████████████████████████████████████████████| 47.5M/47.5M [00:01<00:00, 27.1MB/s]
openpilot       tinygrad_metal_jitless     119.55 ms
openpilot       tinygrad_metal_jit           5.69 ms
openpilot       tinygrad_clang_jitless     177.86 ms
openpilot       tinygrad_clang_jit         110.62 ms
openpilot       onnx2torch doesn't support this model
openpilot       onnxruntime_cpu             41.29 ms
Traceback (most recent call last):
...
AssertionError:
Not equal to tolerance rtol=0.0008, atol=0.0008
For tensor 'outputs' in dict_keys(['outputs'])
Mismatched elements: 3 / 6120 (0.049%)
Max absolute difference: 0.05912781
Max relative difference: 0.2617
 x: array([[ 0.229035,  0.001494, -0.001691, ...,  0.      ,  0.      ,
         0.      ]], dtype=float32)
 y: array([[ 0.229   ,  0.001502, -0.001691, ...,  0.      ,  0.      ,
         0.      ]], dtype=float16)
```

**Comment by wozeparrot** [comment]
We can have the commavq change in a separate pr, cuz it'll have to target the update_benchmark branch anyways

**Comment by chenyuxyz** [comment]
@wozeparrot anything you want to change from this PR? I can comment out the openpilot and commavq from `external_model_benchmark` so that it's not breaking. Would like to get this in to have a green CI soon.

**Comment by wozeparrot** [comment]
Yea, commenting out should be fine, can bring them back in another pr, do want green ci

**Comment by chenyuxyz** [comment]
@wozeparrot done

**Pull request merged**
