### PR TITLE
shrink MLB on sharded axis

### PR DESCRIPTION
**Pull request by chenyuxyz**
use onehot structure to store the real partition. goal is unsynced batchnorm2d that can be run on multigpu for training.

draft version in https://github.com/chenyuxyz/tinygrad/pull/109

### CODE REVIEW

**Comment by geohot** [comment]
Why do you need to track externally if they are real? Can't the shapetracker in the lazybuffer do it (if it's never valid)?

**Comment by chenyuxyz** [comment]
it might be possible but it feels quite complicated. for example, shrink on sharded axis -> some movementops -> pad on sharded axis -> allreduce. if mlb shrink is tracked with each lazybuffer's shapetracker (and make all but one invalid), the pad back cannot be done directly.

i have the ops working now, will know better once the batchnorm works

**Comment by chenyuxyz** [comment]
still have many work to do, but unsynced batchnorm training works!

```
344   43.96 ms run,   34.07 ms python,    9.89 ms HIP * 6,  499.00 loss, 0.000148 LR, 10.52 GB used,  46181.37 GFLOPS,   2030.09 GOPS
345   44.54 ms run,   33.62 ms python,   10.92 ms HIP * 6,  501.50 loss, 0.000137 LR, 10.53 GB used,  45579.10 GFLOPS,   2030.09 GOPS
346   44.05 ms run,   33.78 ms python,   10.28 ms HIP * 6,  501.50 loss, 0.000124 LR, 10.54 GB used,  46084.61 GFLOPS,   2030.09 GOPS
347   44.05 ms run,   33.77 ms python,   10.28 ms HIP * 6,  499.75 loss, 0.000112 LR, 10.54 GB used,  46084.53 GFLOPS,   2030.09 GOPS
348   44.23 ms run,   33.61 ms python,   10.63 ms HIP * 6,  503.25 loss, 0.000099 LR, 10.55 GB used,  45894.79 GFLOPS,   2030.09 GOPS
349   43.90 ms run,   33.69 ms python,   10.20 ms HIP * 6,  500.50 loss, 0.000086 LR, 10.56 GB used,  46248.74 GFLOPS,   2030.09 GOPS
shuffling test dataset in 42.29 ms (epoch=0)
eval     10035/10752 93.33%,    0.43 val_loss STEP=350 (in 3600.46 ms)
LATEBEAM=2 HALF=1 GPUS=6 BS=1536 EVAL_BS=1536 STEPS=350 python3   43.56s user 14.07s system 113% cpu 50.736 total
```

**Comment by chenyuxyz** [comment]
latest number, 40ms! 50TFLOPS!
```
345   40.95 ms run,   25.91 ms python,   15.04 ms HIP * 6,  502.00 loss, 0.000137 LR, 10.53 GB used,  49564.29 GFLOPS,   2029.46 GOPS
346   40.37 ms run,   25.95 ms python,   14.42 ms HIP * 6,  502.25 loss, 0.000124 LR, 10.54 GB used,  50276.55 GFLOPS,   2029.46 GOPS
347   40.74 ms run,   25.79 ms python,   14.94 ms HIP * 6,  501.00 loss, 0.000112 LR, 10.54 GB used,  49820.33 GFLOPS,   2029.46 GOPS
348   40.54 ms run,   25.87 ms python,   14.67 ms HIP * 6,  504.75 loss, 0.000099 LR, 10.55 GB used,  50058.92 GFLOPS,   2029.46 GOPS
349   40.23 ms run,   25.79 ms python,   14.45 ms HIP * 6,  502.50 loss, 0.000086 LR, 10.56 GB used,  50443.29 GFLOPS,   2029.46 GOPS
shuffling test dataset in 42.54 ms (epoch=0)
eval     10036/10752 93.34%,    0.43 val_loss STEP=350 (in 3592.29 ms)
LATEBEAM=2 HALF=1 STEPS=350 BS=1536 GPUS=6 python3 examples/hlb_cifar10.py  41.48s user 14.76s system 113% cpu 49.439 total
```

**Comment by chenyuxyz** [comment]
i am ready to merge this one. keep the real as an attribute to MLB, and use const(0) as the output of `e` and `r` if it's not real to avoid keeping references of a buffer. i think real represents a different state in the sense that we don't know if we need to compute those `const(0)` by checking the lb alone, because the real lb can also be a legit const(0), and we use real=False to skip computing those. it's also a pure optimization because computing those unreal const(0) will have the same outcome.

test-wise, i have all ops, uneven shard, different combination of conv/bn applying on partitions.

some open questions that i am investigating separately. (1) beam still have kernels on gpu1 to gpu5, (2) memory increase during multi gpu training. this is on master too and it's not the cause for METAL with virtual multi gpu, so it might be HIP specific?

@geohot let me know if you have any concerns or suggestions

**Pull request merged**
