### PR TITLE
Trigger process replay from pull request title [run_process_replay]

### PR DESCRIPTION
**Pull request by uuuvn**

### CODE REVIEW

**Comment by Qazalin** [comment]
I see why this'd be convenient for a bounty / PR - doesn't work though

**Comment by uuuvn** [comment]
> I see why this'd be convenient for a bounty / PR - doesn't work though

yeah, fixing this right now, i don't know how github actions works like at all

**Comment by uuuvn** [comment]
not sure what bounty you're talking about - i'm just sick of writing run process replay on each commit in #4976

**Comment by Qazalin** [comment]
wrong way to test it works,
this is what i usually do: https://github.com/tinygrad/tinygrad/pull/4903/commits/12ac995c02fcdfaf1e5bfbe235d492aace91d94d

**Comment by uuuvn** [comment]
@Qazalin seems like it works, thanks

**Pull request merged**
