### PR TITLE
Fix accessing elements created by padding

### PR DESCRIPTION
**Pull request by andresgit**
This is an attempt to fix the issues #2177 and #2194 on the CPU interpreted backend. I will also try to see if I can fix it on compiled backends.

The problem is that `ShapeTracker.to_movement_ops` tries to calculate `real_offset`, the offset of the first element in the base buffer that appears in this view. But the view might not contain any such element (i.e. it is completely made up of elements created by padding). In this case it gets an offset that doesn't work.

As a fix I introduced `offset_noreal` to `View`, which is set `True` if we resize in a way that the `View.mask` doesn't contain any elements in the view. Then in `ShapeTracker.to_movement_ops` we treat this case separately by creating the required shape using padding.

I also made `View.mask` be between 0 and the new shape when resizing, because otherwise for example `Tensor([1,2]).pad(((3,0),))[0:2]` would have `View.mask=((3,2),)`, which caused problems.

### CODE REVIEW

**Comment by andresgit** [comment]
It also fixes on CPU the `ValueError` caused by this code mentioned on Discord a couple of weeks ago:
`Tensor.stack([Tensor([1, 2, 3, 4, 5]) for i in range(3)])[0, :].numpy()`

**Comment by geohot** [comment]
So this definitely doesn't belong in the view if it's only an interpreted bug

**Comment by andresgit** [comment]
From the issues I added several test cases that also fail on compiled backends.
I managed to fix the errors on the compiled backends by returning all indices as invalid in the shapetracker.py function `expr_node_mask` when there is no base buffer element in the view (i.e. `View.offset_noreal` is set).

It fixes for example this on the GPU: `assert Tensor([[1],[2]]).pad(((0,0),(1,0)))[1,0]==0`

Instead of introducing a new variable `View.offset_noreal` one alternative possibility would be to set `View.offset` to `None` and then add a check for `None` everywhere the offset is used.

**Comment by geohot** [comment]
I'm not convinced that a view change is required, feel free to reopen starting with a failing test case

**Comment by andresgit** [comment]
I agree that it is not required to add a flag to View, it is just one possible fix and it is also possible to fix the issues in other ways.
I can try to submit a PR with a different approach.

**Pull request closed without merging**
