### PR TITLE
8x .numpy() speedup

### PR DESCRIPTION
**Pull request by reddyn12**
Screenshot 2024-08-02 at 6 25 10 PM

```
import numpy as np
from tinygrad import Tensor, dtypes
import time

SHAPE = (36, 120087, 268)
tens_out = Tensor.rand(SHAPE, dtype=dtypes.float32).realize()
print(tens_out.shape, tens_out.dtype)
np_arr = np.ones(SHAPE, dtype=np.float32)
print(np_arr.shape, np_arr.dtype)

nt = time.perf_counter()
tens_out.numpy(np_arr.data)
net = time.perf_counter()

mt = time.perf_counter()
np_out = tens_out.numpy()
met = time.perf_counter()

np.testing.assert_equal(np_arr, np_out)

print(f'NEW: {net-nt} Normal: {met-mt}')
```

### CODE REVIEW

**Comment by reddyn12** [comment]
Idk how to make linter happy

**Comment by geohot** [comment]
Not changing API for this

**Comment by reddyn12** [comment]
> Not changing API for this

I split it into 2 functions

**Comment by geohot** [comment]
No, this misses the point. Why is the main API slow?

**Pull request closed without merging**
