### PR TITLE
UOps stats patch

### PR DESCRIPTION
**Pull request by ianpaul10**
ref https://github.com/tinygrad/tinygrad/pull/6405

### CODE REVIEW

**Comment by geohot** [comment]
Why do you think this is right?

**Comment by ianpaul10** [comment]
It seems right when the gate is an IF (in this PR https://github.com/tinygrad/tinygrad/pull/6405) but I guess it's now not removing enough in this case when the gates are just the isolated uops.

Should I just add the test in this PR and then have the line removed when switching over to gated stores? I may have misunderstood Qazalin's ask.

**Comment by Qazalin** [comment]
Do you need to change the flopcounter for your bounty?
Isolate the failure here and put up the diff with tests. We wanna see regression tests that fails in master.

**Comment by ianpaul10** [comment]
Ok, sorry I might've misunderstood the original ask.

I isolated the failure on master when measuring the op_estimate that came up during the BEAM search. Is this more of what you had in mind?

**Pull request closed without merging**
