### PR TITLE
Rec rewrite + find changed rewrite patterns

### PR DESCRIPTION
**Pull request by DKormann**
single pass recursive rewrite

can be very simple and replace both uopgrah.rewrite and dedup

main challenge is finding all rewrite rules that need to be changed for this to work as in #5079
thats why i log all uopgraph that dont agree with old rewrite

### CODE REVIEW

**Comment by DKormann** [comment]
new idea: search for minimal graph that doesnt get rewritten correctly

**Comment by geohot** [comment]
Cool! I'm working on something similar in #5159

Something that checks the patterns would be great. Can you explain what's wrong with them?

**Comment by geohot** [comment]
Merged your UPat printer btw.

**Comment by DKormann** [comment]
> Merged your UPat printer btw.

for me visualizing stuff like that is super necessary

**Comment by DKormann** [comment]
> Cool! I'm working on something similar in #5159
> 
> Something that checks the patterns would be great. Can you explain what's wrong with them?

simplest example is the first rule in constant folder. it expects while node with mul children. but other rule rewrites mul -1 to neg . now the first rule cant recognize that

**Comment by DKormann** [comment]
```
sink

**Comment by geohot** [comment]
Oh, but that's not an issue with the rewriter itself, it's just the different application order.

**Comment by DKormann** [comment]
yes

**Comment by DKormann** [comment]
the rules are created with top down application in mind. now we go from the leaves upwards right

**Comment by DKormann** [comment]
current problem graph:

```
 14%|████████████████████████████████████                                                                                                                                                                                                                      | 1/7 [00:00<00:03,  1.65it/s]  0 ━┳ UOps.ALU BinaryOps.ADD
  1  ┣━┳ UOps.ALU BinaryOps.ADD
  2  ┃ ┣━━ UOps.CONST 0.0
  3  ┃ ┗━━ UOps.CONST 0.0
  4  ┗━━ UOps.CONST -0.16666666666666666
UOp(op=UOps.ALU, dtype=float, src=(UOp(op=UOps.ALU, dtype=float, src=(UOp(op=UOps.CONST, dtype=float, src=(), arg=0.0), UOp(op=UOps.CONST, dtype=float, src=(), arg=0.0), ), arg=BinaryOps.ADD), UOp(op=UOps.CONST, dtype=float, src=(), arg=-0.16666666666666666), ), arg=BinaryOps.ADD)
mismatch: UOps.CONST          : dtypes.float              []                               -0.1666666716337204 != UOps.CONST          : dtypes.float              []                               -0.16666666666666666
  0 ━━ UOps.CONST -0.1666666716337204
  0 ━━ UOps.CONST -0.16666666666666666
```

**Comment by DKormann** [comment]
`  ((UOp.var('c1') + UOp.cvar('c2')) + UOp.cvar('x'), lambda x,c1,c2: x+UOp.const(x.dtype, exec_alu(BinaryOps.ADD, x.dtype, [c1.arg, c2.arg]))),
`

**Comment by DKormann** [comment]
finished in other pr

**Pull request closed without merging**
