### PR TITLE
train resnet

### PR DESCRIPTION
**Pull request by geohot**

### CODE REVIEW

**Comment by geohot** [comment]
Unlocking bounty, over 1 week has gone by without update.

**Comment by geohot** [comment]
New rule on mlperf training bounties. in order to lock the bounty, you must post weights that you trained in tinygrad that meet the accuracy requirement. Then we can look at speed and mergablity, but until there's weights, no lock.

**Comment by Polydynamical** [comment]
Is this bounty solved? If not, what issues were you running in to George?

**Comment by geohot** [comment]
Stale, #3361 is the future

**Pull request closed without merging**
