### PR TITLE
simple exporting models

### PR DESCRIPTION
**Pull request by dc-dc-dc**
Brought over the core logic of exporting models into a single file under extra

Kept the logic for clang and webgpu, only returning the logic needed for the model to run.

Added a third option to export out to a json file with everything needed to run the model enabling the ability to bring these models into any language of choice provided it can access the backened used to export (OPENCL, CUDA, etc).

As a example of the import ability I created a golang lib [tinyrnnr](https://github.com/dc-dc-dc/tinyrnnr-go) that can import this json file and run efficientnet without any tensor logic.

### CODE REVIEW

**Comment by geohot** [comment]
Why is this draft? Ready to merge?

**Comment by dc-dc-dc** [comment]
Wanted to add a swift/Metal example as well but can't get the image properly fitted. Will just skip that and rebase with master and mark ready for review

**Comment by geohot** [comment]
Sorry, can you rebase. I shouldn't have merged the editor config PR.

**Comment by wozeparrot** [comment]
They just timed out here, I'll rerun it.

**Pull request merged**
