### PR TITLE
Arm backend

### PR DESCRIPTION
**Pull request by stevenandersonz**
I got the scalar ops for ARM64 working and 6/154 ops.py tests are passing. I would like to try the bounty, but is fine if can't be locked yet.

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/assembly.py               2               0
tinygrad/codegen/assembly_arm.py          38               0
tinygrad/lazy.py                           1               1
tinygrad/runtime/ops_arm.py               36               0
------------------------------------------------------------
total                                     77               1
------------------------------------------------------------
lines added in the tinygrad folder: 76
```

**Comment by geohot** [comment]
So I intended the bounty to be an *or* between x86 and ARM, after you get one the other is simple, and the bounty is locked right now.

However, I'll make you a deal. If after x86 is merged you manage to add ARM support while *reducing* line count (no code golf), I'll pay out both bounties. Will require refactoring the two together.

Of course, if @martinloretzzz abandons the bounty (1 week of no forward progress), I'll lock it to you.

**Comment by stevenandersonz** [comment]
That's fair, thank you!

**Comment by geohot** [comment]
Been ~a week since #985 progress. Will give bounty to whichever backend passes tests first!

**Comment by martinloretzzz** [comment]
Yeah that's totally fair, I just don't have much time lately. I'm also working at a start-up and there's way to much work there recently.

Also done a lot of things for the webgpu bounty, because I built the webgpu backend more or less at a hackathon a month ago (but refactoring, cleanup and making it faster also took a lot of time).

As soon as I have more time for tinygrad again, I will continue to work on the assembly stuff, if the bounty isn't done by then.

**Comment by martinloretzzz** [comment]
I won't have the time to work on this bounty in the near future, @stevenandersonz you can take it.

The startup I'm working for might get sold in the next few months and there's so much work to do there.

I will definitely do some smaller refactors and likely a few cool things with the webgpu stuff, but the assembly backend is just to much currently. I'll close my PR(at least for now). 

@stevenandersonz Good luck with finding all the bugs ✨

**Comment by stevenandersonz** [comment]
Yes, I'm still working on this. The latest commit, memops, broke a few things that I'm currently fixing. Aside from that, I'm only missing half16 and int8 cast/ops.

**Pull request closed without merging**
