### PR TITLE
Fix cuda on cifar

### LINKED ISSUE #1224: Some investigation on why CUDA fail on CIFAR
In short, the block size it allocates exceeds the limit of the GPU (for mine 65535)
```
Device 0: "NVIDIA GeForce RTX 2070"
  CUDA Driver Version / Runtime Version          12.2 / 12.2
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 7966 MBytes (8353153024 bytes)
  (036) Multiprocessors, (064) CUDA Cores/MP:    2304 CUDA Cores
  GPU Max Clock rate:                            1620 MHz (1.62 GHz)
  Memory Clock rate:                             7001 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 4194304 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total shared memory per multiprocessor:        65536 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)

``` 
With the `CUDA=1 BS=64 STEPS=50 python3 examples/hlb_cifar10.py` the failure happens when the following kernel was being executed where the gradient for the first layer was being realized by `Lazy`. My understanding on `Lazy` is still limited but I assume the more operations it tries to fuse, the bigger size of a buffer it generates.
```
__global__ void E_65536_2_2_32(float* data0, const float* data1, const float* data2) {
{ int gidx0 = blockIdx.z;  /* 65536 */
{ int gidx1 = blockIdx.y;  /* 2 */
{ int gidx2 = blockIdx.x;  /* 2 */
  { int lidx3 = threadIdx.x;  /* 32 */
    float val1_0 = data1[(((gidx0%16)*2)+((gidx0/16)*2048)+(gidx1*32)+(lidx3*64)+gidx2)];
    float val2_0 = data2[(((gidx0/16)*512)+(gidx0%16)+(lidx3*16))];
    float alu0 = (val1_0==val2_0);
    data0[((((gidx0*4)+(gidx1*2)+gidx2)%64)+((gidx0/16)*2048)+(lidx3*64))] = alu0;
  }}}} /* global+local */
}
```

### LINKED ISSUE #1233: AssertionError: some input tensors not found
While testing my fix for training CIFAR using CUDA, this error occurred after the latest merge.
image
something related to the fix in #1227

### PR DESCRIPTION
**Pull request by g1y5x3**
Fix #1224 by adding `check_device_limit` If the allocated size is bigger than the limit, it creates additional cuda kernels with offset being manually added to the corresponding dimension index using `.replace()` . Currently only did `global[2]` which corresponds to `grid.z`. I want to see if I can reduce the line for those code before adding the check for all `grid.x,y,z` and `block.x,y,z`.

<strike>Fix #1233 with added `.contiguous()` in LR to be able to run CIFAR again.</strike>

Here are some performance comparison
```
CUDA=1 BS=256 STEPS=50 python3 examples/hlb_cifar10.py

49  478.41 ms run,    5.42 ms python,  472.98 ms CL,    1.83 loss, 0.000010 LR, 3.82 GB used,   1220.46 GFLOPS
eval 3542/10000 35.42%,    1.86 val_loss STEP=50
```
```
GPU=1 BS=256 STEPS=50 python3 examples/hlb_cifar10.py

49  480.70 ms run,    8.91 ms python,  471.79 ms CL,    1.84 loss, 0.000010 LR, 3.82 GB used,   1214.64 GFLOPS
eval 3479/10000 34.79%,    1.86 val_loss STEP=50
```

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/ops.py                            9               5
tinygrad/runtime/ops_cuda.py              24               3
------------------------------------------------------------
total                                     33               8
------------------------------------------------------------
lines added in the tinygrad folder: 25
```

**Comment by g1y5x3** [comment]
In CI both `Linters` and `cuda test` has this `AttributeError: type object 'Context' has no attribute 'get_device'`. Did it confuse `cuda.Context` which I imported from the library with what's under `if getenv("CUDACPU", 0) == 1:`?

**Comment by g1y5x3** [comment]
Is the emulated cuda test using CUDACPU=1?

**Comment by g1y5x3** [comment]
Also added `.contiguous()` in LR to fix #1233. What's left is to fix the cuda simulators

**Comment by geohot** [comment]
Can you do just the #1233 fix first?

**Comment by g1y5x3** [comment]
After some discussion in the discord, the global dim limit issue would also happen on WebGPU. However, could this potentially be a bug that [linearizer](https://github.com/tinygrad/tinygrad/blob/872e2198fe87374eb60c05bad7852bda77e2981a/tinygrad/codegen/linearizer.py#L581) did not push everything to the first global dim?
In my example #1235 it was pushed to the third dim.

**Comment by g1y5x3** [comment]
Was going to reduce some lines in `ops_cuda.py` but it seems like #1256 is going to directly affect this, since the error was also caused by `MemOp`. Initially, I was looking into whether its possible to swap `gidx0` and `gidx2` since the latter corresponds to the first dim which has the biggest size.
```
UOps.LOOP           :                           []                               ([<gidx0[0-65535]>, <gidx1[0-1]>, <gidx2[0-1]>], 'global')
UOps.LOOP           :                           []                               ([<lidx3[0-31]>], 'local')
UOps.LOAD           : <val1_0>                  []                               MemOp(i=1, idx=<(((gidx0[0-65535]%16)*2)+((gidx0[0-65535]//16)*2048)+(gidx1[0-1]*32)+(lidx3[0-31]*64)+gidx2[0-1])>, valid=<1>)
UOps.LOAD           : <val2_0>                  []                               MemOp(i=2, idx=<(((gidx0[0-65535]//16)*512)+(gidx0[0-65535]%16)+(lidx3[0-31]*16))>, valid=<1>)
UOps.ALU            : <alu0>                    [<val1_0>, <val2_0>]             BinaryOps.CMPEQ
UOps.STORE          :                           [<alu0>]                         MemOp(i=0, idx=<((((gidx0[0-65535]*4)+(gidx1[0-1]*2)+gidx2[0-1])%64)+((gidx0[0-65535]//16)*2048)+(lidx3[0-31]*64))>, valid=<1>)
UOps.ENDLOOP        :                           []                               ([<gidx0[0-65535]>, <gidx1[0-1]>, <gidx2[0-1]>, <lidx3[0-31]>], 'global+local')
```

**Comment by g1y5x3** [comment]
Currently it fails when I set `BS=1024` but works completely fine with `BS=512` or less. Currently the limit check is only applied when the `ASTRunner` was initialized but not during the kernel execution. There's probably something else that I am missing.
```
GPU=1 CUDA=1 BS=1024 STEPS=50 python examples/hlb_cifar10.py
  
0 3597.16 ms run, 3596.93 ms python,    0.23 ms CL,    2.94 loss, 0.003657 LR, 0.10 GB used,    649.21 GFLOPS
  1 1123.78 ms run, 1123.58 ms python,    0.20 ms CL,    2.30 loss, 0.007314 LR, 15.06 GB used,   2078.08 GFLOPS
  2  610.88 ms run,   19.06 ms python,  591.83 ms CL, 154045.27 loss, 0.009944 LR, 15.06 GB used,   3822.83 GFLOPS
  3  611.60 ms run,   14.44 ms python,  597.15 ms CL, 11998125056.00 loss, 0.009732 LR, 15.06 GB used,   3818.35 GFLOPS
  4  611.05 ms run,   13.89 ms python,  597.16 ms CL, 75332345856.00 loss, 0.009521 LR, 15.06 GB used,   3821.80 GFLOPS
  5  611.39 ms run,   14.95 ms python,  596.45 ms CL, 198118817792.00 loss, 0.009310 LR, 15.06 GB used,   3819.63 GFLOPS
```
Here is the working case for `BS=512`
```
CUDA=1 BS=512 STEPS=1000 python examples/hlb_cifar10.py

999  875.59 ms run,  537.66 ms python,  337.93 ms CL,    0.83 loss, 0.000010 LR, 8.85 GB used,   1333.60 GFLOPS
eval 8991/10000 89.91%,    0.41 val_loss STEP=1000
```

**Comment by g1y5x3** [comment]
Feel like I am all over the place with this fix but end up decided to redo it from `linearizer` and `cstyle` which I believe would be much cleaner.

**Comment by g1y5x3** [comment]
#1299 is the new fix

**Pull request closed without merging**
