### PR TITLE
Fix: AssertionError Transpose/Permute when WHERE Op in LB

### PR DESCRIPTION
**Pull request by ZenginU**
Related #1263,

I have changed the assertion condition but not sure if it against the logic or just overlooked.

Transposing a tensor throws assertion if there is WHERE Ops in the LB.

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/ops.py                            1               1
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by ZenginU** [comment]
@wozeparrot 
I believe it is not about the Transpose itself but happens with the **tensor.permute** as well, I guess maybe the problem is with the evaluation of the where ops??

If you are talking about the test cases for the **replace_with_movement_ops** then I may not be able to add a test case as I dont know the inner workings.

If you are suggesting test cases for Transpose than I believe problem is not only about transpose but may be with WHERE ops

Reproduce with permute (throws assertion)
```python
tensor.Tensor.rand(5, 5, 5).ceil().permute((0, 2, 1)).numpy()
```

**Comment by geohot** [comment]
That's a fine regression test, just anything that currently fails and this change fixes.

**Comment by ZenginU** [comment]
@geohot 
I have added a test with torch equivalent.
Currently nothing fails as ceil/floor is not used before movement ops.

**Comment by wozeparrot** [comment]
Maybe the test should be testing with `.where` directly? Makes the test case simpler and `.ceil` is a little bit broken right now.

**Comment by ZenginU** [comment]
@wozeparrot 
I believe ternaryOps is a new thing so in lazy.py/elementwise_op this function accepts TernaryOps input but I believe author does not edited the ops.py/replace_with_movement_ops.

 So when TernaryOps is in the LB system does not replace it because of the assert. 

I wrote a simple test case using only .where and .permute. Problem only occurs when ".where" is in the Buffer so directly using .where does **not** trigger the assert.

Any more suggestions?

**Comment by wozeparrot** [comment]
Nope! I think the test is fine.

**Pull request merged**
