### PR TITLE
llama JIT python runtime speedup

### PR DESCRIPTION
**Pull request by chenyuxyz**
python 3.11
master python runtime: ~8.1ms
remove JIT call in TransformerBlock: ~7.3ms
+ `-O`: ~7.0ms

### CODE REVIEW

**Comment by geohot** [comment]
Ideally I think you want to pass the int in to the jitted function, then it's valid for that context. Like a tuple (Variable, int) is a valid JIT parameter that you can use in reshapes (or call it a ConcreteVariable). The reshape and reshape back is a weird API and probably pretty slow.

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/jit.py                            4               2
------------------------------------------------------------
lines added in the tinygrad folder: 2
```

**Comment by chenyuxyz** [comment]
or pass a runtime `var_vals` to the jitted function directly, then we can put symbolic reshape and shrink inside jitted functions.

working on the new input check criteria and cleanups, but with this and some `isinstance` -> `__class__`, I am getting `< 5ms` about 10% of the time

**Comment by geohot** [comment]
Speed on this looks pretty good, I consider it sub 5ms! Don't know if there's other things you wants to add or cleanup

```
kafka@tubby:~/fun/tinygrad$ GPU=1 JIT=1 python3.11 examples/llama.py --count 20 --temperature 0 --timing --prompt "Hello."
using GPU backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|████████████████████████████████████████████████████████████████| 292/292 [00:00<00:00, 3012.61it/s]
loaded weights in 109.64 ms, 13.48 GB loaded at 122.93 GB/s
Hello.
ran model in 23707.21 ms
sync in 4416.12 ms
 I
ran model in 450.52 ms
sync in 468.70 ms
'
ran model in 182.76 ms
sync in 4.39 ms
m
ran model in 4.98 ms
sync in 88.86 ms
 a
ran model in 5.09 ms
sync in 88.56 ms
 
ran model in 4.91 ms
sync in 101.35 ms
2
ran model in 5.08 ms
sync in 89.35 ms
0
ran model in 5.11 ms
sync in 89.40 ms
 year
ran model in 5.25 ms
sync in 90.24 ms
 old
ran model in 5.01 ms
sync in 91.25 ms
 male
ran model in 4.75 ms
sync in 91.07 ms
.
ran model in 4.91 ms
sync in 95.14 ms
 I
ran model in 4.97 ms
sync in 92.70 ms
'
ran model in 4.84 ms
sync in 91.88 ms
m
ran model in 5.27 ms
sync in 92.46 ms
 a
ran model in 4.78 ms
sync in 93.04 ms
 student
ran model in 4.75 ms
sync in 93.20 ms
 at
ran model in 4.75 ms
sync in 93.51 ms
 the
ran model in 4.80 ms
sync in 93.77 ms
 University
ran model in 4.85 ms
sync in 94.05 ms
```

**Comment by chenyuxyz** [comment]
2 things I want to think more before merging
(1) ENABLE_METHOD_CACHE seems to produce incorrect cache with reshaping with symbols. I had an issue with the newly added test and I want to get to the bottom of it to see if linearizer key needs any update
(2) if reshape is done inside the jitted function, we cannot check input size in `jit.py` because it does not know we pass a new ctx instead of doing reshape

should be ready in the next day or two

**Comment by chenyuxyz** [comment]
okay ready for review. It's still not a single jit call because of cache has side effect and cannot be jitted. But now jit calls are in the same place, and symbolic reshape and shrink are jitted.

some complication are coming from the fact that `TinyJit` only calls jitted function on the third call. So the second call is tricky that it's on jitted path, but further update to fit an unjitted call. Also for conversational mode the cache is shared between jitted and unjitted path.

to answer my own questions
(1) added variables to the shapetracker key. A function with variables is different from a function that does not.
(2) don't have a good way to assert if we pass `jit_ctx` to change the input instead of reshape. Will need to save shapetracker of inputs right before `ASTRunner.exec` to preserve the full input context.

**Comment by chenyuxyz** [comment]
hmm something is not right, let me investigate.

`JIT=1 GPU=1 KOPT=2 python examples/llama.py --prompt "Hello." --count 10 --temperature=0 --timing`

```
...
  File "/Users/chenyu/code/tinygrad/tinygrad/runtime/ops_gpu.py", line 90, in __call__
    if not hasattr(self, 'argdtypes'): self.set_argdtypes(tuple(None if x.__class__ is CLBuffer else np.int32 for x in bufs))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/runtime/ops_gpu.py", line 84, in set_argdtypes
    def set_argdtypes(self, argdtypes): self.argdtypes, _ = argdtypes, [clprg.set_scalar_arg_dtypes(argdtypes) for clprg in self.clprgs]
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/code/tinygrad/tinygrad/runtime/ops_gpu.py", line 84, in <listcomp>
    def set_argdtypes(self, argdtypes): self.argdtypes, _ = argdtypes, [clprg.set_scalar_arg_dtypes(argdtypes) for clprg in self.clprgs]
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/__init__.py", line 858, in kernel_set_arg_types
    generate_enqueue_and_set_args(
  File "/Users/chenyu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/invoker.py", line 402, in generate_enqueue_and_set_args
    pmod, enqueue_name = _generate_enqueue_and_set_args_module(*cache_key)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/invoker.py", line 271, in _generate_enqueue_and_set_args_module
    subgen, wait_for_parts = gen_arg_setting(in_enqueue=True)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/invoker.py", line 243, in gen_arg_setting
    return generate_specific_arg_handling_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenyu/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pyopencl/invoker.py", line 214, in generate_specific_arg_handling_body
    raise TypeError(
TypeError: length of argument list (3) and CL-generated number of arguments (4) do not agree
```

**Comment by chenyuxyz** [comment]
oh the error is not related to this PR... it's also not working in master. The root cause is that using `Kernel.has_variable_shape` to skip KOPT is not enough because the symbolic shrink used for positional encoding, even with an int shape, is variable dependent.

**Comment by chenyuxyz** [comment]
what I see on my M1 Max, 64GB ram, global mem 17.03GB

```
GPU=1 JIT=1 python3 examples/llama.py --timing --prompt "swag"
using GPU backend
using LLaMA-7B model
ram used: 13.48 GB, freqs_cis                                         : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:00<00:00, 3434.01it/s]
loaded weights in 93.08 ms, 13.48 GB loaded at 144.80 GB/s
swag
ran model in 5800.18 ms
sync in 143.68 ms
gy
ran model in 223.50 ms
sync in 4.28 ms
 c
ran model in 141.62 ms
sync in 4.91 ms


ran model in 5.29 ms
sync in 89.35 ms
oh
ran model in 5.81 ms
sync in 88.44 ms
 man
ran model in 5.01 ms
sync in 89.60 ms
,
ran model in 4.99 ms
sync in 89.73 ms
 this
ran model in 5.01 ms
sync in 90.25 ms
 looks
ran model in 5.00 ms
sync in 90.61 ms
 like
ran model in 5.08 ms
sync in 90.62 ms
 a
ran model in 5.26 ms
sync in 90.76 ms
```

**Comment by chenyuxyz** [comment]
oh I might be able to use `assign` in jitted function for cache and jit the whole thing, let me work on this a bit more

**Comment by chenyuxyz** [comment]
I think the final piece to jit the llama in one call is to implement in place update for kv cache, which can further simplify the distinction between jitted and unjitted path. Added as a TODO for now, I want to implement it in a fresh PR so I don't need to keep syncing this branch if that's fine with you.

For the sync time issue, can you compare with master branch to see if it's specific to this PR? The first ran model time was abnormally long too `21s` vs `6s` that I am seeing, maybe the machine is swapping due to low available memory?

**Comment by geohot** [comment]
Strange, I can reproduce the sync slowness on master too. Agree it's likely swapping somehow

**Comment by geohot** [comment]
Bounty paid!

**Pull request merged**
