### PR TITLE
Update links in new docs

### PR DESCRIPTION
**Pull request by smurfd**
Updating links in `docs/` to point towards https://github.com/tinygrad/tinygrad/blob/master instead of https://tinygrad.github.io/, ie making them work :)

### CODE REVIEW

**Comment by wozeparrot** [comment]
I feel like some of these should point to the hosted docs instead, like references to tensor.py and nn

**Comment by smurfd** [comment]
Im more than happy to change if something is not correct :)
But i believe the hosted docs are .md files, like: https://github.com/tinygrad/tinygrad/blob/master/docs/tensor.md and the links touched here are only .py and from context it makes some sense. They also point to subfolders like `tinygrad/tensor.py` for example or `tinygrad/nn/__init__.py`

**Comment by wozeparrot** [comment]
I think it might be better to rewrite them to point to the tensor.md docs since that's the docs that are nicer for new users.

**Comment by smurfd** [comment]
thanks, updated with nn.md and tensor.md. but kept one for tensor where the example copied the `sparse_categorical_crossentropy()` function

**Pull request merged**
