### PR TITLE
Render docs with Material for MkDocs

### PR DESCRIPTION
**Pull request by david-haerer**
This PR introduces Material for MkDocs to create a static site with the tinygrad documenation.

If this PR is something you like, I can also try to help setup an automatic build / deployment pipeline.

## Showcase

You can have a look at the current build at https://tinygrad.haerer.dev/.

The `abstractions.py` is reformatted so that it renders nicely in the [docs](https://tinygrad.haerer.dev/abstractions/) (with outputs computed during build).

## Motivation

My motivation is to read the docs in a nicer way while learning tinygrad.

## Repo structure

I can also put the `mkdocs.yml` in the root dir, so that `/docs/docs` can be moved back to just `/docs`.

---

Edit: Moved my previous comments in here and added some structure.
(Initially I thought this is a PR from `david-haerer:docs` to `david-haerer:master`. Still learning GitHub 🙈)

### CODE REVIEW

**Comment by david-haerer** [comment]
You can have a look at the current build at https://tinygrad.haerer.dev/.

If this PR is something you like, I can also try to help setup an automatic build / deployment pipeline.

My motivation for introducing MkDocs was to view the docs in a nicer way while learning tinygrad.

**Comment by david-haerer** [comment]
I can also put the `mkdocs.yml` in the root dir, so that `/docs/docs` can be moved back to just `/docs`.

**Comment by wozeparrot** [comment]
Usually documentation prs aren't accepted from new contributors: https://canary.discord.com/channels/1068976834382925865/1068976834928193609/1162379945478209636

This also seems like it adds quite a bit of complexity to the docs (like the move to `/docs/docs`) which I'm not sure if we want yet.

**Comment by geohot** [comment]
Yea, this Is complex and a new system.

**Pull request closed without merging**
