### PR TITLE
Implement Python runtime ops (test_ops.py)

### PR DESCRIPTION
**Pull request by xarkes**
Hello,
I've seen in the PRs this topic is getting some interest so I am pushing my current implementation although it is not cleaned up yet.

```
$ PYTHON=1 python3 ./test/test_ops.py
...
----------------------------------------------------------------------
Ran 245 tests in 5769.725s

OK (skipped=4)
```

Let me know what you think of it, as I am new to this project I hope my understanding of it is good enough.
I will do some refactor a bit later to remove some useless lines.

### CODE REVIEW

**Comment by xarkes** [comment]
Rebased and cleaned up I believe.
The performances are a bit concerning but I think that's to be expected with that many operations.
Feel free to merge whatever you think is valid. Cheers!

**Comment by xarkes** [comment]
Note that the `UOps.IF` implementation is wrong at this stage (eg. nested ifs are not handled - a test should be added for that, but I have no clue how to generate those) and that likely the store implementation is too hacky. KamiKomplex504 gave some hints about how to handle it, and I guess the open dtypes PR may be relevant as well.

**Comment by geohot** [comment]
Tests failing.

**Comment by xarkes** [comment]
`Error: The operation was canceled.`
I think that's because there is a timeout of some sorts on the CI. Maybe I should disable some for the python testing.

**Comment by xarkes** [comment]
Just noticed https://github.com/tinygrad/tinygrad/pull/3384 is finally green too.
From the diff their implementation is likely more accurate so feel free to close this PR.

**Comment by geohot** [comment]
If you think theres is better, I'll close

**Pull request closed without merging**
