### PR TITLE
set metal fast math default to 0 (disabled)

### PR DESCRIPTION
**Pull request by chenyuxyz**
It's a correctness fix because we use inf and nan. Let's see how slow it is

### CODE REVIEW

**Comment by geohot** [comment]
Huh, the failing test is strange. I've always thought there was some deep sync issue with METAL, maybe it's that.

**Comment by chenyuxyz** [comment]
note that speed comparison needs to be measured with no compiler cache

**Comment by chenyuxyz** [comment]
opened issue #3386 to track conv1d failure

i don't know why but it seems to be faster to run with fast math disabled on M1 Max
`DISABLE_COMPILER_CACHE=1 NOCLANG=1 python3 test/external/external_model_benchmark.py`

master
```
resnet50        tinygrad_metal_jitless      49.61 ms
resnet50        tinygrad_metal_jit          25.27 ms
resnet50        torch_cpu                   53.77 ms
resnet50        torch_mps                   20.65 ms
resnet50        onnxruntime_cpu             27.98 ms
resnet50        outputs validated with rtol=2.0e-03, atol=2.0e-03
openpilot       tinygrad_metal_jitless      62.43 ms
openpilot       tinygrad_metal_jit           6.02 ms
openpilot       torch_cpu                 1018.42 ms
openpilot       torch_mps                   26.32 ms
openpilot       onnxruntime_cpu             36.33 ms
openpilot       outputs validated with rtol=2.0e-03, atol=2.0e-03
efficientnet    tinygrad_metal_jitless      73.46 ms
efficientnet    tinygrad_metal_jit          13.22 ms
efficientnet    torch_cpu                  604.24 ms
efficientnet    torch_mps                   12.97 ms
efficientnet    onnxruntime_cpu             46.45 ms
efficientnet    outputs validated with rtol=2.0e-03, atol=2.0e-03
shufflenet      tinygrad_metal_jitless      29.44 ms
shufflenet      tinygrad_metal_jit           2.52 ms
shufflenet      torch_cpu                   26.35 ms
shufflenet      torch_mps                   62.14 ms
shufflenet      onnxruntime_cpu              4.17 ms
shufflenet      outputs validated with rtol=2.0e-03, atol=2.0e-03
commavq         tinygrad_metal_jitless     107.61 ms
commavq         tinygrad_metal_jit           9.43 ms
commavq         onnx2torch       NotImplementedError
commavq         onnxruntime_cpu             68.42 ms
commavq         outputs validated with rtol=2.0e-03, atol=2.0e-03
```

this pr
```
resnet50        tinygrad_metal_jitless      40.62 ms
resnet50        tinygrad_metal_jit          15.81 ms
resnet50        torch_cpu                   56.81 ms
resnet50        torch_mps                   22.50 ms
resnet50        onnxruntime_cpu             31.98 ms
resnet50        outputs validated with rtol=2.0e-03, atol=2.0e-03
openpilot       tinygrad_metal_jitless      64.82 ms
openpilot       tinygrad_metal_jit           5.77 ms
openpilot       torch_cpu                 1092.76 ms
openpilot       torch_mps                   27.42 ms
openpilot       onnxruntime_cpu             37.94 ms
openpilot       outputs validated with rtol=2.0e-03, atol=2.0e-03
efficientnet    tinygrad_metal_jitless      72.75 ms
efficientnet    tinygrad_metal_jit          12.13 ms
efficientnet    torch_cpu                  648.02 ms
efficientnet    torch_mps                   13.56 ms
efficientnet    onnxruntime_cpu             46.11 ms
efficientnet    outputs validated with rtol=2.0e-03, atol=2.0e-03
shufflenet      tinygrad_metal_jitless      30.97 ms
shufflenet      tinygrad_metal_jit           2.02 ms
shufflenet      torch_cpu                   30.68 ms
shufflenet      torch_mps                   63.37 ms
shufflenet      onnxruntime_cpu              4.21 ms
shufflenet      outputs validated with rtol=2.0e-03, atol=2.0e-03
commavq         tinygrad_metal_jitless     111.81 ms
commavq         tinygrad_metal_jit           9.39 ms
commavq         onnx2torch       NotImplementedError
commavq         onnxruntime_cpu             69.08 ms
commavq         outputs validated with rtol=2.0e-03, atol=2.0e-03
```

**Comment by chenyuxyz** [comment]
on M2 Max benchmark it seems to be ~2% faster (cifar) to ~2% slower (float tc gemm), probably within noise. given no significant impact i think it's worth it to merge this

**Comment by chenyuxyz** [comment]
with no significant perf impact, I think merging this to resolve all inf/nan problem on METAL is worth it. I am ready to merge this. @geohot let me know if you have any concerns or perf test suggestions

**Comment by geohot** [comment]
Merged. Can always revert if it's an issue, but I think it's fine.

**Pull request merged**
