### PR TITLE
I have added a new loss file, which currently only contains a simple …

### PR DESCRIPTION
**Pull request by hi-sushanta**
Hello, my name is Chi. I noticed that your framework does not currently have a loss file containing multiple loss functions, so I created one. I have so far added only a single loss function, MSE loss.

And also see what looks like my loss function:
Screenshot from 2023-10-16 07-03-50

### CODE REVIEW

**Comment by geohot** [comment]
Too many lines

**Comment by hi-sushanta** [comment]
what are you trying to say about?

**Comment by wozeparrot** [comment]
this def doesn't belong in a separate file, look in `tensor.py` where the other loss functions currently are.

**Comment by hi-sushanta** [comment]
you understand wrong becuse I try to create this file exactly similar to optim.py file.

**Pull request closed without merging**
