### PR TITLE
Bert: use Tensor.scaled_dot_product_attention

### PR DESCRIPTION
**Pull request by JakobSpahn**
Changes made:

- compute attention with ```Tensor.scaled_dot_product_attention```
- add tests ```test/models/test_bert.py```

### CODE REVIEW

**Comment by JakobSpahn** [comment]
Exclude or include from CI? Because it will download the weights.

**Comment by wozeparrot** [comment]
`test_rnnt` doesn't actually test the whole model, only the lstm part. Probably make it an external test like yolo and yolov8 are because of the large amount of dependencies that need to be pulled in.

**Comment by JakobSpahn** [comment]
This would be a possible version without downloading weights and tokenizer. Don't know why CI doesn't pass on LLVM and GPU (they pass on CLANG), on my machine they pass.

**Comment by wozeparrot** [comment]
running out of memory, can you run a much smaller version?

**Comment by JakobSpahn** [comment]
sorry, forgot to make model smaller. Will test on my fork until it passes and then commit working config here.

**Comment by JakobSpahn** [comment]
```
TORCH=1 python -c "from tinygrad.tensor import Tensor; from tinygrad.helpers import dtypes; (1-Tensor(True, dtype=dtypes.bool)).realize()"
``` 
fails, so skip ```TORCH```

**Comment by wozeparrot** [comment]
Yea, thats known: #1524

**Comment by geohot** [comment]
Thanks!

**Pull request merged**
