### PR TITLE
tinychat UI

### PR DESCRIPTION
**Pull request by demattosanthony**
saw this post: https://x.com/__tinygrad__/status/1845733739713982518

made this pr

### CODE REVIEW

**Comment by wozeparrot** [comment]
Can you post some screenshots?

**Comment by demattosanthony** [comment]
@wozeparrot 
Screenshot 2024-10-15 at 10 36 22 PM


Screenshot 2024-10-15 at 10 38 46 PM



Screenshot 2024-10-15 at 10 43 35 PM

**Comment by geohot** [comment]
Can we keep everything dark mode?

**Comment by demattosanthony** [comment]
> Can we keep everything dark mode? But I think the bubbles definitely look better!

Switched it to dark mode only. Do you like this or want darker?

Screenshot 2024-10-16 at 8 44 09 AM
Screenshot 2024-10-16 at 8 44 17 AM

**Comment by geohot** [comment]
Toggles are bad and options are bad.

**Comment by wozeparrot** [comment]
Yea, looks good to me as well

**Comment by demattosanthony** [comment]
@wozeparrot my bad, brought back total token count

**Comment by geohot** [comment]
Completely broken on my computer

**Comment by geohot** [comment]
image

**Comment by geohot** [comment]
This is way too large of a diff also

**Comment by geohot** [comment]
If you still want to merge this, please make a minimal change to only the chat bubbles. +/- 20 lines max!

**Pull request closed without merging**
