### PR TITLE
refactor _make_hip_code_for_op into pm rules

### PR DESCRIPTION
**Pull request by ignaciosica**
process_replay has diff as casting is no longer fixed and is now a uop

### CODE REVIEW

**Comment by geohot** [comment]
Does process replay match?

**Comment by ignaciosica** [comment]
It does not... but because casting is done at uop level instead of render level.

**Comment by ignaciosica** [comment]
image

This is an example of how it changes

**Comment by geohot** [comment]
Cool, and yea I see what you mean about the precision loss. For bfloat16 I'm fine with removing the middle cast.

**Pull request merged**
