### PR TITLE
new UOp style patterns [run_process_replay]

### PR DESCRIPTION
**Pull request by cpwrs**
~~adds UOp ability to express "all permutations of src",~~ rewrites more patterns in the new UOp style

First PR towards hopefully a bigger refactor. Making UOp equally expressive means they could pattern match without UPat at all. At the very least UPat could be refactored to a dataclass with cleaner types and one constructor (compile).

Patterns UOp can't express yet:
- [ ] All permutations of src
- [ ] For any dtype in set
- [ ] For any op in set
- [ ] Allowed len (less hacky)

### CODE REVIEW

**Comment by DKormann** [comment]
> pattern match without UPat at all

**Comment by DKormann** [comment]
you can just make PHI and DEFINE_ACC (passes tests for me)

**Comment by geohot** [comment]
PHI and DEFINE_ACC aren't commutative though.

A new UOp shouldn't be created for this. Maybe UPat should superclass UOp.

**Comment by cpwrs** [comment]
> A new UOp shouldn't be created for this.

Got it. Any reason UOps.VAR is an exception? The UOp syntax is nice for patterns, especially with all the dunders, which is why I thought adding expression would be worth a few non-rendered UOps. 

It's hard to make a clean refactor if some pattern stuff is expressed in UOp and some is not. I think it should be all or nothing.

There's still a lot of rewrites to the new style without permute() in here, I'll revert the permute stuff.

**Comment by geohot** [comment]
I don't like UOp.VAR, it really should just be a NamedUOp superclass.

**Comment by geohot** [comment]
Merged this, easier to read. I'd support a refactor with the `NOp` class

**Comment by cpwrs** [comment]
Sounds good I'll work on that

**Pull request merged**
