### PR TITLE
perf: specialize match function at UPat init [run_process_replay]

### PR DESCRIPTION
**Pull request by roelofvandijk**
⚠️ This is probably too complex for the 50% speed increase it offers on the `_match` function, but I wanted to share the idea. 

At `UPat` initialization, the `_match` function can be specialized based on which elements of the `UPat` are not None.
This cuts down on unnecessary checks and attribute access.

```
PROFILE=0 python -O test/external/external_benchmark_schedule.py
master
***** model forward in  15.68 ms
***** model schedule in   5.22 ms
***** model lower in 575.02 ms
n:  331816  tm: 210.41ms  tot: 371.24ms uops.py:111:_match                                 <-  66% uops.py:141:rewrite

branch
***** model forward in  15.61 ms
***** model schedule in   5.02 ms
***** model lower in 525.86 ms
n:  331816  tm:  72.74ms  tot: 254.60ms uops.py:134:_match                                 <-  57% uops.py:122:src_unmatch
```

Summary of changes:
  * reduce `_match` to a tuple of `UPat`-specific match functions that only includes the relevant functions. This way, all member lookups are also removed from the matching calls.
  * move permutations from the `src` match (each match call) to the `UPat` init (once)
  * early stopping for the src children match
  * `op`, `dtype` and `arg` matches are simplified to `in tuple`

I tested real functions instead of lambda functions but that does not seem to matter.

Example:

`UPat(UOps.CONST, name="mval")` has `unmatch_funcs=(lambda uop,_: uop.op not in(UOps.CONST,), lambda uop,store: store.setdefault("mval", uop) is not uop)`

### CODE REVIEW

**Comment by DKormann** [comment]
why is it faster? because the lambdas or because you have the different loop for src_unmatch

**Comment by roelofvandijk** [comment]
Both

**Comment by DKormann** [comment]
oh i see the any( ... ) goes through all children that makes sense

**Comment by DKormann** [comment]
this seems like you could get it passed easy when split into independent prs no? also i dont see a reason why this cant be done in almost no additional lines

**Comment by DKormann** [comment]
well than try to pr at least the idea with lambda functions

**Comment by geohot** [comment]
How are you getting 575 ms baseline? On an M3 Pro

```
diane@blak:~/tinygrad$ PROFILE=0 python -O test/external/external_benchmark_schedule.py
***** model forward in  18.74 ms
***** model schedule in   6.11 ms
***** model lower in 872.02 ms
```

I'm okay with the tuple refactor, I just think it should be like 3 lines and not make the syntax worse.

**Comment by roelofvandijkO** [comment]
Python 3.12

**Comment by roelofvandijk** [comment]
Python 3.12, M3 Pro

**Comment by roelofvandijk** [comment]
Closing this, might pull out only the all-tuple init

**Pull request closed without merging**
