### PR TITLE
Failing test: different behavior on different devices

### PR DESCRIPTION
**Pull request by MaxWolf-01**
A simple test for #7161 
~~Interestingly it fails LLVM and not CLANG in CI (in constrast to running it locally).~~ It also fails on LLVM locally.

### CODE REVIEW

**Comment by geohot** [comment]
Any way to make it simpler? Is this the minimum failing case?

**Comment by MaxWolf-01** [comment]
Three lines now. This is the simplest I could come up with.

**Comment by geohot** [comment]
What file does it belong in? Can you add a comment and mark expected failure?

**Comment by MaxWolf-01** [comment]
Not sure why CLANG passes in CI but fails locally for me.

```bash
CLANG=1 python -c """
from tinygrad import Tensor
t = Tensor([[3.0], [2.0], [1.0]]).contiguous()
t[1:] = t[:-1]
assert t.tolist() == [[3.0], [3.0], [2.0]]  # assertion error
"""
```

**Comment by geohot** [comment]
Interesting, merged! Thanks for the clean test

**Pull request merged**
