### PR TITLE
overload half ALU ops in CUDA

### PR DESCRIPTION
**Pull request by Qazalin**
This should fix all ALU ops for half in CUDA
pending CI running tests

### CODE REVIEW

**Comment by Qazalin** [comment]
needs CI that actually compiles CUDA

**Comment by geohot** [comment]
CI should actually compile CUDA

**Comment by Qazalin** [comment]
unblocks the benchmarks to run again - working on getting an implementation on CI

**Comment by Qazalin** [comment]
I tested these locally with nvcc they compile - it fixes this one https://github.com/tinygrad/tinygrad/actions/runs/7079546079/job/19266304610

**Comment by geohot** [comment]
That's fixed with https://github.com/tinygrad/tinygrad/pull/2592/files

**Comment by geohot** [comment]
The benchmark is passing in CI right now. If you want to merge this, we need tests in CI that fail without it and pass with it.

**Comment by Qazalin** [comment]
tests failing here because of these ops not existing https://github.com/tinygrad/tinygrad/actions/runs/7102355600/job/19332520214?pr=2617#step:16:409

**Pull request closed without merging**
