### PR TITLE
UOps.STORE returns the value dtype

### PR DESCRIPTION
**Pull request by Qazalin**
If STORE keeps dtypes.void, it's still inconvenient to get the value's dtype. I think UOp.real_int solves this better.

### CODE REVIEW

**Comment by geohot** [comment]
I really don't like this. That's not the real dtype of the store.

**Comment by Qazalin** [comment]
changes toposort priority: dtype.scalar < dtype.vec
```
#include <metal_stdlib>
using namespace metal;
kernel void E_5_3(device float* data0, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
  float2 cast0 = float2(0.0f,0.0f);
  float2 cast1 = float2(1.0f,0.0f);
  *(data0+14) = 0.0f;
  *((device float2*)(data0+4)) = cast0;
  *((device float2*)(data0+6)) = cast1;
  *((device float2*)(data0+8)) = cast0;
  *((device float2*)(data0+10)) = cast0;
  *((device float2*)(data0+12)) = cast1;
  *((device float4*)(data0+0)) = float4(1.0f,0.0f,0.0f,0.0f);
}
```
vs
```
#include <metal_stdlib>
using namespace metal;
kernel void E_5_3(device float* data0, uint3 gid [[threadgroup_position_in_grid]], uint3 lid [[thread_position_in_threadgroup]]) {
  float2 cast0 = float2(0.0f,0.0f);
  float2 cast1 = float2(1.0f,0.0f);
  *((device float4*)(data0+0)) = float4(1.0f,0.0f,0.0f,0.0f);
  *((device float2*)(data0+4)) = cast0;
  *((device float2*)(data0+6)) = cast1;
  *((device float2*)(data0+8)) = cast0;
  *((device float2*)(data0+10)) = cast0;
  *((device float2*)(data0+12)) = cast1;
  *(data0+14) = 0.0f;
}
```

**Comment by geohot** [comment]
What's the downside to store having dtype void?

**Comment by Qazalin** [comment]
yea, having a separate codepath for UOps.STORE is fine for now.

**Pull request closed without merging**
