### PR TITLE
hip gemm fp16 115TFLOPS assembly kernel

### PR DESCRIPTION
**Pull request by g1y5x3**
it turns out what I really need was HIP logging tool instead of rocBLAS logging tool. The code is emitted when compiling rocblas.

image

### CODE REVIEW

**Comment by geohot** [comment]
Why doesn't the Python wrapper work? It shouldn't be slower

**Comment by geohot** [comment]
Any progress on this?

**Comment by g1y5x3** [comment]
still working on pull the kernels from jax before making a wrapper for the assembly. haven't gotten much time to work on it this week.

**Comment by g1y5x3** [comment]
closing since matmul from JAX performs way better. currently able to pull the mlir code out of jax but really need to play with MLIR compiler a bit more to be able to pull out probably assembly code it compiles

**Pull request closed without merging**
