### PR TITLE
KOPT: move to new apply_opt, ng suggest

### PR DESCRIPTION
**Pull request by chaosagent**
redo of #2029 

need to move the kopt stuff off the main optimization path

as always, can use more testing

### CODE REVIEW

**Comment by geohot** [comment]
Hmm, this needs to be a red diff. Unless there's a reason not to, we have to commit and rip out the old stuff.

**Comment by chaosagent** [comment]
Eh, i guess we just move it to extra until the current RL contest experiments conclude.

**Comment by geohot** [comment]
I deleted `apply_auto_opt` this morning.

**Comment by chaosagent** [comment]
nevergrad is kill

**Pull request closed without merging**
