### PR TITLE
speedup _match

### PR DESCRIPTION
**Pull request by DKormann**
matching was way worse than exponential on certain cases

```python
u = UOp.const(dtypes.int, 1)
p = UPat(name = "a")

for i in range(11):
  u = u+u
  p = UPat(UOps.ALU, BinaryOps.ADD, [p, p])

len(_match(u, p, {}))
```

### CODE REVIEW

**Comment by DKormann** [comment]
still the runtime is exponential i will look into caching for the _match function itself

**Comment by DKormann** [comment]
not sure how relevant this is because it might be exponential runtime only in regard to UPat depth which maybe shouldnt be too big in the first place

**Comment by DKormann** [comment]
will look into faster caches maybe store could be a tuple instead of a dict since it should only hold a small number of keys anyway

**Comment by geohot** [comment]
Can you benchmark this generally on real world workloads? We should never do speedups that only improve a contrived test

**Pull request closed without merging**
