### PR TITLE
cache ast_parse

### PR DESCRIPTION
**Pull request by DKormann**
minor refactor + cached ast_parse gonna lead to exp speedup for #2305 with one more cache in map_buffers

### CODE REVIEW

**Comment by roelofvandijk** [comment]
Have you measured the speed, for example for the llama example?

**Comment by DKormann** [comment]
so far I am measuring speed only for stuff like:

for i in range(100): x = x + x 
x.realize()

but i suspect that there are going to be speedups for Transformer models too although only exponential with number of attention layers. Also this speedup is only relevant for building and compiling ast so unrelated to performance after JIT.

**Comment by roelofvandijk** [comment]
Only after the hash override, I think.

**Comment by geohot** [comment]
Why is this a draft? Do we want it?

**Comment by DKormann** [comment]
Working at rnnt atm l. Gonna come back to it

**Pull request closed without merging**
