### PR TITLE
Fix: BEAM search with PTX fails

### PR DESCRIPTION
**Pull request by Eliulm**
`uops_to_asm` only accepts `UOpGraph` instead of list

### CODE REVIEW

**Comment by geohot** [comment]
Can you add a test to CI that would have caught this?

**Comment by Eliulm** [comment]
Sure thing!

**Comment by Eliulm** [comment]
@geohot  Was unsure whether I should add the test in `test/external` or add to `test/test_search.py`. I think we want the later, sorry.

**Comment by chenyuxyz** [comment]
I think having type checker catching this is fine. I am working on beam search tests for all ci devices

**Pull request merged**
