### PR TITLE
Enable Multi-Output Export

### PR DESCRIPTION
**Pull request by kashyapakshay**
Support for models that typically return multiple tensors (eg, regression + confidences in SSD)

### CODE REVIEW

**Comment by geohot** [comment]
Can you get the e2e webgpu tests working again? With a test for that, I think this is good to merge

**Comment by kashyapakshay** [comment]
@geohot I assume that's the webgpu pytest that was disabled in #1471 ? Or is that something else?

**Comment by geohot** [comment]
Nah, idk if that can work. Just something fully end to end that tests the multioutput

**Comment by kashyapakshay** [comment]
Modified `examples/index.html` to account for a list of outputs now and re-enabled `test_webgpu.js` to test running the webgpu efficientnet. I'm happy to write another example compile script for a model with multiple outputs but wanted to avoid boilerplate code.

**Comment by geohot** [comment]
LGTM, nice to have this tested again. I think that coverage is fine (confirms no efficientnet regression)

**Pull request merged**
