### PR TITLE
Shorter

### PR DESCRIPTION
**Pull request by geohot**

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                         9              25
------------------------------------------------------------
lines added in the tinygrad folder: -16
```

**Comment by ZenginU** [comment]
if -7 lines help maybe we can add #1440 to this PR?

**Comment by geohot** [comment]
Is #1440 completely tested?

**Comment by ZenginU** [comment]
It is refactor so only tested with existing tests, if you want I can open a PR for "shorter" branch

**Comment by geohot** [comment]
See this is the problem. That PR is really code golf.

**Pull request merged**
