### PR TITLE
extend print_tree to uops +1 line

### PR DESCRIPTION
**Pull request by DKormann**
helpful for understanding uops and rearange.
had to break one if line because it got too long

### CODE REVIEW

**Comment by DKormann** [comment]
```
  0 ━┳ STORE 
  1  ┣━━ DEFINE_GLOBAL (0, True)
  2  ┣━┳ RANGE (1, 0)
  3  ┃ ┣━━ CONST 
  4  ┃ ┗━━ CONST 2
  5  ┗━┳ ALU BinaryOps.ADD
  6    ┣━┳ LOAD 
  7    ┃ ┣━━ DEFINE_GLOBAL (1, False)
  8    ┃ ┗━┳ RANGE (1, 0)
  9    ┃   ┣━━ CONST 
 10    ┃   ┗━━ CONST 2
 11    ┗━┳ LOAD 
 12      ┣━━ DEFINE_GLOBAL (1, False)
 13      ┗━┳ RANGE (1, 0)
 14        ┣━━ CONST 
 15        ┗━━ CONST 2
```

**Comment by DKormann** [comment]
using hasattr 4 times is repetetive could write it as a one liner function would lead to same number of lines but more characters. arguable harder to read

**Comment by DKormann** [comment]
yeah still nice to visualize as tree i think.

and AST is also technically a directed acyclical graph no?

**Comment by chenyuxyz** [comment]
yea i guess that makes sense, uop and lazyop are similar

**Comment by DKormann** [comment]
nice example visualizing graph rewrite:

```python


Device.DEFAULT = "CLANG"

x = Tensor([1,2])

x = x + (-x) 

sched = x.schedule()
ast = sched[1].ast

renderer = Device["CLANG"].renderer
lin = get_linearizer(renderer, ast)
lin.linearize()

store = lin.uops.sinks[0]

print_tree(store)

from tinygrad.codegen.uops import constant_folder
lin.uops.nodes = {}
sink  =lin.uops.graph_rewrite(store, constant_folder)

print_tree(sink)
```

```
  0 ━┳ STORE 
  1  ┣━━ DEFINE_GLOBAL (0, True)
  2  ┣━┳ RANGE (1, 0)
  3  ┃ ┣━━ CONST 
  4  ┃ ┗━━ CONST 2
  5  ┗━┳ ALU BinaryOps.ADD
  6    ┣━┳ LOAD 
  7    ┃ ┣━━ DEFINE_GLOBAL (1, False)
  8    ┃ ┗━┳ RANGE (1, 0)
  9    ┃   ┣━━ CONST 
 10    ┃   ┗━━ CONST 2
 11    ┗━┳ ALU UnaryOps.NEG
 12      ┗━┳ LOAD 
 13        ┣━━ DEFINE_GLOBAL (1, False)
 14        ┗━┳ RANGE (1, 0)
 15          ┣━━ CONST 
 16          ┗━━ CONST 2
  0 ━┳ STORE 
  1  ┣━━ DEFINE_GLOBAL (0, True)
  2  ┣━┳ RANGE (1, 0)
  3  ┃ ┣━━ CONST 
  4  ┃ ┗━━ CONST 2
  5  ┗━━ CONST 
  ```

**Comment by DKormann** [comment]
yeah also was wondering if its planned to unify them ever?

**Comment by geohot** [comment]
Neat! Yea I've been thinking about unifying them.

I'd merge a PR that renames uop->op and vin->src in `class UOp` to match LazyOp

**Comment by DKormann** [comment]
> Neat! Yea I've been thinking about unifying them.
> 
> I'd merge a PR that renames uop->op and vin->src in `class UOp` to match LazyOp. That would also simplify this.

yes nice!

**Pull request merged**
