### PR TITLE
NOp field name [run_process_replay]

### PR DESCRIPTION
**Pull request by DKormann**

### CODE REVIEW

**Comment by geohot** [comment]
Always be in the habit of "[run_process_replay]" in the PR title on refactors like this

**Comment by DKormann** [comment]
run process replay is running per default https://github.com/tinygrad/tinygrad/actions/runs/10118219467/job/27984684885?pr=5742

**Comment by chenyuxyz** [comment]
it runs by default but does not assert if all are the same, and refactoring like this should keep kernels the same

**Comment by DKormann** [comment]
ahh thanks

**Pull request merged**
