### PR TITLE
Fix Clang Race Condition

### PR DESCRIPTION
**Pull request by l-j-g**
implement thread lock until clang file is compiled

### CODE REVIEW

**Comment by wozeparrot** [comment]
I don't think this even works? pytest uses multiple processes not threads so holding a thread lock will do nothing to prevent cross process race conditions?

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/runtime/ops_clang.py              9               4
------------------------------------------------------------
lines added in the tinygrad folder: 5
```

**Comment by l-j-g** [comment]
> oh i see, maybe a process lock would work instead?

**Comment by geohot** [comment]
No. Fix this with the file name, not a lock.

**Pull request closed without merging**
