### PR TITLE
late UOps.IF generation [run_process_replay] [no_assert]

### PR DESCRIPTION
**Pull request by Qazalin**
1. Remove UOps.IF manual insertion from the Linearizer
2. Combines `valid` gate from the ShapeTracker with the thread gate
```diff
   __syncthreads();
-  if ((lidx1<1)) {
+  if ((alu0*(lidx1<1))) {
     float acc0 = 0.0f;
     for (int ridx0 = 0; ridx0 < 4; ridx0++) {
       float val2 = temp[ridx0];
       acc0 = (val2+acc0);
     }
-    if (alu0) { data0[gidx0] = acc0; }
+    data0[gidx0] = acc0;
   }
 }
 ```

### CODE REVIEW

**Comment by Qazalin** [comment]
status:
- got correctness for single gates
- working on: a) multi output stores sharing the IF b) upcasted stores that don't share IF but can nest, eg:
```
  bool alu0 = (gidx0<36);
  bool alu1 = (gidx0<37);
  if (alu1) { *(data0+alu2) = (((alu1?1.0f:0.0f)<acc0)?(alu1?1:0):0); }
  if (alu0) { *(data0+alu2+1) = ((alu4<acc1)?alu3:0); }
  if (alu0) { *(data0+alu2+2) = ((alu4<acc2)?alu3:0); }
  if (alu0) { *(data0+alu2+3) = ((alu4<acc3)?alu3:0); }
  if (alu0) { *(data0+alu2+4) = ((alu4<acc4)?alu3:0); }
  if (alu0) { *(data0+alu2+5) = ((alu4<acc5)?alu3:0); }
  if (alu0) { *(data0+alu2+6) = ((alu4<acc6)?alu3:0); }
  if (alu0) { *(data0+alu2+7) = ((alu4<acc7)?alu3:0); }
```

**Review by Qazalin — COMMENTED** [review]
status:

done:
- single gates
- multi output stores sharing the IF - this is done with the `exprs` ctx
```
__kernel void r2_320_289(__global int* data0, __global int* data1, const __global float* data2) {
  int gidx0 = get_group_id(0); /* 320 */
  bool alu0 = (gidx0<289);
  if (alu0) {
    float acc0 = -INFINITY;
    for (int ridx0 = 0; ridx0 < 289; ridx0++) {
      float val0 = (alu0?data2[gidx0+(ridx0*289)]:0.0f);
      float alu1 = max(val0,acc0);
      acc0 = alu1;
    }
    bool alu2 = ((alu0?1.0f:0.0f)<acc0);
    data0[gidx0] = (alu2?(alu0?1:0):0);
    data1[gidx0] = (alu2?(alu0?2:0):0);
  }
}
```

working on:
- upcasted stores that don't share IF but can nest:
```
  bool alu0 = (gidx0<36);
  bool alu1 = (gidx0<37);
  if (alu1) { *(data0+alu2) = (((alu1?1.0f:0.0f)<acc0)?(alu1?1:0):0); }
  if (alu0) { *(data0+alu2+1) = ((alu4<acc1)?alu3:0); }
  if (alu0) { *(data0+alu2+2) = ((alu4<acc2)?alu3:0); }
  if (alu0) { *(data0+alu2+3) = ((alu4<acc3)?alu3:0); }
  if (alu0) { *(data0+alu2+4) = ((alu4<acc4)?alu3:0); }
  if (alu0) { *(data0+alu2+5) = ((alu4<acc5)?alu3:0); }
  if (alu0) { *(data0+alu2+6) = ((alu4<acc6)?alu3:0); }
  if (alu0) { *(data0+alu2+7) = ((alu4<acc7)?alu3:0); }
```
- removing IF from the Linearizer

This work also reveals we don't have good test coverage for:
1. LOCAL+PADTO
2. multi output PADTO

**Comment by Qazalin** [comment]
Insight: late UOps.IF is the same problem as Block. It needs to get the LCA of the block not the entire graph.

image once Block is solved then rewriting is easy.

**Comment by geohot** [comment]
Is there a blocker on this?

**Comment by Qazalin** [comment]
Blocking:

1. The pattern matcher is limited to rewriting only one node, I need to rewrite both LCA and the STORE
2. The way I handle BARRIER children is a hack, need to clean it up.

non-blockers:
- Reorder multiple UOps.IFs in the toposort. This helps with register pressure.
- Split UOps into Blocks pre rewrite. This will make the rewrite much easier to reason about.

**Comment by geohot** [comment]
"I need to rewrite both LCA and the STORE" -- I don't think this will be possible in the PatternMatcher. I'd be fine with adding it to the linearization step instead.

**Pull request merged**
