### PR TITLE
Revert "Revert "Ring allreduce in multitensor""

### PR DESCRIPTION
**Pull request by geohot**
Reverts tinygrad/tinygrad#3840

@uuuvn An HSA sync issue was fixed, testing if this fixes the accuracy issue.

We still need the test fixed and RING=2 though.

### CODE REVIEW

**Comment by geohot** [comment]
Hmm, still failing with eval_acc_pct=93.47098214285714 < 93.5

**Comment by uuuvn** [comment]
> Reverts #3840
> 
> @uuuvn An HSA sync issue was fixed, testing if this fixes the accuracy issue.
> 
> We still need the test fixed and RING=2 though.

It is already in uuuvn/tinygrad branch ring_allreduce_v2, i can merge it here if you give me write access to this branch/pr

**Comment by uuuvn** [comment]
I've created a new pr - #3852 

Btw the rest of accuracy drop after HSA fix looks like numerical instability/rounding, but not confirmed yet (max abs diff between ring and naive on float32 is around 1e-8, on float16 0.001 and sometimes even 0.01), slowly training hlb_cifar on my mac to confirm/disconfirm now because tiny10 is busy with some mlperf stuff

**Comment by uuuvn** [comment]
FP32 naive
`PYTHONPATH=. STEPS=350 BS=1536 GPUS=6 TARGET_EVAL_ACC_PCT=93.5 RING=0 python3 examples/hlb_cifar10.py`
```
343 1916.94 ms run, 1916.59 ms python,    0.35 ms METAL * 6,  494.52 loss, 0.000161 LR, 12.74 GB used,   1050.86 GFLOPS,   2014.44 GOPS
344 1885.31 ms run, 1884.97 ms python,    0.34 ms METAL * 6,  489.08 loss, 0.000148 LR, 12.74 GB used,   1068.49 GFLOPS,   2014.44 GOPS
345 1885.48 ms run, 1885.04 ms python,    0.44 ms METAL * 6,  489.24 loss, 0.000136 LR, 12.74 GB used,   1068.40 GFLOPS,   2014.44 GOPS
346 1883.42 ms run, 1883.03 ms python,    0.39 ms METAL * 6,  487.52 loss, 0.000123 LR, 12.74 GB used,   1069.57 GFLOPS,   2014.44 GOPS
347 1881.48 ms run, 1881.11 ms python,    0.37 ms METAL * 6,  489.96 loss, 0.000111 LR, 12.74 GB used,   1070.67 GFLOPS,   2014.44 GOPS
348 1887.92 ms run, 1887.59 ms python,    0.33 ms METAL * 6,  491.64 loss, 0.000098 LR, 12.74 GB used,   1067.02 GFLOPS,   2014.44 GOPS
349 1890.62 ms run, 1890.15 ms python,    0.47 ms METAL * 6,  489.55 loss, 0.000086 LR, 12.74 GB used,   1065.49 GFLOPS,   2014.44 GOPS
shuffling test dataset in 80.79 ms (epoch=0)
eval     10064/10752 93.60%,    0.41 val_loss STEP=350 (in 8402.32 ms)
eval_acc_pct=93.60119047619048 >= 93.5
```

FP32 ring
`PYTHONPATH=. STEPS=350 BS=1536 GPUS=6 TARGET_EVAL_ACC_PCT=93.5 python3 examples/hlb_cifar10.py`
```
343 1923.35 ms run, 1922.96 ms python,    0.39 ms METAL * 6,  493.51 loss, 0.000161 LR, 12.50 GB used,   1047.37 GFLOPS,   2014.46 GOPS
344 1917.75 ms run, 1917.39 ms python,    0.36 ms METAL * 6,  491.11 loss, 0.000148 LR, 12.50 GB used,   1050.43 GFLOPS,   2014.46 GOPS
345 1921.36 ms run, 1920.94 ms python,    0.42 ms METAL * 6,  489.50 loss, 0.000136 LR, 12.50 GB used,   1048.45 GFLOPS,   2014.46 GOPS
346 1890.15 ms run, 1889.72 ms python,    0.43 ms METAL * 6,  488.45 loss, 0.000123 LR, 12.50 GB used,   1065.77 GFLOPS,   2014.46 GOPS
347 1903.11 ms run, 1902.78 ms python,    0.32 ms METAL * 6,  489.00 loss, 0.000111 LR, 12.50 GB used,   1058.51 GFLOPS,   2014.46 GOPS
348 1907.70 ms run, 1907.42 ms python,    0.28 ms METAL * 6,  492.54 loss, 0.000098 LR, 12.50 GB used,   1055.97 GFLOPS,   2014.46 GOPS
349 1918.14 ms run, 1917.76 ms python,    0.38 ms METAL * 6,  488.20 loss, 0.000086 LR, 12.50 GB used,   1050.22 GFLOPS,   2014.46 GOPS
shuffling test dataset in 42.98 ms (epoch=0)
eval     10072/10752 93.68%,    0.42 val_loss STEP=350 (in 8254.14 ms)
eval_acc_pct=93.67559523809523 >= 93.5
```

FP16 naive
`PYTHONPATH=. STEPS=350 BS=1536 GPUS=6 TARGET_EVAL_ACC_PCT=93.5 HALF=1 RING=0 python3 examples/hlb_cifar10.py`
```
342  873.32 ms run,  872.93 ms python,    0.39 ms METAL * 6,  489.00 loss, 0.000174 LR, 6.60 GB used,   2306.78 GFLOPS,   2014.54 GOPS
343  887.05 ms run,  886.65 ms python,    0.40 ms METAL * 6,  492.25 loss, 0.000161 LR, 6.60 GB used,   2271.06 GFLOPS,   2014.54 GOPS
344  892.53 ms run,  892.27 ms python,    0.27 ms METAL * 6,  489.75 loss, 0.000148 LR, 6.60 GB used,   2257.11 GFLOPS,   2014.54 GOPS
345  888.69 ms run,  888.26 ms python,    0.43 ms METAL * 6,  491.50 loss, 0.000137 LR, 6.60 GB used,   2266.87 GFLOPS,   2014.54 GOPS
346  892.11 ms run,  891.69 ms python,    0.43 ms METAL * 6,  490.00 loss, 0.000124 LR, 6.60 GB used,   2258.17 GFLOPS,   2014.54 GOPS
347  894.34 ms run,  893.94 ms python,    0.40 ms METAL * 6,  488.50 loss, 0.000112 LR, 6.60 GB used,   2252.54 GFLOPS,   2014.54 GOPS
348  899.30 ms run,  898.87 ms python,    0.44 ms METAL * 6,  491.50 loss, 0.000099 LR, 6.60 GB used,   2240.12 GFLOPS,   2014.54 GOPS
349  901.95 ms run,  901.44 ms python,    0.51 ms METAL * 6,  488.50 loss, 0.000086 LR, 6.60 GB used,   2233.54 GFLOPS,   2014.54 GOPS
shuffling test dataset in 29.09 ms (epoch=0)
eval     10075/10752 93.70%,    0.42 val_loss STEP=350 (in 4705.38 ms)
eval_acc_pct=93.70349702380952 >= 93.5
```

FP16 ring
`PYTHONPATH=. STEPS=350 BS=1536 GPUS=6 TARGET_EVAL_ACC_PCT=93.5 HALF=1 python3 examples/hlb_cifar10.py`
```
340  924.34 ms run,  923.77 ms python,    0.57 ms METAL * 6,  493.00 loss, 0.000199 LR, 6.49 GB used,   2179.46 GFLOPS,   2014.56 GOPS
341  901.15 ms run,  900.61 ms python,    0.54 ms METAL * 6,  487.50 loss, 0.000186 LR, 6.49 GB used,   2235.55 GFLOPS,   2014.56 GOPS
342  907.04 ms run,  906.69 ms python,    0.34 ms METAL * 6,  488.25 loss, 0.000174 LR, 6.49 GB used,   2221.04 GFLOPS,   2014.56 GOPS
343  899.75 ms run,  899.20 ms python,    0.54 ms METAL * 6,  494.50 loss, 0.000161 LR, 6.49 GB used,   2239.04 GFLOPS,   2014.56 GOPS
344  887.92 ms run,  887.55 ms python,    0.38 ms METAL * 6,  491.00 loss, 0.000148 LR, 6.49 GB used,   2268.85 GFLOPS,   2014.56 GOPS
345  909.86 ms run,  909.26 ms python,    0.60 ms METAL * 6,  489.00 loss, 0.000137 LR, 6.49 GB used,   2214.15 GFLOPS,   2014.56 GOPS
346  894.46 ms run,  893.97 ms python,    0.49 ms METAL * 6,  488.50 loss, 0.000124 LR, 6.49 GB used,   2252.26 GFLOPS,   2014.56 GOPS
347  909.23 ms run,  908.61 ms python,    0.62 ms METAL * 6,  488.75 loss, 0.000112 LR, 6.49 GB used,   2215.68 GFLOPS,   2014.56 GOPS
348  884.99 ms run,  884.30 ms python,    0.68 ms METAL * 6,  492.75 loss, 0.000099 LR, 6.49 GB used,   2276.38 GFLOPS,   2014.56 GOPS
349  898.78 ms run,  898.21 ms python,    0.57 ms METAL * 6,  489.00 loss, 0.000086 LR, 6.49 GB used,   2241.45 GFLOPS,   2014.56 GOPS
shuffling test dataset in 28.03 ms (epoch=0)
eval     10061/10752 93.57%,    0.42 val_loss STEP=350 (in 4950.45 ms)
eval_acc_pct=93.57328869047619 >= 93.5
```

FP32 | 93.60 vs 93.67 (+0.07 on ring)
FP16 | 93.70 vs 93.57 (-0.13 on ring)

This is on metal, looks acceptable. Can't test on HSA yet due to tiny10 being busy with some mlperf job

**Comment by geohot** [comment]
From CI:

ValueError: eval_acc_pct=93.47098214285714 < 93.5

Why is ring worse?

**Comment by uuuvn** [comment]
> From CI:
> 
> ValueError: eval_acc_pct=93.47098214285714 < 93.5
> 
> Why is ring worse with FP16? How confident are you that this isn't a bug?

95% that isn't a bug

Ran 10 times each ring/naive with different seeds to check how big are fluctuations:
```
(.venv) uuuvn@tiny10:~/src/tinygrad$ for i in `seq 10`; do PYTHONPATH=. STEPS=350 BS=1536 GPUS=6 HALF=1 SEED=$i python3 examples/hlb_cifar10.py | tail -1 >> ring.txt; done
(.venv) uuuvn@tiny10:~/src/tinygrad$ for i in `seq 10`; do PYTHONPATH=. STEPS=350 BS=1536 GPUS=6 HALF=1 SEED=$i RING=0 python3 examples/hlb_cifar10.py | tail -1 >> naive.txt; done
(.venv) uuuvn@tiny10:~/src/tinygrad$ cat ring.txt
eval     10057/10752 93.54%,    0.42 val_loss STEP=350 (in 1624.86 ms)
eval     10054/10752 93.51%,    0.42 val_loss STEP=350 (in 1609.21 ms)
eval     10087/10752 93.82%,    0.42 val_loss STEP=350 (in 1611.75 ms)
eval     10060/10752 93.56%,    0.42 val_loss STEP=350 (in 1610.06 ms)
eval     10040/10752 93.38%,    0.42 val_loss STEP=350 (in 1616.03 ms)
eval     10057/10752 93.54%,    0.42 val_loss STEP=350 (in 1621.79 ms)
eval     10035/10752 93.33%,    0.42 val_loss STEP=350 (in 1614.54 ms)
eval     10066/10752 93.62%,    0.42 val_loss STEP=350 (in 1618.25 ms)
eval     10034/10752 93.32%,    0.42 val_loss STEP=350 (in 1610.89 ms)
eval     10065/10752 93.61%,    0.42 val_loss STEP=350 (in 1606.81 ms)
(.venv) uuuvn@tiny10:~/src/tinygrad$ cat naive.txt
eval     10093/10752 93.87%,    0.42 val_loss STEP=350 (in 1462.24 ms)
eval     10048/10752 93.45%,    0.42 val_loss STEP=350 (in 1612.22 ms)
eval     10092/10752 93.86%,    0.42 val_loss STEP=350 (in 1614.75 ms)
eval     10078/10752 93.73%,    0.42 val_loss STEP=350 (in 1601.61 ms)
eval     10069/10752 93.65%,    0.42 val_loss STEP=350 (in 1605.90 ms)
eval     10039/10752 93.37%,    0.42 val_loss STEP=350 (in 1608.36 ms)
eval     10057/10752 93.54%,    0.42 val_loss STEP=350 (in 1475.33 ms)
eval     10067/10752 93.63%,    0.42 val_loss STEP=350 (in 1468.30 ms)
eval     10059/10752 93.55%,    0.42 val_loss STEP=350 (in 1476.54 ms)
eval     10073/10752 93.68%,    0.42 val_loss STEP=350 (in 1612.18 ms)
(.venv) uuuvn@tiny10:~/src/tinygrad$
```

The difference between ring/naive seems well within the bounds of random fluctuations with different init seeds. My current best guess is that small diffrences in results between ring/naive (orders of 1e-8 on fp32 and 0.001 on fp16) add up to a different optimization path

**Comment by uuuvn** [comment]
Also made a modification to do naive allreduce + inject some noise instead of ring:

```
(.venv) uuuvn@tiny10:~/src/tinygrad$ git diff
diff --git a/tinygrad/features/multi.py b/tinygrad/features/multi.py
index 53676965..5d126f89 100644
--- a/tinygrad/features/multi.py
+++ b/tinygrad/features/multi.py
@@ -19,6 +19,16 @@ def all_reduce(op: ReduceOps, lbs: List[LazyBuffer]) -> List[LazyBuffer]:
   if DEBUG >= 2: print(f"{'RING ALLREDUCE' if use_ring else 'NAIVE ALLREDUCE'} {n_lbs}x{dim} | {lbs[0].dtype}")
   if not use_ring:
     return [functools.reduce(lambda x,y: x.e(bop, y), [x.copy_to_device(lb.device) for x in lbs]) for lb in lbs]
+  def custom_random(out):
+    import numpy as np
+    from tinygrad import dtypes
+    from tinygrad.helpers import getenv
+    rng = np.random.default_rng(getenv("RING_INJECT_RANDOM_SEED", 1))
+    if out.dtype == dtypes.half: rng_np_buffer = (rng.integers(low=0, high=2047, size=out.size) / 2048).astype(np.half, copy=False)
+    else: rng_np_buffer = rng.random(size=out.size, dtype=np.float32).astype(dtype=out.dtype.np, copy=False)
+    rng_np_buffer /= 1e6
+    out.copyin(rng_np_buffer.data)
+  return [functools.reduce(lambda x,y: x.e(bop, y), [x.copy_to_device(lb.device) for x in lbs]).e(BinaryOps.ADD, LazyBuffer.loadop(LoadOps.CUSTOM, lb.shape, lb.dtype, lb.device, custom_random)) for lb in lbs]
   base, left = dim // n_lbs, dim % n_lbs
   c_lens = [base + 1 if left - i > 0 else base for i in range(n_lbs)]
   acc = 0
(.venv) uuuvn@tiny10:~/src/tinygrad$ for i in `seq 10`; do PYTHONPATH=. STEPS=350 BS=1536 GPUS=6 HALF=1 RING_INJECT_RANDOM_SEED=$i python3 examples/hlb_cifar10.py | tail -1 >> noise.txt; done
^CTraceback (most recent call last):
  File "/home/uuuvn/src/tinygrad/examples/hlb_cifar10.py", line 438, in <module>
    train_cifar()
  File "/home/uuuvn/src/tinygrad/examples/hlb_cifar10.py", line 415, in train_cifar
    loss = train_step_jitted(model, [opt_bias, opt_non_bias], [lr_sched_bias, lr_sched_non_bias], X, Y)
  File "/home/uuuvn/src/tinygrad/tinygrad/features/jit.py", line 115, in __call__
    for ji in self.jit_cache: ji.prg(cast(List[Buffer], ji.rawbufs), var_vals, wait=DEBUG>=2, jit=True)
  File "/home/uuuvn/src/tinygrad/tinygrad/realize.py", line 19, in __call__
    def __call__(self, rawbufs:List[Buffer], var_vals:Dict[Variable, int], wait=False, jit=False): self.fxn(*rawbufs)
  File "/home/uuuvn/src/tinygrad/tinygrad/features/multi.py", line 30, in custom_random
    out.copyin(rng_np_buffer.data)
  File "/home/uuuvn/src/tinygrad/tinygrad/device.py", line 104, in copyin
    def copyin(self, mv:memoryview):
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

(.venv) uuuvn@tiny10:~/src/tinygrad$ cat noise.txt
eval     10086/10752 93.81%,    0.42 val_loss STEP=350 (in 1603.43 ms)
eval     10045/10752 93.42%,    0.42 val_loss STEP=350 (in 1607.35 ms)
eval     10082/10752 93.77%,    0.42 val_loss STEP=350 (in 1601.82 ms)
eval     10072/10752 93.68%,    0.42 val_loss STEP=350 (in 1603.34 ms)
eval     10084/10752 93.79%,    0.42 val_loss STEP=350 (in 1591.65 ms)
(.venv) uuuvn@tiny10:~/src/tinygrad$
```

So the same thing with fluctuations applies when there is even a little bit of noise which there is with ring. 99% confident that this isn't a bug now

**Comment by chenyuxyz** [comment]
i did a round of test and merged #3852

**Pull request closed without merging**
