### PR TITLE
Remove BinaryOps.SUB, use UnaryOps.NEG/BinaryOps.ADD

### PR DESCRIPTION
**Pull request by Fraudik**
Replaced BinaryOps.SUB with UnaryOps.NEG/BinaryOps.ADD everywhere except for ASTs in tests.
WIP: neatly remove SUB from ASTs

### CODE REVIEW

**Comment by Fraudik** [comment]
Bounty completed: all BinaryOps.SUBs have been replaced

**Comment by Fraudik** [comment]
About the github-actions bot message: it's a bit strange because this branch is actually up-to-date with master

**Comment by Fraudik** [comment]
I think that in the `tensor.py` it can be reduced to just `a + (-b)` since the `add` function is defined above.
But not completely sure, this is at the discretion of the reviewers

**Comment by Fraudik** [comment]
Not sure if I need to mention that I took this task from the bounties table (to lock it there, maybe).
Sorry if I missed anything, this is my first time.

**Comment by geohot** [comment]
Bounty awarded to #4977

**Comment by Fraudik** [comment]
> Bounty awarded to #4977

Hello, may I ask a couple of questions about the bounty system? The Discord link on the site is not working.

I don’t understand the principle of issuing a bounty; the table indicates that when a WIP pull request is created, the task is locked. However, one of the pull requests listed has been around for four days and had its first review three days ago. The final pull request with bounty was also opened three days ago. However, the day before yesterday the task was free.
If another principle of the bounty system is used: distribution to the first person to complete it, then the final pull request with bounty completed its similar changes later than mine. Now I have checked, it turns out that my pull request completely closes the task and, in addition, refactors one test instead of deleting it (this is not to claim that one pull request is better or worse than another).

This does not look like a transparent bounty system, neither with a first pull request completely closing the task until the task is locked without a bounty, nor with a pull request in development and the status of the task as free. I came on a recommendation to try to contribute to the bounty system, but in the end I just lost several hours of responsible work. Luckily this is not one of the more difficult tasks.

**Comment by chenyuxyz** [comment]
We discussed this topic in discord, which link does not work?

In this case, I have reviewed every change when there are submitted. I only put review comment to the ones that I think are mergeable, and locked the bounty with a minor comment. For example, this pr is not mergeable, due to reasons that already discussed in the previous IDIV bounty.

**Comment by Fraudik** [comment]
image
This one, https://discord.com/invite/ZjZadyC7PK

**Comment by Fraudik** [comment]
I did not participate in IDIV bounty. And as far as I see this PR have same changes except for test_neg_fold test - without any commentary to it.

**Comment by chenyuxyz** [comment]
I have explained my position. If you still cannot tell the difference and what my comment for this pr would be, I can only say I picked the one that the author saw the difference. This is my last comment on this topic

**Pull request closed without merging**
