### PR TITLE
Raise exception if MTLCommandBuffer fails

### PR DESCRIPTION
**Pull request by uuuvn**
Sometimes MTLCommandBuffer fails silently and just doesn't update output Buffer, which is quite bad. There's multiple issues that lead to metal flakiness, this is one of them.

Fixes https://discord.com/channels/1068976834382925865/1069001075828469790/1189831398975094804

### CODE REVIEW

**Comment by geohot** [comment]
Good find!

`Exception` is a generic class, `RuntimeError` is probably a better choice.

Is there any way to test that this exception triggers.

**Comment by uuuvn** [comment]
> Good find!

I'm sure there is a lot more places where error checks are missing, so pls don't merge yet - will add them tomorrow
At least [one](https://discord.com/channels/1068976834382925865/1069001075828469790/1209967358966235296) exists for sure in GPU backend.

> `Exception` is a generic class, `RuntimeError` is probably a better choice.

I'm new to python, fixed.

> Is there any way to test that this exception triggers.

```python
# https://discord.com/channels/1068976834382925865/1069001075828469790/1189831398975094804
from tinygrad import Tensor

# force a long loop in subsequent kernels. seems to start failing at ~1e6 for me but gets consistent as we increase
N = int(1e8) + 1
ones = Tensor.ones((N,)).contiguous()

a = ones.mean().item()
print(f"{a=}") # ends up being 0.0 on gpu backends... possible silent metal fail?

intermediate = Tensor(3.14159).item() # eval any tensor with same shape
print(f"{intermediate=}")

b = ones.mean().item()
print(f"{b=}") # gets same val as intermediate when LRUAllocator is enabled

assert a == b
```
Sometimes (+- 1 in 10) fails on my 32gb m1 max, i guess it's running out of ram or something:
```
(.venv) [user@macbook ~/src/tinygrad]% python fun2.py
a=0.16777215898036957
intermediate=3.141590118408203
Traceback (most recent call last):
  File "/Users/user/src/tinygrad/fun2.py", line 13, in <module>
    b = ones.mean().item()
        ^^^^^^^^^^^^^^^^^^
  File "/Users/user/src/tinygrad/tinygrad/tensor.py", line 168, in item
    return self._data().cast(self.dtype.fmt)[0]
           ^^^^^^^^^^^^
  File "/Users/user/src/tinygrad/tinygrad/tensor.py", line 159, in _data
    return cast(Buffer, t.cast(t.dtype.scalar()).contiguous().realize().lazydata.base.realized).as_buffer()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/src/tinygrad/tinygrad/device.py", line 95, in as_buffer
    return self.copyout(memoryview(bytearray(self.size*self.dtype.itemsize)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/src/tinygrad/tinygrad/device.py", line 104, in copyout
    self.allocator.copyout(mv, self._buf)
  File "/Users/user/src/tinygrad/tinygrad/runtime/ops_metal.py", line 81, in copyout
    def copyout(self, dest:memoryview, src:Any): dest[:] = self.as_buffer(src)
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/src/tinygrad/tinygrad/runtime/ops_metal.py", line 78, in as_buffer
    self.device.synchronize()
  File "/Users/user/src/tinygrad/tinygrad/runtime/ops_metal.py", line 96, in synchronize
    raise RuntimeError(error)
RuntimeError: Error Domain=MTLCommandBufferErrorDomain Code=1 "Internal Error (0000000e:Internal Error)" UserInfo={NSLocalizedDescription=Internal Error (0000000e:Internal Error), NSUnderlyingError=0x116e22690 {Error Domain=IOGPUCommandQueueErrorDomain Code=14 "(null)"}}
```
```

**Comment by uuuvn** [comment]
Ready to merge, will make separate PR for GPU backend

**Comment by nimlgen** [comment]
Maybe add this check to metal graph as well?

**Comment by uuuvn** [comment]
> Maybe add this check to metal graph as well?

Added, thanks

**Pull request merged**
