### PR TITLE
rewrite default arg

### PR DESCRIPTION
**Pull request by DKormann**
slight simplification and only run once

### CODE REVIEW

**Review by Qazalin — COMMENTED** [review]
hmm does this make ptx faster?

**Comment by DKormann** [comment]
i dont know. Also its not passing ptx and i have no idea why it shouldn't really make a difference

**Comment by Qazalin** [comment]
it's applying a bad rewrite rule?

**Comment by DKormann** [comment]
i have no why its failing it should apply any different rules at all

**Pull request closed without merging**
