### PR TITLE
remove CAST_BEFORE_VIEW

### PR DESCRIPTION
**Pull request by chenyuxyz**
testing perf, also this might have issue with assign?

### CODE REVIEW

**Comment by chenyuxyz** [comment]
@chaosagent do you still want this? I don't see perf impact on benchmark so prefer to remove this unless there's big perf gain

**Comment by chaosagent** [comment]
I am OK with removing. I think you will see perf regression on BEAM=2 convolution backwards. Current master doesn't trigger TC that much anyways. I have an alternative approach for that.

**Comment by chenyuxyz** [comment]
okay let me BEAM=2 resent on master too

**Comment by chaosagent** [comment]
oh also, check memory usage. i think this saved some memory too.

**Comment by chenyuxyz** [comment]
`HSA=1 DEFAULT_FLOAT=HALF WARMUP_EPOCHS=2 BS=768 GPUS=6 BENCHMARK=10 MODEL=resnet python3 examples/mlperf/model_train.py` uses ~87.4GB on master and this branch so no memory diff.

**Comment by chenyuxyz** [comment]
both this pr and master have 430ms step time with default changed to HALF. i think it's safe to delete this.

**Comment by chaosagent** [comment]
Sounds good!

**Pull request merged**
