### PR TITLE
[WIP] Storm Atari100K Implementation

### PR DESCRIPTION
**Pull request by reddyn12**
Reproducing this paper: https://arxiv.org/abs/2310.09615
With torch code: https://github.com/weipu-zhang/STORM

Successfully trained torch implementation on MsPacman in 5 hours to expected score.

This is a pure translation of the source code for the paper.

### CODE REVIEW

**Comment by reddyn12** [comment]
Files Left:

- [ ] world_models
- [ ] functions_losses
- [ ] attention_blocks
- [ ] transformer_model
- [ ] agents
- [ ] eval
- [ ] train

**Comment by reddyn12** [comment]
Mostly done, need to figure out how to integrate optimizer properly and load/save model checkpoints

**Comment by geohot** [comment]
This is not the way. I want a clean tinygrad first reimplementation for this bounty, not tons of copy paste

**Comment by reddyn12** [comment]
Clean as in single file or no commented code? Cuz I'm still translating the code. Should I not put a draft until I can get it training?

**Comment by reddyn12** [comment]
@geohot

**Pull request closed without merging**
