### PR TITLE
UNet-3D Training

### PR DESCRIPTION
**Pull request by gml16**
This PR builds on top of #863 (and thanks to the help of @terafo).

Changes made by #863:
- Implement iterator for training set
- Implement transformations
- Implement dice cross entropy loss

Changes from this PR:
- Support batch size > 1
- Implement LR warmup
- Train the model
  - Big caveat that with my 4GB GPU I can only train with a smaller RoI than the benchmark. Thus, I am unable to check whether the required quality of the model is reached (goal is 0.908 Mean DICE score).

Feedback is more than welcome :)

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                         1               1
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by gml16** [comment]
Thank you, that makes sense. I will be away for some time so the PR will be stale. Hopefully this work in progress can help someone else.

**Comment by wozeparrot** [comment]
Closing due to no progress in a week.

**Comment by Max-We** [comment]
I also worked on this bounty, but had the same memory issue. Leaving the following here in case it helps someone else.

Tinygrad has bad memory usage, at least when being compared to PyTorch. Consider the following example

```
import torch
import torch.nn as nn

# Assuming input tensor shape is (batch_size, channels, depth, height, width)
input_tensor = torch.randn((1, 32, 128, 128, 128), dtype=torch.float32)

# Define 3D convolution layer
conv = nn.Conv3d(in_channels=32, out_channels=32, kernel_size=(3, 3, 3), padding=(1, 1, 1))

# Apply convolution
conv_out = conv(input_tensor)

# Print the result
print(conv_out.shape)
```

On a CPU machine with 12 GB RAM (Google Colab) this works great in PyTorch, but the Tinygrad equivalent runs out of memory.

With small operations this is ok, but when training UNet3D you'll have to do larger convolutions which require unreasonable amounts of RAM (compared to PyTorch).

**Pull request closed without merging**
