### PR TITLE
Refactor metal tc wmma kernel rendering

### PR DESCRIPTION
**Pull request by ignaciosica**
image

Can't use cleaner `simdgroup_load` instruction as inputs are in thread memory. The method requires source to be either in device memory or threadgroup memory. Same for `simdgroup_store` instruction. (so stuck with `mat_a.thread_elements()[0] = a[0];`)

I know right now low LOC are a priority but I couldn't make it more readable without those extra lines. (It could be shortened with shorter variables names but I think conceptually is a good refactor)

**Generated wmma kernel**

``` c
float2 __WMMA_8_8_8_half_float(half2 a, half2 b, float2 c) {
  simdgroup_half8x8 mat_a, mat_b; simdgroup_float8x8 mat_c;
  mat_a.thread_elements()[0] = a[0];
  mat_a.thread_elements()[1] = a[1];
  mat_b.thread_elements()[0] = b[0];
  mat_b.thread_elements()[1] = b[1];
  mat_c.thread_elements()[0] = c[0];
  mat_c.thread_elements()[1] = c[1];
  simdgroup_multiply_accumulate(mat_c, mat_a, mat_b, mat_c);
  return float2(mat_c.thread_elements()[0], mat_c.thread_elements()[1]);
}
```

~Forced to use `os.linesep` instead of `\n` as CI throws `SyntaxError: f-string expression part cannot include a backslash`. Worked perfectly fine with `\n` in local setup.~ Fixed with workaround with local var

### CODE REVIEW

**Comment by geohot** [comment]
LOC is not a priority! Always readability over LOC

**Comment by Qazalin** [comment]
can you use walrus if you wanna alias arg idxs?

**Comment by ignaciosica** [comment]
``` c
float2 __WMMA_8_8_8_half_float(half2 a, half2 b, float2 c){
  simdgroup_half8x8 mat_a, mat_b; simdgroup_float8x8 mat_c;
  mat_a.thread_elements()[0] = a[0]; mat_b.thread_elements()[0] = b[0]; mat_c.thread_elements()[0] = c[0];
  mat_a.thread_elements()[1] = a[1]; mat_b.thread_elements()[1] = b[1]; mat_c.thread_elements()[1] = c[1];
  simdgroup_multiply_accumulate(mat_c, mat_a, mat_b, mat_c);
  return float2(mat_c.thread_elements()[0], mat_c.thread_elements()[1]);
}
```

generated kernel

**Comment by ignaciosica** [comment]
> can you use walrus if you wanna alias arg idxs? or destructure arg later. either way multiple variable assignments in one line is even more unreadable.

thanks for your feedback!

**Pull request merged**
