### PR TITLE
make self referential realize fast

### PR DESCRIPTION
**Pull request by DKormann**
continuation of #2278 now I want to make realize fast too

### CODE REVIEW

**Comment by geohot** [comment]
I have no idea how to even begin reviewing this. Can this be done with a negative line change? Possible to use functools.lru_cache instead of an explicit dictionary?

**Comment by DKormann** [comment]
i was trying. the problem is you don't need to cache the whole function arguments. I could do a couple less lines and possibly rlu_cache buy wrapping the whole ast_parse function. the diff is gonna be little bigger though

**Comment by DKormann** [comment]
the caching itself is gonna add some lines regardless the only way I think to have neg line diff is by reducing lines elsewhere basically what i did last PR

**Comment by DKormann** [comment]
ah wait i got something

**Comment by DKormann** [comment]
I squached a couple simple lines up in the file maybe thats not helpful
I can make the ast_parse itself somewhat smaller but not much

**Comment by DKormann** [comment]
linearizer change: i put all unhashable args into linearizer state. and offs i just pass the index and retrieve the offset when needed in ast_parse

**Pull request closed without merging**
