### PR TITLE
perf: fully cached shapetracker methods

### PR DESCRIPTION
**Pull request by roelofvandijk**
Not necessarily for merge, mainly to show @chaosagent.

Kept the external shapetracker interfaces, this will be a bit faster still (and way less lines) if those are rewritten in lazy etc.

LLama:

Before
```
codegen         mean runtime:  238.50ms, runs:   293.03,  224.61,  220.70,  243.19,  222.52,  229.64,  224.70,  224.93,  223.50,  278.18
methodcache     mean runtime:  212.00ms, runs:   189.93,  210.70,  216.78,  207.13,  207.24,  235.79,  232.11,  211.25,  203.36,  205.74
profile         mean runtime: 1082.35ms, runs:  1013.85, 1055.22, 1052.08, 1030.62, 1129.18, 1271.14, 1087.14, 1049.98, 1069.15, 1065.08
```

After
```
codegen         mean runtime:  211.45ms, runs:   267.03,  200.79,  203.35,  192.95,  193.02,  194.79,  262.67,  202.87,  197.08,  199.89
methodcache     mean runtime:  185.16ms, runs:   162.61,  181.66,  190.57,  176.26,  176.46,  178.97,  189.02,  240.30,  180.14,  175.58
profile         mean runtime:  860.25ms, runs:   789.98,  791.11,  792.08,  841.22,  948.47,  920.92,  902.69,  857.30,  887.20,  871.53
```

CIFAR
Before
```
 PYTHONPATH=. STEPS=5 WINO=1 python3.11 -O examples/hlb_cifar10.py
  0 34880.25 ms run, 34880.09 ms python,    0.16 ms CL, 1187.23 loss, 0.002563 LR, 0.84 GB used,     13.61 GFLOPS
  1 8163.48 ms run, 8163.33 ms python,    0.15 ms CL, 1187.59 loss, 0.002577 LR, 4.39 GB used,     57.37 GFLOPS
  2  218.71 ms run,    8.44 ms python,  210.27 ms CL, 2760.15 loss, 0.001741 LR, 4.39 GB used,   2141.32 GFLOPS
  3  222.95 ms run,    8.38 ms python,  214.57 ms CL, 2844.72 loss, 0.000906 LR, 4.39 GB used,   2100.54 GFLOPS
  4  228.68 ms run,    8.68 ms python,  220.00 ms CL, 2118.59 loss, 0.000070 LR, 4.39 GB used,   2047.96 GFLOPS
```

After
```
  0 28633.72 ms run, 28633.58 ms python,    0.14 ms CL, 1187.23 loss, 0.002563 LR, 0.84 GB used,     16.58 GFLOPS
  1 7006.18 ms run, 7006.04 ms python,    0.14 ms CL, 1187.59 loss, 0.002577 LR, 4.39 GB used,     66.84 GFLOPS
  2  218.80 ms run,    8.20 ms python,  210.59 ms CL, 2760.15 loss, 0.001741 LR, 4.39 GB used,   2140.45 GFLOPS
  3  224.61 ms run,   12.93 ms python,  211.67 ms CL, 2844.72 loss, 0.000906 LR, 4.39 GB used,   2085.09 GFLOPS
  4  227.51 ms run,   11.21 ms python,  216.30 ms CL, 2118.59 loss, 0.000070 LR, 4.39 GB used,   2058.45 GFLOPS
```

### CODE REVIEW

**Comment by roelofvandijk** [comment]
@geohot This is ~20% for llama and winograd, and probably most other things. Only caching, no functional changes. The diff is shot in this MR - should I split it up into parts? I can reduce the linecount delta as well, but that requires changing the Shapetracker interface (&tests), which I'd prefer to do in a separate MR. A next simplification would be to make the Shapetracker a namedtuple, but that's also nice as a separate MR.

**Comment by geohot** [comment]
Does this increase/reduce complexity/readability?

**Comment by geohot** [comment]
My proposal would be to split this into two files, view.py and shapetracker.py, with an eye toward deleting shapetracker.py

**Comment by roelofvandijk** [comment]
> Does this increase readability? 

Yes, I think so. By only passing what is needed to each function, it becomes clear that the whole Shapetracker class is just a pretty interface. Also, all caches work better.

E.g., these six methods. 
```
  def reshape(self, new_shape): 
    if self.views[-1].shape == new_shape: return self
    self.views = reshape(self.views, new_shape)
    return self
  def expand(self, new_shape):
    self.views = self.views[:-1] + (expand(self.views[-1], new_shape),)
    return self
  def shrink(self, arg):
    self.views = self.views[:-1] + (shrink(self.views[-1], arg),)
    return self
  def stride(self, mul):
    self.views = self.views[:-1] + (stride(self.views[-1], mul),)
    return self
  def permute(self, axis):
    self.views = self.views[:-1] + (permute(self.views[-1], axis),)
    return self
  def pad(self, arg):
    self.views = self.views[:-1] + (pad(self.views[-1], arg),)
    return self
```

> Layer of indirection

The extra layer of indirection is only needed to keep the interface of the ShapeTracker class the same (tests & usages in lazy), it's also a matter of taste, e.g. which of these you prefer:
`view.expr_idxs(idxs)`
`expr_idxs(view, idxs)`

The second one is way better cacheable. You seem to prefer the first one. If the speed matters, extra layer it is.

Is it focused on readability? No. I just wanted to create an example of how to fully cache all functions here without touching any other files.

> Removing shapetracker & creating view.py: 

That's absolutely the way to go. I have a working branch where each buffer only has a view of tuples (instead of a shapetracker). The five methods (except for `reshape`) that modify a single view could move to the view class right away, but there is something to be said for keeping the set of 6 together.

A possible upgrade path would be (this is what I did):

* this (making the methods on the views transparent)
* `Shapetracker(NamedTuple)` -> becomes immutable, needs to be re-created on change, which forces some changes in `lazy` etc.
* remove the ShapeTracker wrapper, each buffer has tuples of views:
`def create_lazybuffer(device:str, st:Tuple[View], optype:OpType, ... `

What I find tricky is how to split it up into MRs. I can create a MR that deletes the shapetracker right away, but a gradual refactor might be wiser.

**Comment by roelofvandijk** [comment]
Consolidated the reshape functions,

```
  0 24079.56 ms run, 24079.43 ms python,    0.14 ms CL, 1187.23 loss, 0.002563 LR, 0.84 GB used,     19.71 GFLOPS
  1 7208.32 ms run, 7208.19 ms python,    0.12 ms CL, 1187.59 loss, 0.002577 LR, 4.39 GB used,     64.97 GFLOPS
  2  217.81 ms run,    5.92 ms python,  211.88 ms CL, 2760.15 loss, 0.001741 LR, 4.39 GB used,   2150.18 GFLOPS
  3  224.96 ms run,   11.24 ms python,  213.72 ms CL, 2844.72 loss, 0.000906 LR, 4.39 GB used,   2081.85 GFLOPS
  4  221.21 ms run,    7.85 ms python,  213.36 ms CL, 2118.59 loss, 0.000070 LR, 4.39 GB used,   2117.06 GFLOPS
```

That's 30%.

**Pull request closed without merging**
