### PR TITLE
skip hashing unrealized children

### PR DESCRIPTION
**Pull request by Qazalin**
image

### CODE REVIEW

**Comment by chenyuxyz** [comment]
cool! can you add some comments about what group/ungroup is supposed to track and a regression test?

**Comment by Qazalin** [comment]
oh if you remove ungroup everything in test_schedule breaks.
I think for the timing regression we need some sort of process replay for performance.

**Comment by chenyuxyz** [comment]
some proxy tests that shows the root cause of this issue would be nice, i don't quite understand where the slow down was coming from (like is it kernel orders, or some redundant src or something else?)

**Comment by Qazalin** [comment]
It's because I made 3 O(n) operations:
https://github.com/tinygrad/tinygrad/pull/5717/files#diff-120c8f826d67db123ecd7a1de1d0af40b894be9c3c3a27655819b4cd2689c581L255-L257
into 1 O(1) and 1 O(n) on a smaller n. Both contributed to this.

**Comment by Qazalin** [comment]
could isolate this down to the hashing for a ReduceOp with a large graph.

**Comment by chenyuxyz** [comment]
interesting, so we still have python scheduling in resnet steps

**Comment by Qazalin** [comment]
That extra hash isn't even required with the new abstractions in _get_isolated_children because we only care about a realized child.
An unrealized ReduceOp child doesn't need to get hashed directly.

**Comment by Qazalin** [comment]
closing for staleness, I'll revisit this once indexing is complete.

**Pull request closed without merging**
