### PR TITLE
[WIP]: Tensorboard Support

### PR DESCRIPTION
**Pull request by dosier**
### (Maybe move this to a separate repo?)

Taking heavy inspiration from PyTorch's implementation. 

General TODO:
- [ ] pooled writers (benchmark, is this needed?)
- [ ] more extensive tests (compare to pytorch for various outputs)
- [ ] concise and example-rich docs 
- [ ] variety of code examples for existing models

Summary types (crossed-out ones will not be implemented):
- [x] add_hparams
- [x] add_scalar
- [x] add_scalars
- [x] add_histogram
- [x] ~~add_histogram_raw~~
- [x] add_image
- [x] add_images
- [ ] add_image_with_boxes
- [ ] add_figure
- [ ] add_video
- [ ] add_audio
- [x] add_text
- [x] ~~add_onnx_graph~~
- [ ] add_graph **(made a start with this)**
- [ ] add_embedding
- [ ] add_pr_curve
- [x] ~~add_pr_curve_raw~~
- [x] ~~add_custom_scalars_multilinechart~~
- [x] ~~add_custom_scalars_marginchart~~
- [x] ~~add_custom_scalars~~
- [x] ~~add_mesh~~

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/assembly_rdna.py          1               1
tinygrad/codegen/cstyle.py                 0               1
tinygrad/codegen/llvmir.py                 1               5
tinygrad/helpers.py                        1               2
tinygrad/mlops.py                         15               3
tinygrad/runtime/lib.py                    1               1
tinygrad/runtime/ops_gpu.py                1               2
tinygrad/runtime/ops_metal.py              1               2
tinygrad/runtime/ops_torch.py              1               1
tinygrad/tensor.py                         1               2
------------------------------------------------------------
total                                     23              20
------------------------------------------------------------
lines added in the tinygrad folder: 3
```

**Comment by dosier** [comment]
> Changes made in `tinygrad/`:
> 
> ```
> ------------------------------------------------------------
> files                             insertions       deletions
> ------------------------------------------------------------
> tinygrad/codegen/assembly_rdna.py          1               1
> tinygrad/codegen/cstyle.py                 0               1
> tinygrad/codegen/llvmir.py                 1               5
> tinygrad/helpers.py                        1               2
> tinygrad/mlops.py                         15               3
> tinygrad/runtime/lib.py                    1               1
> tinygrad/runtime/ops_gpu.py                1               2
> tinygrad/runtime/ops_metal.py              1               2
> tinygrad/runtime/ops_torch.py              1               1
> tinygrad/tensor.py                         1               2
> ------------------------------------------------------------
> total                                     23              20
> ------------------------------------------------------------
> lines added in the tinygrad folder: 3
> ```
This change log is wrong.

I made a small error when updating the PR where it included the commits already on master for this PR's changelog for some reason. Fixed it by switching the base to something else and back to master.

**Comment by dosier** [comment]
@geohot should I just make my own repo, or are u planning to make a tinygrad github org where this can be posted under?

(context: in discord call it was said this should be moved to a separate repo)

**Comment by geohot** [comment]
Yea, I'd put this in your own repo, not sure it belongs in core tinygrad.

**Pull request closed without merging**
