### PR TITLE
O(1) VALIDHACKS

### PR DESCRIPTION
**Pull request by ZenginU**
half disaster but low key grasped the logic

Should I seperate the symbolic part to seperate PR ?

### CODE REVIEW

**Comment by geohot** [comment]
Looking good! Do you need any more tests?

**Comment by ZenginU** [comment]
To be honest I do not know how to test this without fuzzer like logic, also very last part is based solely on trial and error which I am not proud of. 
There are couple of assumption also

**Comment by geohot** [comment]
Hmm, why did tests change?

**Comment by ZenginU** [comment]
> Hmm, why did tests change? Were they wrong to begin with?

They were not wrong, I made the SumNode use implicit division. 

For example,
a*4 < 16 -> a < 4.
Is now implicit.

**Comment by geohot** [comment]
Can you add more tests? What does `a*4 < 15` do?

**Comment by ZenginU** [comment]
> Can you add more tests? What does `a*4 < 15` do?

Okay, I will add more tests. I can put that symbolic in to another PR if you want. It will not break this PR.

Also, a*4 < 15 stays same as their gcd is 1.

**Comment by geohot** [comment]
Eh, it's simple enough to read.

Isn't `a*4 < 15` the same as `a < 4`?

**Comment by ZenginU** [comment]
> Eh, it's simple enough to read.
> 
> 
> 
> Isn't `a*4 < 15` the same as `a < 4`?

Yes it is true but I have not changed the logic in Sumnode.__lt__ . If you want I can work on that as well. This symbolic change is more like using existing implementation.

**Comment by geohot** [comment]
It's fine for now, let's just add more tests and I think it's good

**Comment by ZenginU** [comment]
> It's fine for now, let's just add more tests and I think it's good

Added test for SumNode folding but any ideas how to test the to_image_idx ? I believe we need fuzzer like approach.

**Comment by geohot** [comment]
Yea, fuzzing would be great. Going to merge this for now, I don't fully understand it but I understand the symbolic change

**Pull request merged**
