### PR TITLE
add outbufs info to CompiledASTRunner

### PR DESCRIPTION
**Pull request by Qazalin**
This is a prereq for multioutput since both JITRunner and HSAGraph assume rawbufs[0] is the only output.

### CODE REVIEW

**Comment by nimlgen** [comment]
We can discuss that, but I think that CompiledASTRunner should have info about output buffers or kernels. This info is also needed to build hsa graph deps

**Comment by Qazalin** [comment]
The approach here is to do this at `exec` because that is when the `Buffer`s for the outputs are created.
@nimlgen does the hsa graph need the info before exec is called?

**Comment by nimlgen** [comment]
I thought maybe CompiledASTRunner can have bitmask/positions of rawbufs which are used as output? hsagraph needs to know which buffers of `CompiledASTRunner` are read-only to build an optimal dependency chain.

**Comment by geohot** [comment]
Hmm, I don't like adding more variables here. What is this more generically? Maybe something like types on all the buffers.

**Pull request merged**
