### PR TITLE
type_verify(big_graph.toposort) [pr]

### PR DESCRIPTION
**Pull request by Qazalin**
1. shape change bitcast can have "implicit" movement ops, this is probably fine?
2. the root cause of GC asserts is toposort's lru_cache:
image

### CODE REVIEW

**Comment by geohot** [comment]
That doesn't make sense, re: the toposort. That cache should only be in scope for the function.

**Comment by Qazalin** [comment]
image
looks like I need to manually clear a local_cache?

**Comment by geohot** [comment]
Do you really need the del?

**Comment by Qazalin** [comment]
GC root cause is closures - https://github.com/tinygrad/tinygrad/pull/8261.

I'm gonna keep the BUFFER_VIEW weirdness as-is for now, it can change dtype, it can change shape. It's an untasteful op.

**Comment by Qazalin** [comment]
Closing in favour of 8311

**Pull request closed without merging**
