### PR TITLE
remove NOp.var() with _nop constructor [run_process_replay]

### PR DESCRIPTION
**Pull request by DKormann**

### CODE REVIEW

**Comment by DKormann** [comment]
with _nop constructor we can
- [x] remove .var() 
- [ ] remove NOp.cvar NOp.const NOp.name ...
- [ ] completely remove Upat from
- [ ] fold class NOp back into UOp (if this is desirable)
- [ ] unify UPat.__init__ with UOp.compile()

**Comment by DKormann** [comment]
will continue on monday

**Comment by geohot** [comment]
I like this less than `NOp.var`, you have to import two things

**Comment by DKormann** [comment]
okay but will be able to remove UPat from import in exchange

**Comment by geohot** [comment]
I'm pretty happy with where it is now. If there's some simple syntax to use less `UPat` I'm open to it, but this is a big change

**Pull request closed without merging**
