### PR TITLE
Fix gpt2 example

### PR DESCRIPTION
**Pull request by roryclear**
gpt2 example gives different outputs with JIT since [c100f3d](https://github.com/tinygrad/tinygrad/commit/c100f3d40618ff7f19ded78eee89d8a0dc253135).

Outputs on master:
master output

Outputs with change:
output after change

### CODE REVIEW

**Comment by geohot** [comment]
Hmm, why?

**Comment by roryclear** [comment]
I think because rand doesn't work in JIT after rand has been called and not realized. Not sure why that is yet but I have a repro here:
`from tinygrad import Tensor, TinyJit
x = Tensor.rand(1)
#x.realize()
r = TinyJit(lambda: Tensor.rand(1))
for _ in range(5):
    print(r().numpy())`

**Comment by roryclear** [comment]
and that behaviour with threefry starts when realize was removed from it [7703e7b](https://github.com/tinygrad/tinygrad/commit/97d7082).

**Comment by geohot** [comment]
Hmm, that repro is interesting. Can you add a failing test?

**Comment by roryclear** [comment]
> Hmm, that repro is interesting. Can you add a failing test?

Sure, I just added one

**Comment by wozeparrot** [comment]
Should be fixed with #6869

**Pull request closed without merging**
