### PR TITLE
added beautiful fashion mnist and example

### PR DESCRIPTION
**Pull request by Kinvert**
People learning tinygrad might want a step in difficulty between MNIST and CIFAR-10.

This is what I personally did here to keep learning tinygrad. Might be useful to others. Up to you guys if you want something like this added.

If this is something you might want, please have a look at datasets.py. There is a bit of redundancy as it is, but I wasn't sure if you'd want me changing up something that was already written here. This is my first PR so I don't know your guy's preferences for how things are done yet.

### CODE REVIEW

**Comment by Kinvert** [comment]
Sorry, looks like I forgot pre-commit hooks after a new clone.

**Comment by Kinvert** [comment]
Please let me know if you want the datasets.py refactor.

**Comment by geohot** [comment]
Tons of copy paste, this whole PR should be 4 lines

**Comment by Kinvert** [comment]
> Tons of copy paste, this whole PR should be 4 lines

Now 5 lines. Doesn't change functionality of old programs that use the mnist() function, and adds the ability to use Fashion MNIST.

**Pull request merged**
