### PR TITLE
opencl, intel/radeon  

### PR DESCRIPTION
**Pull request by waifairer**
Here is additional information about the unusual failures on Metals on the 2018/2019 Intel+Radeon mac stack. I'm lucky enough to be using one of those machines. My goal is to filter some of the noise that's currently in the GH-1019 issue. There are a few conflicting reports in that issue and also I think some distracting assumptions were made. At first, I am targeting the test case with values that disappear during the cast from half to char.

Here's what I know. There's a decent amount of new information in this (not mentioned in the issue comments).

1. The issue only occurs on both tensors of size 4 and 8. The issue does not appear on tensors of size 16, 32 or 64. The issue does not occur on any non-multiple of 4.
2. The issue is intrinsically tied to the following hand-coded optimization:
```
  # TODO: this is breaking the tests
  for splits in [4]:
    if k.upcasted == 0 and len(k.full_unupcasted_shape) > 0 and k.full_unupcasted_shape[-1] % splits == 0:
      k.shift_to(len(k.full_unupcasted_shape)-1, splits, insert_before=len(k.full_unupcasted_shape))
      k.upcast()
```
@geohot appears to know that this is the segment causing the issue from the comment. Specifically, it's the _k.upcast()_ that causes us to fail _this test_. Commenting this single line ` k.upcast()` causes the test cases included in this MR to pass. 
3. I have captured the UOPS stack and prg for both the passing and failing cases. They're currently checked in as `information`.  Here's the skinny:

The failing range(4) case has the following opstack/prg:
```
====== failing, free upcast on, range(4) =======
UOps.DEFINE_GLOBAL  :                           []                               ('data0', dtypes.unsigned char)
UOps.DEFINE_GLOBAL  :                           []                               ('data1', dtypes.half)
UOps.LOOP           :                           []                               ([], 'global')
UOps.LOOP           :                           []                               ([], 'local')
UOps.LOAD           : <val1_0:float4:None>      []                               MemOp(name='data1', idx=<0>, local=False, memory_dtype=dtypes.half, valid=<1>, invalid_value=0.0)
UOps.STORE          :                           [<val1_0:float4:0>]              MemOp(name='data0', idx=<0>, local=False, memory_dtype=dtypes.unsigned char, valid=<1>, invalid_value=0.0)
UOps.STORE          :                           [<val1_0:float4:1>]              MemOp(name='data0', idx=<1>, local=False, memory_dtype=dtypes.unsigned char, valid=<1>, invalid_value=0.0)
UOps.STORE          :                           [<val1_0:float4:2>]              MemOp(name='data0', idx=<2>, local=False, memory_dtype=dtypes.unsigned char, valid=<1>, invalid_value=0.0)
UOps.STORE          :                           [<val1_0:float4:3>]              MemOp(name='data0', idx=<3>, local=False, memory_dtype=dtypes.unsigned char, valid=<1>, invalid_value=0.0)
UOps.ENDLOOP        :                           []                               ([], 'global+local')
#pragma OPENCL EXTENSION cl_khr_fp16 : enable
__kernel void E_4(__global unsigned char* data0, const __global half* data1) {
    float4 val1_0 = vload_half4(0, data1+0);
    data0[0] = val1_0.x;
    data0[1] = val1_0.y;
    data0[2] = val1_0.z;
    data0[3] = val1_0.w;
   /* global+local */
}
``` 

The passing range(4) case (this entire `free upcast` optimization disabled) that only uses scalars.

```
====== passing, no upcast, range(4) =======
UOps.DEFINE_GLOBAL  :                           []                               ('data0', dtypes.unsigned char)
UOps.DEFINE_GLOBAL  :                           []                               ('data1', dtypes.half)
UOps.LOOP           :                           []                               ([], 'global')
UOps.LOOP           :                           []                               ([<lidx0[0-3]>], 'local')
UOps.LOAD           : <val1_0>                  []                               MemOp(name='data1', idx=<lidx0[0-3]>, local=False, memory_dtype=dtypes.half, valid=<1>, invalid_value=0.0)
UOps.STORE          :                           [<val1_0>]                       MemOp(name='data0', idx=<lidx0[0-3]>, local=False, memory_dtype=dtypes.unsigned char, valid=<1>, invalid_value=0.0)
UOps.ENDLOOP        :                           []                               ([<lidx0[0-3]>], 'global+local')
#pragma OPENCL EXTENSION cl_khr_fp16 : enable
__kernel void E_4(__global unsigned char* data0, const __global half* data1) {
  { int lidx0 = get_local_id(0);  /* 4 */
    float val1_0 = vload_half(0, data1+lidx0);
    data0[lidx0] = val1_0;
  } /* global+local */
}
```

There's additional kernels/prgs included in the information document. I have also captured the passing/failing kernels for the range(8) case, as well as both of the passing kernels for the range(12) case, `free upcast` both on and off. The failing range(8) kernels and the passing range(12) kernels look nearly identical, but there are a couple of differences:
```
===== failing, free upcast on,  range(8) =======
#pragma OPENCL EXTENSION cl_khr_fp16 : enable
__kernel void E_2_4(__global unsigned char* data0, const __global half* data1) {
{ int gidx0 = get_group_id(0);  /* 2 */
    float4 val1_0 = vload_half4(0, data1+gidx0*4);
    data0[(gidx0*4)] = val1_0.x;
    data0[((gidx0*4)+1)] = val1_0.y;
    data0[((gidx0*4)+2)] = val1_0.z;
    data0[((gidx0*4)+3)] = val1_0.w;
  } /* global+local */
}
```
```
===== passing, free upcast on, range(12) =====
#pragma OPENCL EXTENSION cl_khr_fp16 : enable
__kernel void E_3_4(__global unsigned char* data0, const __global half* data1) {
  { int lidx0 = get_local_id(0);  /* 3 */
    float4 val1_0 = vload_half4(0, data1+lidx0*4);
    data0[(lidx0*4)] = val1_0.x;
    data0[((lidx0*4)+1)] = val1_0.y;
    data0[((lidx0*4)+2)] = val1_0.z;
    data0[((lidx0*4)+3)] = val1_0.w;
  } /* global+local */
```

This is what makes me think that the issue is occurring at write-time to data1, not at read-time. Another minor difference is that the failing case is using global/group indices rather than local indices -- I think that there's a reasonable possibility that the issue could be related to that (global vs local indices). I'd like to lock this bounty while I continue to debug.

### CODE REVIEW

**Comment by waifairer** [comment]
The next thing I'd like to try is disabling the global indices for the smaller (range(4)/range(8)) tensors and see if the issue goes away. If someone knows off the top of their head how to do this, I'd appreciate the tip, but otherwise I will figure it out.

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/failed.md                15               0
tinygrad/codegen/passing.md                7               0
tinygrad/lazy.py                          11               2
tinygrad/ops.py                            9               2
tinygrad/runtime/ops_cpu.py                6               2
tinygrad/runtime/ops_gpu.py                6               0
tinygrad/runtime/ops_metal.py              2               0
------------------------------------------------------------
total                                     56               6
------------------------------------------------------------
lines added in the tinygrad folder: 50
```

**Comment by waifairer** [comment]
Disabling the Intel GPU device makes it work fine (tests pass). For my machine, it should prefer the AMD GPU but that's a separate topic since it doesn't get us anywhere with the CI.

**Comment by waifairer** [comment]
This kernel is working (passing tests):
````
"""
    #pragma OPENCL EXTENSION cl_khr_fp16 : enable
    __kernel void E_2_4(__global unsigned char* data0, const __global half* data1) {
        int gidx0 = get_group_id(0);  /* 2 */

        float4 val1_0 = vload_half4(0, data1+gidx0*4);
        data0[(gidx0 * 4)] = val1_0.x;

        int val_z = val1_0.z;
        data0[(gidx0 * 4) + 1] = val1_0.y;
        data0[(gidx0 * 4) + 2] = val_z;

        data0[(gidx0 * 4) + 3] = val1_0.w;
    }
    """
```

**Comment by wozeparrot** [comment]
Can you try disassembling the bad kernels? I wonder if there is a miscompilation somewhere, tho that seems highly unlikely.

**Comment by waifairer** [comment]
@wozeparrot I think that might actually be the case. Here's something bizarre for you:

Passing (same as above):
```
    #pragma OPENCL EXTENSION cl_khr_fp16 : enable
    __kernel void E_2_4(__global unsigned char* data0, const __global half* data1) {
        int gidx0 = get_group_id(0);  /* 2 */

        float4 val1_0 = vload_half4(0, data1+gidx0*4);
        data0[(gidx0 * 4)] = val1_0.x;

        printf("data[%d] = (%f, %f, %f, %f)\\n", val1_0.x, val1_0.y, val1_0.z, val1_0.w);
        
        data0[(gidx0 * 4) + 1] = val1_0.y;
        int half_val_z = val1_0.z;
        data0[(gidx0 * 4) + 2] = half_val_z;

        data0[(gidx0 * 4) + 3] = val1_0.w;
    }
```


Failing:

```
    #pragma OPENCL EXTENSION cl_khr_fp16 : enable
    __kernel void E_2_4(__global unsigned char* data0, const __global half* data1) {
        int gidx0 = get_group_id(0);  /* 2 */

        float4 val1_0 = vload_half4(0, data1+gidx0*4);
        data0[(gidx0 * 4)] = val1_0.x;

        data0[(gidx0 * 4) + 1] = val1_0.y;
        int half_val_z = val1_0.z;
        data0[(gidx0 * 4) + 2] = half_val_z;

        data0[(gidx0 * 4) + 3] = val1_0.w;
    }
```

The only thing I changed is I removed the print. I think that definitely points to a miscompilation. I'll working on disassembling both tomorrow.

**Comment by waifairer** [comment]
I've double-checked this. It's real.

passes
```
    #pragma OPENCL EXTENSION cl_khr_fp16 : enable
    __kernel void E_2_4(__global unsigned char* data0, const __global half* data1) {
        int gidx0 = get_group_id(0);  /* 2 */

        float4 val1_0 = vload_half4(0, data1+gidx0*4);
        data0[(gidx0 * 4)] = val1_0.x;

        printf("(%f, %f, %f, %f)\\n", val1_0.x, val1_0.y, val1_0.z, val1_0.w);
        
        data0[(gidx0 * 4) + 1] = val1_0.y;
        int half_val_z = val1_0.z;
        data0[(gidx0 * 4) + 2] = half_val_z;

        data0[(gidx0 * 4) + 3] = val1_0.w;
    }
```


fails
```
    #pragma OPENCL EXTENSION cl_khr_fp16 : enable
    __kernel void E_2_4(__global unsigned char* data0, const __global half* data1) {
        int gidx0 = get_group_id(0);  /* 2 */

        float4 val1_0 = vload_half4(0, data1+gidx0*4);
        data0[(gidx0 * 4)] = val1_0.x;
        
        data0[(gidx0 * 4) + 1] = val1_0.y;
        int half_val_z = val1_0.z;
        data0[(gidx0 * 4) + 2] = half_val_z;

        data0[(gidx0 * 4) + 3] = val1_0.w;
    }
```








Other interesting interactions:


```
    #pragma OPENCL EXTENSION cl_khr_fp16 : enable
    __kernel void E_2_4(__global unsigned char* data0, const __global half* data1) {
        int gidx0 = get_group_id(0);  /* 2 */

        float4 val1_0 = vload_half4(0, data1+gidx0*4);
        data0[(gidx0 * 4)] = val1_0.z;
        
        data0[(gidx0 * 4) + 1] = val1_0.z;
        data0[(gidx0 * 4) + 2] = val1_0.z;

        data0[(gidx0 * 4) + 3] = val1_0.z;
    }
```
`[2 2 2 2 6 6 6 6]`






```
    #pragma OPENCL EXTENSION cl_khr_fp16 : enable
    __kernel void E_2_4(__global unsigned char* data0, const __global half* data1) {
        int gidx0 = get_group_id(0);  /* 2 */

        float4 val1_0 = vload_half4(0, data1+gidx0*4);
        data0[(gidx0 * 4)] = val1_0.z;
        
        data0[(gidx0 * 4) + 1] = val1_0.w;
        data0[(gidx0 * 4) + 2] = val1_0.y;

        data0[(gidx0 * 4) + 3] = val1_0.x;
    }
```
`[2 0 1 0 6 0 5 4]`

**Comment by geohot** [comment]
I don't understand this PR. It doesn't look like something that should be merged.

**Pull request closed without merging**
