### PR TITLE
Fix TRANSCENDENTAL=2 fp64 sin

### PR DESCRIPTION
**Pull request by hikettei**
- fix fp64 sin
- ~~refactor on fp16 sin~~

### CODE REVIEW

**Comment by hikettei** [comment]
x=4993037481.0 this is where `e` reaches 33 and 32-e becomes -1, resulting in the wrong result.

**Comment by geohot** [comment]
Tests failing.

Also, now that it's UOps, you can use the syntactic sugar if you want. Like `a+b` just works.

**Comment by hikettei** [comment]
@chenyuxyz I have created a small patch for FP64 Sin.

- Changes:
    - [x] Fixed the constants in `frexp`.
    - [x] clean up `switch_over`.

- Current Status:
    - I have confirmed the operation for values up to `abs(x) <= 8589893635.0` and the maximum value of FP32.
    - To accurately approximate values beyond that and for FP64 values, I have to revise the algorithm.
        - To approximate the maximum value of FP64:
        - (1) about 200 LUTs are needed (currently 7)
        - (2) I have to combine two fp64 floats during reduction.
    - I will create a separate PR and work on it there. (requires 2~5 days I guess)

Lastly, I ran the benchmarks using [the same code as the previous PR]((https://github.com/tinygrad/tinygrad/pull/5187#issuecomment-2219465472)). There is no significant impact on the performance.

```
|CLANG|sin|float16|0.002801791997626424|0.002625082852318883|0.9369299557364563|
|CLANG|sin|float32|0.00519241695292294|0.005311832996085286|1.0229981614044157|
|CLANG|sin|float64|0.015657792100682855|0.015266457805410028|0.9750070576517771|
|CLANG|exp2|float16|0.0026565829757601023|0.002699499949812889|1.0161549533533796|
|CLANG|exp2|float32|0.005486250156536698|0.005420125089585781|0.9879471287192161|
|CLANG|exp2|float64|0.01519487495534122|0.015143084106966853|0.9965915581058361|
|CLANG|log2|float16|0.0026355842128396034|0.0024079999420791864|0.9136494027958927|
|CLANG|log2|float32|0.005251167109236121|0.005207458045333624|0.9916763144281547|
|CLANG|log2|float64|0.014625125098973513|0.015438209054991603|1.0555950086249284|
|LLVM|sin|float16|0.0035780000034719706|0.0035456670448184013|0.9909633989317511|
|LLVM|sin|float32|0.005999208893626928|0.005773874931037426|0.9624393871617175|
|LLVM|sin|float64|0.010934583144262433|0.011124040931463242|1.0173264755227747|
|LLVM|exp2|float16|0.0033195000141859055|0.0036641249898821115|1.1038183383712754|
|LLVM|exp2|float32|0.005877000046893954|0.0060153750237077475|1.0235451719771427|
|LLVM|exp2|float64|0.011352790985256433|0.01141087501309812|1.0051162773909181|
|LLVM|log2|float16|0.0035600000992417336|0.003672666847705841|1.0316479621694687|
|LLVM|log2|float32|0.006096167024224997|0.006102332845330238|1.001011425881335|
|LLVM|log2|float64|0.011243458138778806|0.011309916852042079|1.005910878347477|
```

**Comment by chenyuxyz** [comment]
can you add a regression test here https://github.com/tinygrad/tinygrad/blob/6e0a5230786d41eabe9dc9e593b05997d3a1da73/test/test_dtype_alu.py#L167

some fixed value that failed before and fixed by this pr

**Comment by chenyuxyz** [comment]
i added float64 to the test, it was not tested. some tests are failing now

**Pull request merged**
