### PR TITLE
adding if/endif support to llvm renderer

### PR DESCRIPTION
**Pull request by nicktalati**
This adds IF/ENDIF support to the LLVM renderer as part of the "Gated Store Rewrite to UOps.IF" bounty. This is the first of three pull requests as discussed here: https://github.com/tinygrad/tinygrad/pull/7006.

### CODE REVIEW

**Comment by geohot** [comment]
Can you write a test for this?

**Comment by Qazalin** [comment]
Passes a simple test, mergable once the is_terminated one is justified with a test.

**Comment by nicktalati** [comment]
Hi Qazalin,

Currently, the LLVM renderer is not adding any terminator instructions to blocks (other than branches handled by the if/endif logic). So I do believe the is_terminated check could technically be removed without altering functionality -- my motivation for including it was to guard against a potentially hard-to-find bug if any other branches or returns were added in the future. If that isn't the case or if it should be removed for the moment I'm happy to; otherwise I could use a bit more guidance on what a reasonable test would look like in this case.

**Comment by Qazalin** [comment]
Any green diff must be justified with a unit test.
The reviewers in this project will look at every line you add and ask: If I remove that line, will any test show red?

**Comment by nicktalati** [comment]
Thanks @Qazalin, I appreciate the explanation and think I am better understanding the standards of tinygrad. Given that, and since existing UOps don't support other terminator instructions, I think it best to remove that check; I'll take care of that now.

**Comment by Qazalin** [comment]
done in https://github.com/tinygrad/tinygrad/pull/7345

**Pull request closed without merging**
