### PR TITLE
Indicate fix for stale opencl program cache in error message

### PR DESCRIPTION
**Pull request by PaulGustafson**
Better error message when system update breaks OpenCL program caching  (#2588)

### CODE REVIEW

**Comment by geohot** [comment]
What is -30 in OpenCL terms?

**Comment by PaulGustafson** [comment]
CL_INVALID_VALUE


Code | OpenCL Error Flag | Function(s) | Description
-- | -- | -- | --
-30 | CL_INVALID_VALUE | clGetDeviceIDs, clCreateContext | This depends on the function: two or more coupled parameters had errors.


I'm also open to just throwing the cache warning on all error codes, but since I don't have a good understanding of them, I was just maximally specific (I know that -30 can get triggered by a stale cache/system upgrade).

When I get a chance, I'll push a patch with the version stamp on the disktensor that is a better fix.

**Comment by chenyuxyz** [comment]
just use `cl.CL_INVALID_VALUE`?

**Comment by PaulGustafson** [comment]
Yes, that's better.  Made the change.

**Comment by PaulGustafson** [comment]
Closing this since #2618 is a better fix

**Pull request closed without merging**
