### PR TITLE
Create tinyrvc.py

### PR DESCRIPTION
**Pull request by jbalthis**
bounty: voice changer model (so-vits-svc, rvc). make me sound like drake

*** WIP ***

...a beginning of sorts.

I plan to complete this bounty starting here at tailoring an rvc model and going from there to, hopefully, George doing a sick version of Started From the Bottom....

as a matter of fact, that is an appropriate theme for this code for me. 

please let me know if i am submitting this in a cringeworthy fashion and i'll fix things. 

i'm jason and look forward to working with you all.

### CODE REVIEW

**Comment by dosier** [comment]
No tinygrad in here?

**Review by dosier — CHANGES_REQUESTED** [review]
No tinygrad in here? Also, put it as a draft PR since this is still a WIP :). Furthermore, take a look at other examples to get a sense of the code style, this is very verbose.

**Comment by jbalthis** [comment]
Oh should I have built before submitting PR?? I wasn’t sure of expected procedure. My badOn Jul 23, 2023, at 5:12 AM, Stan ***@***.***> wrote:﻿
No tinygrad in here?

**Comment by jbalthis** [comment]
@dosier sure thing man. I had only started things earlier and meant this to be what a draft is and I should have known. I definitely plan to tackle the verbosity issue first thing

**Comment by jbalthis** [comment]
Should I resubmit the PR with the built tinygrad or wait until I get some more changes committed later today and do it all at once? I was only trying to make it known I had plans to complete the bounty, hopefully, and lock it. I apologize if I screwed up procedurally. I’ll catch on lolOn Jul 23, 2023, at 5:12 AM, Stan ***@***.***> wrote:﻿
No tinygrad in here?

**Comment by geohot** [comment]
Yea this isn't tinygrad code, will close.

**Comment by jbalthis** [comment]
Yeah I’m sorry about that George, I was only trying to show my intent until I could get back at my box to code tonight. Should I resubmit another PR with the correct code started?On Jul 23, 2023, at 9:03 PM, George Hotz ***@***.***> wrote:﻿
Yea this isn't tinygrad code, will close.

**Pull request closed without merging**
