### PR TITLE
remove per layer realize in llama

### PR DESCRIPTION
**Pull request by chenyuxyz**
previously needed due to kernel buffer count limit, seems fine to remove now

### CODE REVIEW

**Comment by chenyuxyz** [comment]
it found a variable scope bug!

**Comment by geohot** [comment]
I think I'm hitting the same one in mac benchmark, might be unrealized and just nondeterminism.

**Comment by geohot** [comment]
Yea, it's non deterministic. https://github.com/tinygrad/tinygrad/actions/runs/9148100711/attempts/1

@Qazalin we need that toposort fuzzer. I will also investigate where non-determinism is coming from.

**Comment by chenyuxyz** [comment]
this was changed to `contiguous`

**Pull request closed without merging**
