### PR TITLE
Training UNet3D

### PR DESCRIPTION
**Pull request by jla524**
Changes made:
- Implement iterator for training set
- Implement transformations
- Implement dice cross entropy loss

TODO:
- Support batch size > 1
- Implement LR warmup
- Run up to 4000 epochs
- Train the model (currently running out of memory on M1 Pro)
- Validate results (goal is 0.908 Mean DICE score)

### CODE REVIEW

**Comment by geohot** [comment]
Bounty locked, good luck!

**Comment by jla524** [comment]
Changes made in `tinygrad/`:
---------------------------------------------------------
files                           additions       deletions
---------------------------------------------------------
tinygrad/tensor.py                      1               1
---------------------------------------------------------
total                                   1               1

**Comment by jla524** [comment]
Changes made in `tinygrad/`:
```
---------------------------------------------------------
files                           additions       deletions
---------------------------------------------------------
tinygrad/tensor.py                      1               1
---------------------------------------------------------
total                                   1               1
```

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                         1               1
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                         1               1
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                         1               1
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                         1               1
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by geohot** [comment]
No update in a week

**Pull request closed without merging**
