### PR TITLE
Refactor _broadcast and Tensor.where

### PR DESCRIPTION
**Pull request by ZenginU**
Refactored the code with for loop

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                        12              23
------------------------------------------------------------
lines added in the tinygrad folder: -11
```

**Comment by geohot** [comment]
https://en.wikipedia.org/wiki/Wikipedia:Chesterton's_fence

**Comment by ZenginU** [comment]
@geohot 

 It is mentioned in the code` # TODO refactor this code along with the binary version above`. I believe it is not Chesterton's fence in that case

**Comment by wozeparrot** [comment]
https://github.com/tinygrad/tinygrad/commit/2d567ef688473734cd21f31ae9344d06d01d6ec4

**Comment by ZenginU** [comment]
> [2d567ef#diff-7703e7b63c9844f019ae3609629fd9c9bab290d11ae6608ed2d09edd49bab2dbL520](https://github.com/tinygrad/tinygrad/commit/2d567ef688473734cd21f31ae9344d06d01d6ec4#diff-7703e7b63c9844f019ae3609629fd9c9bab290d11ae6608ed2d09edd49bab2dbL520)

Oh I see thank you, TODO in "where" mislead me

**Pull request closed without merging**
