### PR TITLE
Quadric Layer in nn

### PR DESCRIPTION
**Pull request by diro5t**
introduces 'quadric learning' - second order hypersurface decision boundaries in quadric layers and has the proven potential to reduce model size significantly and therefore help to democratize and decentralize access to ai - based on my research and publication from back in the day (see example and repo for more background)

clean few new lines in tinygrad.nn.__init__.py

example: https://github.com/diro5t/deep_quadric_learning/blob/main/TinyQuadMNIST.ipynb

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/nn/__init__.py                   12               0
------------------------------------------------------------
lines added in the tinygrad folder: 12
```

**Comment by wozeparrot** [comment]
Usually we only promote layers into `nn` if they have been used in at least 3 models/very commonly used layers (like `Linear` or `Embedding`).

**Comment by diro5t** [comment]
i get that, but you say 'usually' - did you look at the example - this is so high level it can reduce parameters in all kinds of model paradigms - higher order neurons have been a subject in research not only by me (although i am one of the earliest)

does this mean there will be no further consideration/review of this feature?
thanks

**Comment by geohot** [comment]
Unless it’s a very common operation, the 3 model rule stands.

**Comment by diro5t** [comment]
could you please explain the 3 model rule a little further? i showed that significant model size reduction is possible in a feed forward  classifier. if i can show the same effect let’s say in a gan and in a 3rd paradigm that would fulfill it? thanks

**Comment by wozeparrot** [comment]
One of the main points of tinygrad is having a nice compact core, even if the 1000 line rule doesn't exist anymore. The 3 model rule is basically that a layer should be used in at least 3 popular models implemented in tinygrad, like how `Embedding` was [promoted](https://github.com/tinygrad/tinygrad/pull/798).

**Comment by diro5t** [comment]
Thanks for the clarification. Cheers and keep up the good work

**Pull request closed without merging**
