### PR TITLE
clear l2 by getting an astrunner so it doesn't get added to jit

### PR DESCRIPTION
**Pull request by chaosagent**
or we could have a ContextVar like INTERNAL_TENSOR_CALL

### CODE REVIEW

**Comment by wozeparrot** [comment]
I did context var here: [`371a8d4` (#3785)](https://github.com/tinygrad/tinygrad/pull/3785/commits/371a8d49bd38ab68f7f85efb83b47fbbb235c02c)

**Comment by chaosagent** [comment]
> I did context var here: [371a8d4 (#3785)](https://github.com/tinygrad/tinygrad/pull/3785/commits/371a8d49bd38ab68f7f85efb83b47fbbb235c02c), not sure which is better.

I didn't notice you did the same thing lol :sweat_smile: 

I like the idea of first-class support for doing tensor calls internally... maybe can replace do_update_stats and such too.

**Comment by geohot** [comment]
That "clear L2" hack should probably just be removed. It's unclear if it's even useful.

HSA should support proper L2 clearing.

**Comment by wozeparrot** [comment]
Yea, its probably better just to wait for #3698, but then clear_l2 doesn't do much on non-HSA platforms, but then again, not sure if it ever did.

**Comment by chaosagent** [comment]
> That "clear L2" hack should probably just be removed. It's unclear if it's even useful.

the original 1024*1024 isn't even as large as xtx's l2 cache, let along l3 :sweat_smile: 

it does do something though, i was able to get >1TB/s gemv without it in isolated test (but not with a 100MB clear)

**Comment by chenyuxyz** [comment]
fyi #3785 is merged

**Comment by wozeparrot** [comment]
I removed the cache thing from #3785, so 3785 is the same as the old threefry pr since it didn't seem to do anything. So this is still an issue.

**Pull request closed without merging**
