### PR TITLE
Tensor Core support on M1 ($2000 bounty)

### PR DESCRIPTION
**Pull request by geohot**

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/cstyle.py                14               0
tinygrad/codegen/linearizer.py            71              14
tinygrad/helpers.py                        1               0
tinygrad/runtime/ops_metal.py              1               0
tinygrad/shape/shapetracker.py             9               5
------------------------------------------------------------
total                                     96              19
------------------------------------------------------------
lines added in the tinygrad folder: 77
```

**Comment by geohot** [comment]
```
kafka@tubby:~/fun/tinygrad$ TC=0 BIG=1 MPS=1 python3 test/test_speed_v_torch.py TestBigSpeed
 exp                            16384x16384    6.60 ms (   81.30 GFLOPS   325.20 GB/s) in torch,    6.20 ms (   86.54 GFLOPS   346.17 GB/s) in tinygrad,    0.94x faster     536.87 MOPS  2147.48 MB
.gemm                            1024x 1024    1.27 ms ( 1696.27 GFLOPS     9.94 GB/s) in torch,    1.73 ms ( 1242.46 GFLOPS     7.28 GB/s) in tinygrad,    1.37x slower    2147.48 MOPS    12.58 MB
.gemm                            2048x 2048    2.51 ms ( 6848.21 GFLOPS    20.06 GB/s) in torch,   12.36 ms ( 1389.69 GFLOPS     4.07 GB/s) in tinygrad,    4.93x slower   17179.87 MOPS    50.33 MB
.gemm                            4096x 4096   17.16 ms ( 8009.55 GFLOPS    11.73 GB/s) in torch,   98.28 ms ( 1398.47 GFLOPS     2.05 GB/s) in tinygrad,    5.73x slower  137438.95 MOPS   201.33 MB
```

```
kafka@tubby:~/fun/tinygrad$ TC=1 BIG=1 MPS=1 python3 test/test_speed_v_torch.py TestBigSpeed
 exp                            16384x16384    6.69 ms (   80.23 GFLOPS   320.93 GB/s) in torch,    6.25 ms (   85.90 GFLOPS   343.61 GB/s) in tinygrad,    0.93x faster     536.87 MOPS  2147.48 MB
.gemm                            1024x 1024    1.27 ms ( 1688.38 GFLOPS     9.89 GB/s) in torch,    0.70 ms ( 3068.57 GFLOPS    17.98 GB/s) in tinygrad,    0.55x faster    2147.48 MOPS    12.58 MB
.gemm                            2048x 2048    2.51 ms ( 6833.68 GFLOPS    20.02 GB/s) in torch,    2.54 ms ( 6776.40 GFLOPS    19.85 GB/s) in tinygrad,    1.01x slower   17179.87 MOPS    50.33 MB
.gemm                            4096x 4096   17.15 ms ( 8013.56 GFLOPS    11.74 GB/s) in torch,   23.47 ms ( 5856.12 GFLOPS     8.58 GB/s) in tinygrad,    1.37x slower  137438.95 MOPS   201.33 MB
```

**Comment by geohot** [comment]
So this is probably the wrong way to think about this. WMMA requires support for local tensors first. Accelerate the memory before we accelerate the compute.

**Comment by philipturner** [comment]
Here is the source code for the SIMD futures GEMM. Didn't have enough time to investigate Stream-K; it seems slower. So instead I used a block size of 32x32 or 48x48 depending on the matrix size. Apple only uses power-2 block sizes and missed the 48x48 sweet spot. So did you.

https://twitter.com/philipturnerar/status/1672107009674469376

SGEMM

HGEMM

**Comment by geohot** [comment]
Not going to do it like this.

**Pull request closed without merging**
