### PR TITLE
ruff: in-dict-keys

### PR DESCRIPTION
**Pull request by roelofvandijk**
https://docs.astral.sh/ruff/rules/in-dict-keys/

### CODE REVIEW

**Comment by chenyuxyz** [comment]
i wanted to do this before but sometimes it's less readable, especially when it's not immediately clear that the iterator is a dict

**Comment by geohot** [comment]
Why are there exceptions to the rule?

**Comment by roelofvandijk** [comment]
`safetensors.safe_open` does not support direct iteration over the keys like python `dict`s

**Comment by geohot** [comment]
I'm not dealing with exceptions. keys is fine

**Pull request closed without merging**
