### PR TITLE
Downgrade wgpu to prevent sd segfault

### PR DESCRIPTION
**Pull request by wpmed92**
Starting with  `wgpu v0.19.0 `, stable diffusion segfaults with:

>  File "/Users/ahmedharmouche/Documents/tinygrad/tinygrad/runtime/ops_webgpu.py", line 56, in _copyout
>     buffer_data = self.dev.queue.read_buffer(src, 0)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/ahmedharmouche/Documents/tinygrad/venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_api.py", line 3427, in read_buffer
>     tmp_buffer._map("READ_NOSYNC").sync_wait()
>   File "/Users/ahmedharmouche/Documents/tinygrad/venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 268, in sync_wait
>     return self.finish()
>            ^^^^^^^^^^^^^
>   File "/Users/ahmedharmouche/Documents/tinygrad/venv/lib/python3.12/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 260, in finish
>     raise RuntimeError(f"Waiting for {self.title} timed out.")
> RuntimeError: Waiting for buffer.map timed out.
> zsh: segmentation fault  PYTHONPATH=. WEBGPU=1 python3 examples/stable_diffusion.py --seed 0 --steps 1

Downgrading to the latest version which works, which is `0.18.1`. Will report the bug in the wgpu repo.

### CODE REVIEW

**Comment by chenyuxyz** [comment]
i tried master with v0.19.2 and this pr with v0.18.1 on M1 Max, `PYTHONPATH=. WEBGPU=1 DEBUG=2 python examples/stable_diffusion.py --seed 0 --noshow --timing` can generate image on both. validation failed on both with the same error i reported before on discord

what's your setup that crashes and is there a minimum repro? CI seems to work with v0.19 too

**Comment by wpmed92** [comment]
On my M1 pro it consistently produces the error I attached starting from v0.19.0. I’ll attach a minimal reproducible example

**Comment by wpmed92** [comment]
I know about the validation error, this pr was specifically for the segfaulty

**Comment by chenyuxyz** [comment]
discussed in meeting, fine to merge this so it works for you, with the idea to fix and bring it back to latest

**Comment by wpmed92** [comment]
Filed a ticket in the repo of the lib: https://github.com/pygfx/wgpu-py/issues/650 I'd prefer an option to not have this timeout, let's see what they say.

**Pull request merged**
