### PR TITLE
RetinaNet training

### PR DESCRIPTION
**Pull request by marcellofuschi**
For now, the only thing I'm sure works is the focal loss.

Don't even know if it's enough for a bounty lock, I just wanted to put it out there. See TODO comments in the code to know what I'm tackling next 🤞 

Feedback appreciated

### CODE REVIEW

**Comment by geohot** [comment]
Good enough for a bounty lock for me!

**Comment by lewis-carson** [comment]
I have a bit of work done in the same thing. Since you're tackling this, I'll stop working on it. Here's my branch for reference: https://github.com/lewis-carson/tinygrad/tree/train_retinanet

**Comment by marcellofuschi** [comment]
Thanks for sharing!

**Comment by aseok** [comment]
@geohot is related bounty still locked?

**Comment by mszsorondo** [comment]
@geohot
made a new draft PR https://github.com/tinygrad/tinygrad/pull/1578

**Pull request closed without merging**
