### PR TITLE
CMPLT output bool in ops_cpu.py and ops_torch.py

### PR DESCRIPTION
**Pull request by segf00lt**
Patch for #1757.

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/runtime/ops_cpu.py                1               1
tinygrad/runtime/ops_torch.py              1               1
------------------------------------------------------------
total                                      2               2
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by geohot** [comment]
So that issue is about the compiled backends, but it should really be all of them. This is a more in depth project than a two line change though, it needs tests and to carefully think through the desired behavior

**Comment by segf00lt** [comment]
Right, at first I thought since you refer to UOps in the issue it would be something higher level. But having taken another look the I see renderers cast to a float.

I assume this was done because the backends are statically typed and so just having CMPLT return a bool won't work(?)

Why is it better to output a bool rather than a 0.0 or 1.0 valued float? Does it have to do with the code generator needing a way of keeping track of what values the float could have and thus be able to optimize around that?

**Comment by geohot** [comment]
No updates in 2 weeks, closing. Though I like this idea

**Pull request closed without merging**
