### PR TITLE
viz ui fixes

### PR DESCRIPTION
**Pull request by Ry4nW**

### CODE REVIEW

**Comment by Qazalin** [comment]
the scroll is kinda laggy, I think notion does this correctly:

https://github.com/user-attachments/assets/8b3149de-7064-4738-b20b-d580abba50d0

**Comment by geohot** [comment]
Yea, scrolling shouldn't use javascript.

**Comment by Qazalin** [comment]
For the resize/collapse I think figma does it right.

right now when i resize the left sidebar the right one changes too
there should be one collapse button that just focuses the screen on the center.

https://github.com/user-attachments/assets/87d3fcff-92e2-4f20-9360-df62baafe994

**Comment by Qazalin** [comment]
scroll is better but it stopped working when I hit this kernel
`VIZ=1 python3 test/test_schedule.py`
image

**Comment by Qazalin** [comment]
I just tried to go down with arrow keys:
image

VIZ=1 test/test_ops.py TestOps.test_tiny_add

**Comment by Qazalin** [comment]
collapse functions well! 
can you give this a max width for resize:
image

**Comment by Qazalin** [comment]
autoscroll doesn't work and the scroll is laggy, I don't like this
```
    // reduce scroll lag
    if (Date.now() - lastPress > 300) lastPress = Date.now();
```
why do you need any javascript for the default scroller?

**Comment by Ry4nW** [comment]
there's too many rerenderings otherwise. not laggy anymore, just slow. maybe some select and enter for faster scroll, but there's already mouse scroll for that

**Comment by Qazalin** [comment]
after many feedback iterations, when I see bugs in the simplest possible test I lose trust in this diff.
image

That lag is unacceptable, I don't see why the speed would be any different than master.

**Comment by Qazalin** [comment]
I'd merge two simple, small PRs for that vscode opener and collapse/resize.

**Pull request closed without merging**
