### PR TITLE
Fix: auto create parent dir when downloading file

### PR DESCRIPTION
**Pull request by dosier**
Did this because some examples that use `download_file` expect a weights dir, this way the user doesn't have to manually create it. 
- also removed duplicate import `os`

### CODE REVIEW

**Comment by geohot** [comment]
Test for this?

**Comment by dosier** [comment]
> Test for this?

Added test, I mocked the download op cuz no internet in CI

**Comment by geohot** [comment]
No internet in CI?

**Comment by dosier** [comment]
> No internet in CI?

In the existing test, I saw "no internet tests in CI":
```
@unittest.skipIf(getenv("CI", "") != "", "no internet tests in CI")
class TestFetch(unittest.TestCase):
```
from which I figured that we cannot make remote requests. 

But if that is outdated, I can change it :)

**Comment by geohot** [comment]
meh, LGTM

**Pull request merged**
